codecov/worker

- database/models/core.py
- database/models/reports.py
- database/tests/factories/core.py
- database/tests/unit/test_model_utils.py
- database/tests/unit/test_models.py
- database/utils.py
- helpers/config.py
- helpers/tests/unit/test_config.py
- services/report/__init__.py
- services/tests/test_report.py
- services/tests/test_repository_service.py
- tasks/tests/integration/test_notify_task.py
- tasks/tests/integration/test_sync_pull.py
Moving Commit.report to GCS. The field name is actually 'report_json', but that's not super important.
Adjusting tests as well.
> Move Commit.report to GCS

- requirements.in
- requirements.txt
https://github.com/codecov/shared/pull/15 fixes an issue causing a lot of `sync_repos` failures. the PR was merged on main, but the hash used here is a hash that was rebased atop the currently-deployed `shared` hash. so if we deploy worker with this, it will only include the fix from `shared` and not other changes. …
> fix: include fix for missing language normalization in sync_repos

- database/models/core.py
- tasks/tests/unit/test_trial_expiration.py
- tasks/trial_expiration.py
Added the `pretrial_users_count` field to the owner's model and the trial expiration task. The user count will be that value if it exists, otherwise 1
> add pretrial_user_count to expiration task

- database/models/core.py
- database/models/reports.py
- database/tests/unit/test_model_utils.py
- database/utils.py
Passing an object as the default value to `ArchiveField` (such as `{}`)
means that we always return the same reference to multiple objects. So they're shared.
(thanks @scott-codecov for pointing that out)
So instead we will pass a class and call the class, creating a new object if we have to use it.
Noticed I hacked it a little for the default of the defaults to return `None`.
We can do the same if we ever need more complex values, or just create a new class.
I also moved the log of dbfield and archive_field None to be DEBUG and not INFO.
We are getting that quite a lot and it's making support's work hard.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result …
> fix: don't share default values in ArchiveField

- helpers/checkpoint_logger.py
deployed with error severity to loudly flag whether the `UploadFlow` logs were hooked up right. downgrading to warning to lessen noise for support folks
> fix: ezpz: downgrade checkpoint logger errors to warnings

- tasks/base.py
- tasks/upload.py
`UploadTask` retries seem to be broken and i'm not sure how long ago they broke
the first problem is in `tasks/base.py`: celery's `apply_async()` function takes an `options` dict which may have a `"headers"` key. i believe it's `None` by default (docs aren't explicit) and as a result we attempt `**None` which errors with:
```
'NoneType' object is not a mapping
```
the fix for this problem is straightforward
second problem was recently introduced (by me). by changing `self.retry()` to `self.retry(args=args, kwargs=kwargs)`, i excluded the `repoid` and `commitid` arguments which led to an exception in `celery_task_router.py`:
```
_get_user_plan_from_repoid() missing 1 required positional argument: 'repoid'
```
strangely, the clearest fix for a missing positional argument is... to add it to …
> fix: unbreak upload retries (two bugs)

- services/report/languages/pycoverage.py
- services/report/languages/tests/unit/test_pycoverage.py
Recently when testing the docs for integrating ATS I did [this commit](https://app.codecov.io/gh/giovanni-guidini/ats-data/commit/c24c1db8aa27fcda2d311fdcd293c20697030389)
for which processing failed. Checking the logs it failed because of
```
[... removed stack trace...]
File "/worker/services/report/languages/pycoverage.py", line 56, in process
report_file.append(
File "/usr/local/lib/python3.10/site-packages/shared/reports/resources.py", line 341, in append
raise ValueError("Line number must be greater then 0. Got %s" % ln)
ValueError: Line number must be greater then 0. Got 0
```
Indeed when I donwloaded and checked the uploaded files there were 3 of them with `executed_lines: [0]`.
They were all `__init__.py` files. Idk why that happened, to be honest. It looks strange because the 3 …
> fix: handle reports with line 0 executed

- helpers/sentry.py
Add Sentry Cron Monitoring feature for Codecov org. This should add monitoring for every celery type tasks in the repo and data should auto-populate on the Sentry dashboard after the first time each task is ran. This change does not add alerting for the tasks.
> feat: Add cron monitoring for celery tasks (#362)

- services/notification/notifiers/status/base.py
- services/notification/notifiers/tests/unit/test_status.py
Resolves https://github.com/codecov/engineering-team/issues/350
Only send status notifications when the payload has changed from the last time we sent the same notification.
> feat: Only send status checks when payload has changed

- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/tests/unit/test_comment.py
This edits the footer to have a feedback link dedicated to the patch cov only format 
> patch only cov feedback link

- requirements.txt
- services/comparison/__init__.py
- services/comparison/tests/unit/test_behind_by.py
- services/notification/notifiers/tests/integration/cassetes/test_comment/TestCommentNotifierIntegration/test_notify.yaml
- services/notification/notifiers/tests/integration/cassetes/test_comment/TestCommentNotifierIntegration/test_notify_gitlab.yaml
- services/notification/notifiers/tests/integration/cassetes/test_comment/TestCommentNotifierIntegration/test_notify_new_layout.yaml
- services/notification/notifiers/tests/integration/cassetes/test_comment/TestCommentNotifierIntegration/test_notify_with_components.yaml
- services/notification/notifiers/tests/integration/test_comment.py
- services/notification/notifiers/tests/unit/test_comment.py
- tasks/tests/integration/cassetes/test_notify_task/TestNotifyTask/test_simple_call_status_and_notifiers.yaml
- tasks/tests/integration/test_notify_task.py
This PR changes get_behind_by to use get_branch instead of get_branches because of a GH API rate limiting issue.
Instead of listing all branches in a repo via the API we now fetch only the one we are looking for, in this case the base branch of an open PR.
This commit also makes changes to the requirements by updating shared to the latest version in order to use get_branch.
Changes had to be made to existing integration tests as they we re-run, cassettes were updated.
> Use get_branch in get_behind_by instead of get_branches

- services/comparison/__init__.py
Handle key error with BB branches in the short term
> Handle key error for now

- tasks/__init__.py
- tasks/preprocess_upload.py
- tasks/tests/unit/test_preprocess_upload.py
move carry forwarding to a new seperate task that will get called when creating a new db report instance
> carry forward flags in a seperate task 

- tasks/upload_finisher.py
The reason for not scheduling the notify was missing here, which was confusing.
> Add missing log for not scheduling notify

- database/tests/factories/core.py
- services/decoration.py
- services/tests/test_decoration.py
Uploads while undergoing a trial shouldn't affect the monthly uploads post trial. This is a code change to adjust this in the worker level
- Adding logic to determine the monthly upload created date + tests
- Adding some properties + tests to the plan service
> Adjust logic for trialing customers monthly upload limit

- services/notification/notifiers/checks/base.py
- services/notification/notifiers/status/base.py
The `CheckNotifier` inherits from `StatusNotifier` which is where notification caching was happening.  `CheckNotifier` overrides the `notify` method but does not implement the caching.  This PR refactors where the caching happens such that it can easily be reused in both base notifier classes.
> ref: Make sure both base status notifiers cache notifications

- database/models/core.py
- services/notification/notifiers/comment/__init__.py
- services/notification/notifiers/tests/integration/test_comment.py
- services/notification/notifiers/tests/unit/test_comment.py
- tasks/tests/integration/test_notify_task.py
https://github.com/codecov/engineering-team/issues/389
Companion PR to https://github.com/codecov/codecov-api/pull/108
If a pull is the 1st for a repo then we want to show different copy in the PR comment.
> feat: Add different comment message for 1st time pulls

- services/notification/notifiers/mixins/message/__init__.py
- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/tests/integration/test_comment.py
- services/notification/notifiers/tests/unit/test_checks.py
- services/notification/notifiers/tests/unit/test_comment.py
- tasks/tests/integration/test_notify_task.py
Reverts #91 
https://github.com/codecov/engineering-team/issues/296
> Revert "Move feedback link out of footer section and always include at the bottom of a comment

- tasks/label_analysis.py
- tasks/tests/unit/test_label_analysis.py
This change is intended to work with the PATCHing of labels by the CLI after collecting them.
Currently doing that doesn't trigger another task in the worker. SO if the labels arraive after we finished calculating we are left with incomplete results on the database. That is fine as the CLI will calculate again.
I think this change might have been a bit premature, but the idea is to have a different way of handling the calculation if we already have results. Then we simply calculate the final result using the saved labels and add in the requested labels that we might not have had the first time around. This would be much much faster than calculating everything again.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional …
> Different handling label analysis if result already calculated

- dockerscripts/Dockerfile.circle
[infrastructure-team#120](https://github.com/codecov/infrastructure-team/issues/120)
> chore(berglas) update berglas distribution method

- tasks/label_analysis.py
In the case where we have some missing information we were saving the errors as part of the result dict (in the database).
There's a dedicated table for the larq errors, they should not be saved in the database.
THese changes fix that adding the errors to the dict to return only after savign the real results.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, …
> chore: don't save errors in `LabelAnalysisRequest` object

- database/models/reports.py
- services/notification/__init__.py
Fixes: https://github.com/codecov/internal-issues/issues/65
> fix: no longer set status for deleted (in UI) flags

- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/tests/unit/test_comment.py
sometimes a PR has changed files, but all changed files has patch coverage 100%. Currently, we have a bug that prints out the header without the printing anything in the table. In this case, we don't want anything to be printed out, as we only care about files with patch coverage < 100% 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of …
> fix bug when there's changed files, but none have missing cov lines

- tasks/backfill_commit_data_to_storage.py
This was previously resulting in the task name of `app.tasks.TaskGroupConfig.archive.BackfillCommitDataToStorage`
> fix: Archive task name

- services/report/report_builder.py
- services/report/tests/unit/test_report_builder.py
fixes https://l.codecov.dev/fYqS4O
There was a situation where you only get `SpecialLabelsEnum` and so we were not calling
`_possibly_modify_line_to_account_for_special_labels` (which is the thing that transforms
the special label ENUM into a STR - so we can save it in the DB)
Now this is giving an error, so we need to fix it. These changes do fix it.
But why was that check there in the first place?
I can only theorize reasons... it might be to save processing time (since changing every line of
every file in the report is a lot of lines), and this condition simply slipped. OR it might indicate
some config error in the ATS process - e.g. we should never just receive the global label.
I suppose that we might have introduced this condition afterwards because when the code was written
it was …
> fix: always modify line to account for special labels

- requirements.in
- requirements.txt
- services/template.py
- services/tests/test_template.py
- templates/test.html
- templates/test.txt
This commit creates the TemplateService that uses
jinja to get and render templates.
This TemplateService provides the get_template method to get a rendered template. It takes the file name of the template as an arg and the template variables as the kwargs.
Templates should be added into the templates directory at the top level of the repository. This commit creates two example templates.
> Add templates using jinja2

- conftest.py
- helpers/email.py
- services/smtp.py
- services/tests/test_smtp.py
* Email helper class that wraps EmailMessage
* SMTPService class that creates connection to SMTP server using config options in services.smtp
* send method on SMTPService that takes Email as an arg to send an email using the SMTP connection
> Add SMTPService and Email helper

- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/tests/integration/test_comment.py
- services/notification/notifiers/tests/unit/test_comment.py
> updating header based on product team feedback

- services/report/fixes.py
- services/report/parser/legacy.py
- services/report/parser/tests/unit/test_version_one_parser.py
- services/report/parser/types.py
- services/report/parser/version_one.py
- services/report/raw_upload_processor.py
- services/report/tests/unit/test_parser.py
- services/report/tests/unit/test_process.py
This PR changes the name of the path_fixes
section in the ParsedRawReport classes to report_fixes.
For more information on report fixes:
https://docs.codecov.com/docs/fixing-reports
For more information on path fixes:
https://docs.codecov.com/docs/fixing-paths
Fixes: https://github.com/codecov/codecov-cli/issues/207
> Change names of path_fixes to report_fixes

- services/static_analysis/__init__.py
- services/static_analysis/tests/unit/test_static_analysis_comparison.py
Fix codecov/engineering-team#650
Recently we made changes to static analysis process of the CLI so it doesn't fails completely
if there are issues analysing a file or uploading it to GCS.
I think this inadvertedly broke the expectation of label analysis that all files in the static analysis
are uploaded and ready to be used. Or some other misterious bug is causing some snapshots to be missing
This is causing issues that the label analysis is not processing correctly. So we are now guarding
against missing snapshots in HEAD or BASE.
Sadly for ats, it only as good as the data it has. And being conservative (and safe) is important to us.
So if we can't make an educated guess about a change, the procedure so far is to just run everything.
That's the fallback, assume the entire file is …
> fix: better handle missing static analysis info

- .github/workflows/ci.yml
- .github/workflows/self-hosted-release-pr.yml
- .github/workflows/self-hosted-release.yml
- Makefile
> Use ATS docker action

- services/license.py
- services/tests/test_activation.py
this PR changes the behaviour of `get_installation_plan_activated_users` to no longer count one user in multiple orgs as multiple users to match the behaviour in the API
Fixes: https://github.com/codecov/worker/issues/121
> Fix plan_activated_users count for an installation

- .pre-commit-config.yaml
- requirements.in
- requirements.txt
as title
to install:
```
pip install -r requirements.txt
pre-commit install
```
> add pre-commit config to worker + lint hook

- services/report/languages/cobertura.py
- services/report/languages/tests/unit/test_cobertura.py
This PR changes the Cobertura XML parsing to do case-insensitive handling of the branch attribute on a line, and to handle the case where both the condition elements and missing branches attributes don't exist on a partially covered line.
Fixes: https://github.com/codecov/feedback/issues/61
Fixes: https://github.com/codecov/feedback/issues/67
> Fix cobertura XML parsing

- database/tests/factories/core.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
This is currently happening in the API's upload endpoint (https://github.com/codecov/codecov-api/pull/200) and can actually be quite slow sometimes.  Let's do it in the worker instead.
More context here: https://sentry.slack.com/archives/C0557QXEW4V/p1697657512609759
> Update repo updatestamp in upload task

- tasks/label_analysis.py
- tasks/tests/unit/test_label_analysis.py
Includes some metrics so we can see the general health of label analysis task
> chore: add general metrics to label analysis task

- helpers/checkpoint_logger/__init__.py
- helpers/tests/unit/test_checkpoint_logger.py
i made a sloppy mistake. i treated `BaseFlow` subclass values as if they were sorted by declaration order, but they're just strings and they're sorted lexicographically. example:
```
class Foo(BaseFlow):
PROCESSING_BEGIN = auto()
INITIAL_PROCESSING_COMPLETE = auto()
assert Foo.PROCESSING_BEGIN < Foo.INITIAL_PROCESSING_COMPLETE
```
`PROCESSING_BEGIN` is declared before `INITIAL_PROCESSING_COMPLETE`, so i want `PROCESSING_BEGIN < INITIAL_PROCESSING_COMPLETE` to be true. but with lexicographic order, "I" is before "P" so it's flipped.
`Foo._member_names_` remembers the declaration order and we can fix the bug by overriding `__eq__()` and friends to make them compare based on declaration order.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in …
> fix: checkpointlogger: use enum declaration order instead of value order

- requirements.in
- services/report/languages/cobertura.py
- services/report/languages/tests/unit/test_cobertura.py
This PR is taking the changes in #118, and putting them behind a config option in the `codecov.yml` specifically
```yaml
parsers:
cobertura:
handle_missing_conditions: bool # default False
```
Depends on: https://github.com/codecov/shared/pull/67
> Add back previous cobertura behaviour and put newer behaviour behind config option

- helpers/checkpoint_logger/__init__.py
- helpers/tests/unit/test_checkpoint_logger.py
tested by running real uploads through my local service instead of relying on unit tests and staging. i'll make sure to do that more in the future as these bugs were easily catchable before PR time if i were more diligent
i read somewhere that defining `__gt__` and `__eq__` should fill in for other comparison functions if they aren't defined. i saw that wasn't true for `__lt__` in the last bugfix and defined that one manually, but i thought surely `__lt__` and `__eq__` are enough to define `__le__` and did not verify
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. …
> fix: define __le__ instead of just __lt__ for BaseFlow

- services/repository.py
- tasks/commit_update.py
- tasks/preprocess_upload.py
- tasks/tests/unit/test_commit_update.py
- tasks/tests/unit/test_preprocess_upload.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
The pre-process commit task doesn't check if the commit data has
been already pulled from the provider. This can cause an error where
the parent commit is not found to carryforward the reports.
These changes make sure that we try to update the commit info if necessary.
It also moves the function - that was repeated in a few places - to
RepositoryService.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, …
> fix: make sure to update commit info

- helpers/checkpoint_logger/__init__.py
- helpers/tests/unit/test_checkpoint_logger.py
- tasks/notify.py
- tasks/tests/unit/test_notify_task.py
mirror `CheckpointLogger` data in prometheus, once this is flowing we can delete the statsd/sentry stuff
> feat: add prometheus instrumentation to checkpointlogger

- database/utils.py
We see in the logs that we're getting valid reads after ~3 seconds (the current sleep interval) so let's decrease the total timeout (and sleep interval).
> Decrease archive field read timeout

- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/tests/unit/test_comment.py
Resolves https://github.com/codecov/engineering-team/issues/475
Show the ATS message to applicable repos only and otherwise show info about the browser extension.
* announcements section will still show up to 25% of PR comments that do not have the comment layout overridden in their YAML
* if the ATS announcement applies to the comment then favor that:
- must not be using ATS already
- must be a Python repo
- must have sufficiently large chunks size
* otherwise fallback to one of the other general announcements (currently just the browser comment announcement)
> feat: Update announcements section of PR comment

- services/billing.py
- services/decoration.py
- services/tests/test_decoration.py
- Add Team plan concept to upload limits, this plan has a 2500 limit.
- Add Team plan to be recognized as a billing plan
> feat: add team plan to billing and upload limits

- helpers/checkpoint_logger/__init__.py
- helpers/tests/unit/test_checkpoint_logger.py
- tasks/tests/unit/test_notify_task.py
- tasks/tests/unit/test_upload_finisher_task.py
fix `notification_latency` and other `UploadFlow` metrics by ceasing to inject the flow name into the value of each checkpoint in the flow
```
>>> json.dumps({ MyEnum.A: 1337 })
"{ 'MyEnum.A': 1337 }"
"{ 'A': 1337 }"
```
when serializing `MyEnum` checkpoints between tasks, i tried to inject the enum name into each enum value so `MyEnum.A` would have a value of `"MyEnum.A"` instead of just `"A"`. the idea being, when trying to continue `MyEnum` in the next task, we could completely validate that the checkpoints data we're deserializing really came from `MyEnum`
my hacky method for accomplishing this didn't work and adding further complexity to this validation is not worth it, so this PR rips it out. there is still some protection against mismatching flows: checkpoints data is put into …
> fix: remove some buggy validation of BaseFlow values

- services/tests/test_smtp.py
some smtp unit tests are broken in ATS sometimes, this PR attempts to fix them
> tests: update smtp unit tests

- requirements.in
- requirements.txt
- services/github_marketplace.py
Shared diff: https://github.com/codecov/shared/compare/fd16807a2b942454f2dff9583ecdd713c514a7f3...729a9321bfa96dd768dbf4bdcaab07e8fd8d82cd
> Update shared version

- .github/workflows/ci.yml
It's helpful to test "dangerous" changes before they make into main.
> allow staging deploy when pushing to staging

- database/models/reports.py
- rollouts/__init__.py
- services/archive.py
- services/report/__init__.py
- services/report/labels_index.py
- services/report/raw_upload_processor.py
- services/report/tests/unit/test_labels_index.py
- services/report/tests/unit/test_sessions.py
- services/tests/unit/test_archive_service.py
context: codecov/engineering-team #768
Creates a rollout for label compression. This is gonna help us to test and safely release the feature in the wild.
Notice that currently the label compression does nothing.
There are comments similar to `TODO: needs shared update`.
The update in question is https://github.com/codecov/shared/pull/79
So these changes mostly prep the terrain for future changes that will actually do something,
and add the guardrails to avoid issues when deploying.
In particular it adds some helper methods to the `ArchiveService`, creates a kinda-stubbed `LabelsIndexService`,
passes more data to the `_adjust_sessions` portion of `raw_upload_processor` where most changes will occur.
If you're curious as to what the end result will probably look like see …
> Prep the terrain for reports with label compression.

- helpers/labels.py
- requirements.in
- requirements.txt
- services/archive.py
- services/report/__init__.py
- services/report/labels_index.py
- services/report/languages/pycoverage.py
- services/report/languages/tests/unit/test_pycoverage.py
- services/report/raw_upload_processor.py
- services/report/report_builder.py
- services/report/tests/unit/test_labels_index.py
- services/report/tests/unit/test_report_builder.py
- services/report/tests/unit/test_sessions.py
- services/tests/unit/test_archive_service.py
- tasks/label_analysis.py
- tasks/tests/unit/test_label_analysis.py
This is a lot of code, and I'll probably break this PR in several others. I'm looking for early feedback here. It's a lot of code and a lot of changes.
This depends on the changes in https://github.com/codecov/shared/pull/79. Check that PR for context.
* `services/report/labels_index.py` houses the `LabelIndexService`. This little bit of code controls read/write in the label index file (that is separate from `chunks.txt`). It does the loading and unloading of the `Report._labels_index` as needed.
* `MinioEndpoints.label_index` and functions to write-to and read-from the file. There can be 1 such file for each `CommitReport`.
* `services/report/raw_upload_processor.py::make_sure_orginal_report_is_using_label_ids` encodes the labels in a `Report` prior to merging it with another report (if …
> WIP - encode labels into index

- services/report/raw_upload_processor.py
Fixes: https://github.com/codecov/engineering-team/issues/138
> Add logs for some path fixes for each raw upload processing

- tasks/tests/unit/test_upload_finisher_task.py
- tasks/upload_clean_labels_index.py
- tasks/upload_finisher.py
If the processed upload includes a flag that is carryforward
AND "labels" mode, we enqueue the CleanLabelsIndexTask.
Depends on https://github.com/codecov/worker/pull/205
I tried to be conservative, but it's possible that - despite
using the flag with labels - no labels are uploaded. It's
also possible that there's nothing to do. But these are small
details.
ps.: To see that indeed we have an "arguments" and "flag" in
"processing_results" I looked at logs for the message
"Scheduling notify task" :wink:
closes codecov/engineering-team#768
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my …
> feat: call CleanLabelsIndexTask

- services/comparison/__init__.py
- services/comparison/conftest.py
- services/comparison/overlays/critical_path.py
- services/comparison/tests/unit/overlay/test_critical_path.py
- services/comparison/tests/unit/test_behind_by.py
- services/comparison/tests/unit/test_comparison_proxy.py
- services/comparison/types.py
- services/notification/__init__.py
- services/notification/notifiers/codecov_slack_app.py
- services/notification/notifiers/generics.py
- services/notification/notifiers/hipchat.py
- services/notification/notifiers/mixins/message/__init__.py
- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/mixins/status.py
- services/notification/notifiers/status/base.py
- services/notification/notifiers/tests/conftest.py
- services/notification/notifiers/tests/integration/test_comment.py
- services/notification/notifiers/tests/unit/test_checks.py
- services/notification/notifiers/tests/unit/test_comment.py
- services/notification/notifiers/tests/unit/test_hipchat.py
- services/notification/notifiers/tests/unit/test_slack.py
- services/notification/notifiers/tests/unit/test_status.py
- services/notification/notifiers/tests/unit/test_webhook.py
- services/notification/notifiers/webhook.py
- services/notification/tests/unit/test_notification_service.py
- tasks/compute_comparison.py
- tasks/notify.py
- tasks/save_report_results.py
- tasks/tests/unit/conftest.py
closes https://github.com/codecov/worker/issues/203
no logical changes, pure rename
hoping tests exercised every usage of these variables. i grepped for some usage patterns but my brain would melt if i tried to go through every occurrence of the word "base" to make sure none refer to this
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of …
> chore: rename comparison base commit fields to project/patch base

- database/models/core.py
- services/decoration.py
- tasks/manual_trigger.py
Default to coverage type
Follow up from https://github.com/codecov/worker/pull/190
> fix: Add some missing report type filtering

- services/notification/notifiers/tests/conftest.py
- services/notification/notifiers/tests/unit/test_comment.py
- services/urls.py
Fixes: https://github.com/codecov/worker/issues/172
> fix: update members_url_self_hosted to correct value

- requirements.in
- requirements.txt
- services/bundle_analysis.py
- tasks/tests/unit/test_bundle_analysis_processor_task.py
* update shared version
* use new function introduced here: https://github.com/codecov/shared/pull/102
> fix: Use updated bundle analysis bucket name function

- tasks/compute_comparison.py
This is an attempt to fix an issue where flag comparisons are not being saved to the database.
> fix: commit to db after computing flag and component comparisons

- database/models/core.py
- services/bundle_analysis.py
- services/lock_manager.py
- services/tests/test_bundle_analysis.py
- tasks/__init__.py
- tasks/bundle_analysis_notify.py
- tasks/tests/unit/test_bundle_analysis_notify_task.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
This is a separate task for now and results in a separate PR comment.  Ideally this would be part of the existing notify task but there's some significant refactoring work that needs to be done first to support that.
This new task runs at the end of the bundle analysis processor chain and posts a PR comment with information regarding the bundle analysis comparison across base/head commits.
Depends on the migration in https://github.com/codecov/codecov-api/pull/320
> feat: Bundle analysis notify task

- services/bundle_analysis.py
- services/tests/test_bundle_analysis.py
The code would have errored previously when trying to call `head_bundle_report.total_size()` (since `head_bundle_report` would have been `None` if removed)
> fix: Handle removed bundles in PR comment

- services/report/languages/lcov.py
- services/report/languages/tests/unit/test_lcov.py
surprisingly, we encountered a report where a line was executed >2**64 times and the lcov tool emitted the hit count with scientific notation. this commit handles that
i mocked up lcov data that uses scientific notation and ran the upload through my local instance of codecov and it worked: https://github.com/matt-codecov/test-lcov-sci-notation
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and …
> fix: handle scientific notation when parsing hit count in lcov reports

- tasks/label_analysis.py
- tasks/static_analysis_suite_check.py
- tasks/tests/unit/test_check_static_analysis.py
- tasks/tests/unit/test_label_analysis.py
- tasks/tests/unit/test_label_analysis_encoded_labels.py
context: codecov/engineering-team#526
Adds some basic per-customer ats metrics.
Actually because the `MetricsContext` usage is disabled this
just sets up the metrics once that's done.
Makes use of `MetricsContext` to annotate metrics per customer
(repo, commit, owner).
> feat: some per-customer ats metrics

- celery_config.py
- tasks/__init__.py
- tasks/update_branches.py
This PR creates a one off task to update the branch heads based on the latest commit we have stored in the db for that branch in every repo. Kwargs include branch_name, which specifies the name of the branches to update, ownerid which filters the branches to update down to a specific owner, and dry run which is by default true.
> feat: add update branches task definition

- services/notification/notifiers/mixins/status.py
This PR creates a log in the `_apply_adjust_base_behavior` function and attempts to fix the following bug.
There's a bug where we compare the base adjusted coverage to the
head coverage. The issue occurs when the base adjusted coverage has more
digits after the decimal point than the head coverage.
The head coverage that we fetch in this function will always have 5
digits after the decimal, but the base adjusted coverage does not have
that same restriction.
The decimal library will not round the number with more digits after
the decimal point when doing a comparison.
Currently, in our code we are basically doing the following:
`Decimal('90.001').quantize('0.00') <= Decimal('90.001')`
which will evaluate to false.
If we are rounding the head coverage to 5 digits after the decimal point
we …
> Attempt to fix adjust base behavior rounding bug

- services/lock_manager.py
- services/test_results.py
- tasks/notify.py
- tasks/test_results_finisher.py
- tasks/tests/unit/test_notify_task.py
- tasks/tests/unit/test_test_results_finisher.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
Depends on: #197 
This PR adds functionality for the test results PR comment feature, and contains the necessary improvements to the test result processor task to achieve this.
The first change to the processor is that it's no longer writing to the db anymore. This is because the processor tasks run concurrently, and concurrent writes to the DB were making it difficult to ensure that there multiple Test objects weren't being created at the same time. The writes to the DB to persist `Test` and `TestInstance` objects were moved to the finisher. 
The second change to the processor is that it now returns a processed list of "Testrun dicts", which contains some metadata (`env` and `run_number`) and a list of "testruns" which the finisher will use to decide what `Test` and `TestInstance` …
> Add test results finisher

- tasks/upload.py
Previously, checkpoints was being used when it wasn't necessarily defined in the Upload task
> fix(upload): don't use checkpoints logger unless report type is coverage

- services/decoration.py
- services/tests/test_decoration.py
this query is very costly and we want the ability to disable it in some environments until we optimize it
> add config to allow disabling upload throttling

- tasks/update_branches.py
- no more ownerid
- takes in incorrect commitid to help filter branches
- no longer uses yield_per, instead does one query for all the branches then breaks it up into chunks of branches
- commits after updating every chunk
> fix(update_branches): commit more often, no more yield_per, no more ownerid

- services/report/__init__.py
- services/test_results.py
- tasks/upload.py
previously, we were querying the repo flags for each upload, but that was unnecessary as we can just query once and maintain a dict for the flags that we insert
> fix: remove n+1 repo flags query

- services/test_results.py
- tasks/tests/unit/test_test_results_finisher.py
This changes the PR comment to organize rows such that tests with the same failure message will be displayed in the same row. Also, if a test has multiple flags with the same failure message, it will display them in the same line.
> Improve test result PR comment

- services/bots.py
- services/github.py
- services/owner.py
- services/tests/test_bots.py
- tasks/sync_repos.py
- tasks/sync_teams.py
This is a problem with the 'sync repos' button in the UI. It only affects getting the token for a OWNER (if it's for a repo it's correct). Sadly this affects `sync_teams` and `sync_repos` tasks.
If the owner decides to sync we should use the owner's token, even if there is an installation app for that owner. The extra logic helps us do that.
> fix: ignore insallation for owner some times

- tasks/notify.py
closes https://github.com/codecov/engineering-team/issues/887
> fix: remove team plan gate from patch coverage base fix

- services/report/raw_upload_processor.py
Adds commit_id information from uploaded reports to logs when it is available. Closes #211 
> chore: add commit id to logs

- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/tests/integration/test_comment.py
- services/notification/notifiers/tests/unit/test_checks.py
- services/notification/notifiers/tests/unit/test_comment.py
- tasks/tests/integration/test_notify_task.py
This PR addresses https://github.com/codecov/engineering-team/issues/1072 and https://github.com/codecov/engineering-team/issues/986
- Change copy of patch coverage comment to include patch coverage percentage
- Remove base project coverage percentage from all covered PR comment
> Fix PR comment

- database/models/core.py
Bring the GithubAppInstallation model to parity with api's
Depends on codecov/codecov-api#407
> update ghapp model

- requirements.txt
- tasks/sync_repos.py
- tasks/tests/unit/test_sync_repos_task.py
Adds a new flow for sync_repos task in which the caller
already knows what repos we should check. This happens
in INSTALLATION webhooks by GitHub, that include a list of affected repos.
The new flow makes use of github graphQL api via torngit to get info
directly on the repos affected.
> revamp sync_repos task

- services/bundle_analysis.py
- services/tests/test_bundle_analysis.py
This PR makes a small tweak to how kilobytes are displayed in the PR comment from `KB` to `kB` following the international standard of displaying kilobytes (why it's different than all of the others ... is beyond me)
> fix: Change how kilobytes are displayed to international standard

- services/notification/notifiers/mixins/status.py
- services/notification/notifiers/tests/unit/test_checks.py
- services/notification/notifiers/tests/unit/test_status.py
- tasks/tests/integration/test_notify_task.py
context: codecov/engineering-team#1131
Changes 'unexpected changes' to 'indirect changes' in statuses
sent by the notify task.
> chore: Change wording in statuses messages

- services/notification/notifiers/mixins/status.py
- services/notification/notifiers/tests/unit/test_checks.py
These changes set the default Removed Code Behavior (RCB) to
`adjust_base` (instead of `fully_covered_patch`).
The change in the test is because the status actually passes
via adjust_base. I decided to preserve the outcome of the test,
and changed the rcb configured for the test.
context: codecov/engineering-team#1130 …
> chore: Change default RCB to adjust_base

- helpers/string.py
- helpers/tests/unit/test_string.py
- services/test_results.py
- tasks/tests/unit/test_test_results_finisher.py
This PR adds escaping for certain characters when making the test result PR comment.
We have to do this to properly display the failure message table.
> Fix test result PR comment

- django_scaffold/management/commands/migrate.py
- django_scaffold/settings.py
whoops. autocommit is turned off in worker and this also applies to the migrate command apparently :)
also re-enable the database routers and add a setting i missed that actually causes risky migrations to be skipped
> fix: commit after running worker migrations

- helpers/telemetry.py
https://github.com/codecov/worker/pull/289 should fix the problems i saw when i deployed these metrics to staging
enabled in https://github.com/codecov/worker/pull/283, reverted in https://github.com/codecov/worker/pull/286, back on now
sorry for the churn on this. in the future i'll deploy to staging manually to test for things like this before merging
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, …
> fix: re-enable sql task metrics

- services/report/__init__.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/upload_processor.py
context: codecov/engineering-team#1112
Attempts to rewrite a report in readable format if the processing failed.
This is meant to aid in debugging errors - that likely come from the report
content - in case of processing failure.
Particularly the reports uploaded by the CLI are done so encoded and
compressed. If we rewrite in readable format users can download them in
the commits page of the UI and actually see what's inside.
Important details:
* This only applies if the processing failed with an exception.
* If we were to try processing the re-writen report the processing would
fail. (but we won't do that because processing failed with exception)
* If the error was an internal one the report won't be changed either.
Particularly for `SoftLimitTimeout` error it would be dangerous to
try …
> fix: Rewrite report in readable format in error

- helpers/telemetry.py
there is a noisy log telling us we shouldn't use naive timestamps when `USE_TZ` is set
> fix: use timezone-aware timestamp in MetricsContext

- rollouts/__init__.py
- services/report/raw_upload_processor.py
- tasks/sync_repos.py
- tasks/tests/unit/test_sync_repos_task.py
Temporarily remove feature flags since it is querying django models which will be blocking the event loop in asyncio.  
> fix: remove feature flags

- database/models/reports.py
- services/test_results.py
- tasks/notify.py
- tasks/test_results_finisher.py
The point of this change is to avoid doing the expensive query to fetch the latest test instances for a commit each time we want to do a notify.
We will be generating the test result report totals in the test results finisher task and setting the number of passed skipped and failed tests.
Depends on: https://github.com/codecov/codecov-api/pull/387
> Use test result totals in worker

- conftest.py
- main.py
- rollouts/__init__.py
https://docs.djangoproject.com/en/5.0/topics/async/#envvar-DJANGO_ALLOW_ASYNC_UNSAFE
django gets mad at us for using its ORM in an async event loop, but we can disable its warning
i believe the `async`/`await` in `worker` is mostly spurious and doesn't result in any concurrency. i remove most of it in https://github.com/codecov/worker/pull/304, and this would appease django, but that change is enormous
assuming i am right that most of the async in worker is not really doing anything, then it should be safe to disable the safety check until we can follow through on the mega-PR
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some …
> allow django in async code, re-enable disabled feature + set env in tests

- app.py
- main.py
- tasks/tests/unit/test_upload_task.py
If the DJANGO_SETTINGS_MODULE and django app are setup after the celery app the celery app won't use the [django fixup](https://github.com/celery/celery/blob/main/celery/fixups/django.py) which [has some DB related code](https://github.com/celery/celery/blob/main/celery/fixups/django.py#L179-L210) (which may fix this "Django transaction failed to commit." that we're running into.)
> fix: move django setup to before celery setup

- requirements.in
- requirements.txt
- rollouts/__init__.py
- services/report/raw_upload_processor.py
- tasks/sync_repos.py
Update Feature interface to match the `check_value()` signature here https://github.com/codecov/shared/pull/141. Need to update the shared hash once the ^ PR gets merged
Also removes salt/proportion param from `Feature` according to this https://github.com/codecov/shared/pull/142
> fix: update Feature interface

- rollouts/__init__.py
- tasks/test_results_processor.py
- tasks/tests/unit/test_test_results_processor_task.py
These changes have 2 obejctives:
1. (duh) try to speed up time of writing tests and test instances in the DB.
This is inspired by https://docs.sqlalchemy.org/en/13/faq/performance.html#i-m-inserting-400-000-rows-with-the-orm-and-it-s-really-slow
The idea is to bulk_update and let the DB handle the concurrency and the conflicts.
2. Test using Sentry metrics + Features for perf potential improvements.
Although I suspect the time benefit will be enough for us to prefer the bulk_insert technique I don't know what the benefit is (potentially). And there's the drawback of using extra memory, which I'm also not sure how much extra memory it is.
So I want to use this opportunity to explore this setup of running perf experiments :D
Look, I get it. The entity doing business as "Sentry" was …
> perf: experiment with bulk instert test results

- tasks/sync_repos.py
- tasks/tests/unit/test_sync_repos_task.py
> shared function is async generator. We need to treat it as that

- services/comparison/__init__.py
- services/notification/__init__.py
- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/tests/integration/test_comment.py
- services/notification/notifiers/tests/unit/test_comment.py
- tasks/notify.py
To help users confirm that test_results is setup correctly we want to display
a message near the header saying that that is the case and all tests passed.
These changes accomplish that by creating a new `NotificationContext` in the
`ComparisonProxy` and carrying the info to the notifier.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of …
> feat: add message when test_result is setup

- services/test_results.py
- tasks/test_results_finisher.py
- tasks/tests/unit/test_test_results_finisher.py
When you group metrics of the test_result.finisher grouped by "reason" and "status"
the options currently are:
| reason      | status         |
|-------------|----------------|
| no_success  | failure        |
| notified    | False          |
| no_failures | success        |
| None        | failures_exist |
| notified    | True           |
These options are not very consistent and it's also not immediately clear
what is happening in all of the cases.
These changes alter the tags associated with the metrics to make them more
consistent.
Changes are:
( no_success, failure ) --> ( no_successful_processing, failure )
( no_failures, success ) --> ( all_tests_passed, normal_notify_called )
( None, failures_exist ) --> ( tests_failed, success )
For the `notified` reason, those actually capture …
> chore: make test_result metrics more consistent

- tasks/timeseries_backfill.py
`TimeseriesBackfillDatasetTask` was not setting `name` correctly causing this task to not be reference-able by other callers. This led to "Enable Analytics" button in the app to not work.
> fix: timeseries task name definition

- tasks/test_results_finisher.py
- tasks/tests/unit/test_test_results_finisher.py
Previously, string escaping was not escaping
HTML properly and it was escaping more chars
than it needed to
Depends on: https://github.com/codecov/worker/pull/308
Fixes: https://github.com/codecov/engineering-team/issues/1232
> Fix string escaping 

- services/report/__init__.py
- services/report/raw_upload_processor.py
- services/report/report_processor.py
- services/report/tests/unit/test_process.py
context: https://l.codecov.dev/xvGZaM
Because we eagerly merge sessions when processing a report the following scenario can happen:
1. You upload an empty report with a flag set to carryforward
2. There will be a new session for that upload (even though it's empty)
3. In the next commit the session will be carried forward
If no real upload was made to clean up old carriedforward sessions from empty uploads
they would accumulate in the report (because `_adjust_sessions` only runs *after* the
processing is done, and *doesn't run* if it's an empty upload). What prompted this
investigation is that a customer was fund with thousands of carryforward session in
some of their commits.
So I'm exploiting the fact that merges into the report need to be made from within a lock
and getting the ID for …
> fix: don't eager merge sessions into report

- services/notification/__init__.py
- services/notification/notifiers/base.py
- services/notification/notifiers/checks/base.py
- services/notification/notifiers/comment/__init__.py
- services/notification/notifiers/generics.py
- services/notification/notifiers/status/base.py
- services/notification/tests/unit/test_notification_service.py
- tasks/notify.py
After configuring multi-apps in staging we noticed the notificaitons were not coming
from the configured app. That is because each notifier uses its own `repo_service` instance.
These changes propagate the `gh_installation_name` selected by the Notify task
(the selection part is working properly) to the `NotificationService`.
The `NotificationService` in turn propagates the choice to the notifiers so that
when they get their own `repo_service` instances it will be from the correct installation.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I …
> fix: propagate gh_installation name selection

- tasks/notify.py
`'function' object is not iterable` issue in sentry has been showing up for a few hours
> fix: pass iterable into any() instead of lambda

- worker.sh
If you look at https://github.com/codecov/worker/blob/14ffa91c4a8b7b2b509adb5e8744ea1534f1d97c/helpers/environment.py#L47 it says `ENTERPRISE`.
But the `worker.sh` script says `enterprise`.
So the worker is not running the timeseries migrations for enterprise envs.
(we had this issue with a customer)
> fix: envs are UPPERCASE

- services/bots.py
- services/tests/test_bots.py
These changes introduce a change in weight for installations recently updated.
Any change in a ghapp `updated_at` field will cause it to enter a "ramp up" phase
during which other suitable installations will be prefered for usage.
The idea is that changes to an installation can introduce config errors and cause
the ghapp to be unusable in it's current state. To avoid breaking the app we use
the ramp up process.
The rampup is based on `random.choices` and giving weights to installs based on how
long ago they were last updated. The rap up function is exponential and the whole
process stabilizes after 10 days (at which point all installations have the same
probability of being selected)
closes: codecov/engineering-team#1483
Look, I get it. The entity doing business as "Sentry" was …
> feat: ramp up process for ghapp installations

- tasks/label_analysis.py
- tasks/tests/unit/test_label_analysis.py
- tasks/tests/unit/test_label_analysis_encoded_labels.py
Fix issue https://codecov.sentry.io/issues/5066637793
We're having RuntimeError from trying to emit metrics that think they are
in an async event loop from sync code.
These changes remove the asnyc call but keep the metrics emiting.
The metrics are now a blocking call, but impact should be minimal at this time.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, …
> fix: metrics are no longer run in async

- services/bundle_analysis.py
- tasks/tests/unit/test_bundle_analysis_processor_task.py
Keep track of when failed to parse a bundle stats file during upload processing and what plugin was being ran at the time.
> Bundle Analysis: Add Sentry metrics for uploading

- database/enums.py
- database/models/reports.py
- services/flake_detection.py
- services/tests/test_flake_detector.py
Refactors flake detection to use FlakeDetectionEngine and symptom detectors
> Add Flake models and refactor flake detection

- rollouts/__init__.py
- tasks/test_results_processor.py
- tasks/tests/unit/test_test_results_processor_task.py
Ends the bulk insert experiment. Uses only the bulk insert method to write tests,
for the reduced time.
This comes at the cost of using extra memory (aux structures), but the time gains
are worth it. Especially because right now the time to write to DB dominates the
total time of this task.
Check graphs for comparison.
In the first graph we have time comparison of both methods. Notice that even the p90 of bulk_insert is generally lower than p50 of simple_insert.
Memory usage is 3x in average, which is not great, but the max so far was 50Kb, which is not going to be a problem anytime soon. I also believe we can explore ways to reduce memory usage further by changing the aux structures from lists to a dict for the `Test`, for example (reduce repeated tests).
> chore: end the bulk insert experiment

- tasks/test_results_finisher.py
- tasks/tests/unit/test_test_results_finisher.py
there is the possibility of an issue when the
notify task is queued up before the test result finisher releases the notification lock due to the fact that a notify will drop itself if it fails to lock, so we should make sure that the test result finisher is not holding the notification lock before it queues up the notify task
[Sentry Issue](https://codecov.sentry.io/issues/4947303451/?project=-1&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h&stream_index=2)
Fixes: https://github.com/codecov/internal-issues/issues/364
> fix: apply notify task after lock is released

- requirements.in
- requirements.txt
- services/report/__init__.py
- tasks/upload.py
- tasks/upload_finisher.py
- tasks/upload_processor.py
Context: https://github.com/codecov/shared/pull/175
Add repoid keywords for parallel upload processing rollout. The other rollouts already use the keyword which is good.
> fix: add repo_id kwarg for parallel upload processing

- django_scaffold/settings.py
- helpers/telemetry.py
currently its not possible to run worker without "timeseries" database handler. This PR makes it possible to run codecov without that.
fixes https://github.com/codecov/feedback/issues/318
> fix: make it usable without timeseries

- helpers/telemetry.py
- rollouts/__init__.py
- services/report/__init__.py
- services/tests/test_report.py
when looking for an ancestor commit to take our carryforward flag data from, we only search back 10 commits. if we go 10 commits without reports, or if the last 10 commits are still processing, CFF fails and the flags that were being CF'd will be dropped until they receive a new upload
this PR sets up an experiment to plug in different limits and see if any of them have an effect on carryforward success. it creates two metrics that we can watch:
- a "base not found" metric which should be lower in the test group
- a "carryforward success" metric which should be higher in the test group
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to …
> add metric + experiment to see if longer CFF search range lowers errors

- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
Make the session id allocation for parallel flow exactly the same as how the serial flow allocates sessions. My previous version using redis makes the allocated sessions strictly increasing, while the old behaviour will reuse some values. 
This change alone probably isn't enough to fix the differences between what the serial flow and parallel flow generate, but makes my life easier investigating as there is less noise in the diffs. 
This is mainly just a temporary change for now for the experiment
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: …
> fix: use serial session id allocation for parallel experiment

- tasks/notify.py
- tasks/tests/unit/test_notify_task.py
Fixes: https://codecov.sentry.io/issues/5057432400/?project=-1&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=1&utc=true
We should be excepting a `LockRetry` here because that is what `LockManager` throws when it hits an error when trying to acquire the lock
> fix: except LockRetry instead of LockError

- helpers/parallel_upload_processing.py
- services/report/__init__.py
- tasks/parallel_verification.py
- tasks/upload.py
- tasks/upload_finisher.py
- tasks/upload_processor.py
Adds more logging for the parallel upload processing experiment. Also refactors the code in `tasks/upload.py` for readability. 
Sentry/Codecov employees and contractors can delete or ignore the following.
-->
> add logs + move experiment code to helpers

- services/report/report_processor.py
i want a dashboard showing which processors are actually used and how long they take. could probably hack it together with statsd counters but we have to get rid of those eventually
> convert statsd report processor metrics to prometheus metrics

- requirements.in
- requirements.txt
- tasks/sync_repos.py
- tasks/tests/unit/cassetes/test_sync_repos_task/TestSyncReposTaskUnit/test_only_public_repos_not_in_db.yaml
- tasks/tests/unit/cassetes/test_sync_repos_task/TestSyncReposTaskUnit/test_sync_repos_using_integration_no_repos.yaml
- tasks/tests/unit/test_sync_repos_task.py
Simply bumps shared hash to include this PR: https://github.com/codecov/shared/pull/180
What's included aside from hash update:
- Removed all the graphQL request stuff no longer needed in the tests + cassette yaml
- Bug Fix for if no repos are returned we should be setting integration to false for repos belonging to user …
> dev: bump shared hash to latest

- Makefile
- docker/Dockerfile.requirements
- worker.sh
fixes https://github.com/codecov/engineering-team/issues/1242
with an alpine/musl image we have to build more packages from source. grpcio takes an eternity to build for example
also apparently alpine/musl images have DNS resolution problems
this uses an official "slim" python image based on debian stable. from a quick glance at uncompressed image sizes on my local machine, this is actually 300mb smaller:
i have not rigorously tested this but it seems okay
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest …
> chore: use debian base images instead of alpine

- conftest.py
- helpers/telemetry.py
- helpers/tests/unit/test_telemetry.py
- pytest.ini
- services/report/__init__.py
- services/tests/test_report.py
`worker_service_report_carryforward_success` and `worker_service_report_carryforward_base_not_found` were broken because of a `synctoasync` thing. this fixes them
to satisfy tests, it also adds new test fixtures that will:
- mock `MetricContext.populate()` to skip db accesses and things a test may not be set up for
- mock `Feature.check_value()` to make it return defaults
these fixtures are on by default, but you can disable them by adding `@pytest.mark.real_feature` or `@pytest.mark.real_metric_context` to the test.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. …
> fix carryforward metric, mock feature/metrics in most tests

- rollouts/__init__.py
- services/test_results.py
- services/tests/test_flake_detector.py
- services/tests/test_test_results.py
- tasks/test_results_finisher.py
- tasks/tests/unit/test_test_results_finisher.py
Depends on:
https://github.com/codecov/shared/pull/184
This PR does not make any changes to the database: existing flakes won't be retrieved, new flakes won't be stored, flakes will be recalculated every time we run the test results finisher.
- Adds the flaky_status column to the Test object in the db
- Adds existing flaky tests to the PR comment (behind a feature flag)
- Runs flaky test detection at the end of the test results finisher (behind a feature flag)
- Updates comment and persists new results from flaky test detection to db
> Integrate flaky test detection into test results finisher

- tasks/upload.py
Adds the type of processing task is being scheduled to logs. It's annoying to look at the logs and not know which type of task is being scheduled.
> chore: differentiate processing tasks in logs

- requirements.in
- requirements.txt
- services/bots.py
- services/github.py
- services/owner.py
- services/repository.py
- services/tests/integration/test_bots.py
- services/tests/test_bots.py
- services/tests/test_owner_service.py
- services/tests/test_repository_service.py
depends on: https://github.com/codecov/shared/pull/186
Passes fallback tokens to GitHub instances if more than 1 app is available (in the case of dedicated apps in particular the default one is the fallback).
Also checks if apps are rate limited before selecting them.
There's a new exception now `NoConfiguredAppsAvailable` due to being rate limited.
I purposefully didn't catch this exception yet.
The idea in a subsequent PR is to do so in the notify task, for example,
so we can reschedule it.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I …
> feat: pass fallbakc tokens to Github if available

- Makefile
- requirements.txt
This fixes [https://github.com/advisories/GHSA-2m57-hf25-phgg](https://github.com/advisories/GHSA-2m57-hf25-phgg).
`requirements.txt` was auto-generated by running:
`pip-compile --upgrade-package sqlparse`
The only dependency, `django`, doesn't have `sqlparse` pinned, so we should be able to upgrade this.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under …
>   Update `sqlparse` to 0.5.0

- services/repository.py
- tasks/sync_repos.py
- tasks/tests/unit/test_sync_repos_task.py
These changes:
* fix a bug in the sync_repos with integration when the list of repos affected is known.
* makes the previous behavior (of listing all repos) active again even in case we have the list of affected repos. This is so that the app can fix itself if we have difference between the repos we think the installation covers and the repos we can acutally list using it.
> hotfix: sync_repos using integration when the repo services is known is acting strange

- tasks/parallel_verification.py
- tasks/upload_finisher.py
For the parallel upload processing verification experiment, I am changing how the outputs of the parallel vs serial flow are compared. 
Instead of comparing exactly the report json and chunks.txt of our reports, I compare the top level totals of coverage, and the file level totals for each file instead. This way, even if the way we assign session ids to uploads in the parallel flow differs from the serial flow (which would've caused a diff in the old comparison method), the coverage totals should hopefully still be the same indicating that the processing was successful.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights …
> feat: make comparison session agnostic by only comparing the totals

- tasks/base.py
there are errors in sentry because we try to access `exception.orig` when the property does not exist
> fix: avoid crashing when analyzing sqlalchemy errors

- tasks/sync_repos.py
Sync_repos when the repos affected are knows is acting up.
Unsure if it's the filtering logic OR a race condition OR if something else
is inserting the repo.
We will be moving to `upsert_repo` to avoid this issue.
> hotfix: avoid double inserts when sync_repos

- helpers/parallel_upload_processing.py
- services/report/__init__.py
- services/report/parser/__init__.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/upload_processor.py
Explicitly make a copy of the raw reports so that the parallel pipeline can parse those raw reports instead of the ones that get rewritten by the serial flow (which are rewritten as the "legacy" format)
> fix: copy raw reports for parallel experiment

- services/report/__init__.py
- tasks/parallel_verification.py
adds more logs so I can debug why verification failed [here](https://console.cloud.google.com/logs/query;query=--%20jsonPayload.message%3D~%22upload%20processing%20verification%22%0A--%20SEARCH%2528%22e57388b2215634015d8cab247af82539d537bc93%22%2529%0A--%20SEARCH%2528%22%60f6da0a27-7857-4ec0-814a-303bd84f7956%60%22%2529%0A--%20jsonPayload.task_id%3D%22a65dcacf-d044-40f0-83fd-762e05bcd72f%22%0ASEARCH%2528%22c234888b170f7fd2db0bb8fba6a93ba45b2a1d30%22%2529;summaryFields=:false:32:beginning;lfeCustomFields=labels%252F%2522k8s-pod%252Frollouts-pod-template-hash%2522,labels%252F%2522k8s-pod%252Fversion%2522;cursorTimestamp=2024-04-26T14:17:49.696863123Z;duration=PT1H?project=genuine-polymer-165712&rapt=AEjHL4MlnhLMl5L8I7Z65VM2i8ALk_F2WmI63QqvOVZttROSTbmOjDXfGg68YKZ1rbWh40UzHftqVStzdKOUWsj1vIX0q …
> chore: add more logs

- services/flake_detection.py
- services/tests/test_flake_detector.py
- tasks/test_results_finisher.py
- If failure message is None ignore the test instance in the UnrelatedMatchesDetector, the information is just not there so we can't use this test instance
- Normalize failure messages in the ingest in UnrelatedMatchesDetector, we should have been doing this already
> fix: Flake detection failure messages

- database/enums.py
- database/models/reports.py
- services/comparison/__init__.py
- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/mixins/message/writers.py
- services/notification/notifiers/tests/integration/cassetes/test_comment/TestCommentNotifierIntegration/test_notify_test_results_error.yaml
- services/notification/notifiers/tests/integration/test_comment.py
- services/notification/notifiers/tests/unit/test_comment.py
- services/test_results.py
- tasks/notify.py
- tasks/test_results_finisher.py
- tasks/tests/unit/test_notify_task.py
- tasks/tests/unit/test_test_results_finisher.py
Fixes: https://github.com/codecov/test-results-action/issues/15
> feat(test results): error message PR comment if no successful parse

- helpers/telemetry.py
Fixes: https://github.com/codecov/internal-issues/issues/441
> feat: if timescale is down don't crash

- services/bots.py
- services/tests/test_bots.py
Because `random.choices` makes selections with replacement and we were making 3 selections only
there was a chance that an app would vanish from the choices (from not being selected).
This is bad because it hides this app as a possible fallbakc option.
Particularly if the choice is marked currently as "rate limited" we would fail with exception
instead of falling back in the other app. We want the fallback.
These changes go around this "choice with selection" by removing the selected app from the
population after each step. It's maybe slower (in practice the population will be small enough
that this doesn't really matter), but makes sure that we always select all available apps.
And still respectes the weighted selection.
Look, I get it. The entity doing business as "Sentry" was …
> fix: always select fallback if available

- helpers/checkpoint_logger/flows.py
- services/lock_manager.py
- tasks/tests/unit/test_save_commit_measurements.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
It was a suspition that we might be overcounting beginnings in the UploadFlow.
I believe one of the exit paths was not being covered in the `Upload` task.
These changes add a new ending to the UploadFlow. Namely, for the scenario where
an UploadTask finishes without enqueuing other tasks because there are no reports
waiting to be processed.
Also updating the `getutcnow` function that is deprecated and fixing some typos.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by …
> chore: extend UploadFlow with new ending

- services/notification/notifiers/comment/__init__.py
- services/notification/notifiers/tests/unit/test_comment.py
requested in https://github.com/codecov/engineering-team/issues/1683
copy/paste of text added:
:information_source: You can also turn on [project coverage checks](https://docs.codecov.com/docs/common-recipe-list#set-project-coverage-checks-on-a-pull-request) and [project coverage reporting on Pull Request comment](https://docs.codecov.com/docs/common-recipe-list#show-project-coverage-changes-on-the-pull-request-comment)
> add should_see_project_coverage_cta to _create_welcome_message

- celery_config.py
- database/models/reports.py
- tasks/backfill_test_instances.py
- tasks/test_results_processor.py
We want to move the commitid and branch information for a test instance to directly on the object, so that when we query we don't have to join with the commits table.
> Update test instances to use local commitid and branch fields

- services/notification/notifiers/comment/__init__.py
- services/notification/notifiers/tests/unit/test_comment.py
follows up https://github.com/codecov/worker/pull/430
missed one detail from this request https://github.com/codecov/engineering-team/issues/1683
> small correction to welcome message logic

- helpers/github_installation.py
- services/bundle_analysis.py
- services/comparison/__init__.py
- services/comparison/overlays/__init__.py
- services/comparison/overlays/critical_path.py
- services/notification/notifiers/tests/integration/test_comment.py
- services/notification/notifiers/tests/unit/test_comment.py
- services/report/__init__.py
- tasks/bundle_analysis_notify.py
- tasks/commit_update.py
- tasks/compute_comparison.py
- tasks/notify.py
- tasks/preprocess_upload.py
- tasks/save_report_results.py
- tasks/sync_pull.py
- tasks/sync_repo_languages.py
- tasks/tests/unit/test_preprocess_upload.py
- tasks/upload.py
- tasks/upload_processor.py
This adds ability for more tasks to use the existing configuration options and
provide overrides for the GitHubAppInstallation name to be used for a given user.
Some of these usages have to be propagated through the task, as is the case with
ComputeComparison, for example.
> feat: add task gh_app_name override for more tasks

- django_scaffold/settings.py
- helpers/telemetry.py
- helpers/tests/unit/test_telemetry.py
clean up unnecessary extra db queries in MetricContext
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/codecov/worker/pull/443).
* __->__ #443
* #442
> clean up unnecessary extra db queries in MetricContext

- .github/workflows/ci.yml
- .github/workflows/self-hosted-release-pr.yml
- .github/workflows/self-hosted-release.yml
Similar to https://github.com/codecov/codecov-api/pull/556, from https://github.com/codecov/gha-workflows/pull/23, updating deprecated GHAs
> dev: update to latest version of gha-workflows

- tasks/backfill_existing_gh_app_installations.py
- tasks/backfill_owners_without_gh_app_installations.py
> make yield amount a param

- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/tests/unit/test_comment.py
tickets: codecov/engineering-team#1625, codecov/engineering-team#1606
Updates the "missing report" message to be more actionable.
Check the ticket for further information, please.
> chore: update missing base message

- migrate-timeseries.sh
The reference to the `ts_telemetry` has been removed in the django apps in #443. We just need to remove referencing it in the migration script. 
> Remove reference to `ts_telemetry`

- database/tests/unit/test_model_utils.py
- database/utils.py
We're seeing timeseries errors pop in sentry that look like this: https://codecov.sentry.io/issues/4354360482/?project=5215654&project=4506250072489984&project=4505534345838592&project=4506739665207296&project=4505562661847040&project=4505562669645824&project=4505562667089920&project=4505743290269696&project=4503926675144704&project=1260170&project=4504171287871488&project=4505225779675136&project=4506634728833024&project=4506317072891904&project=4505131799150592&project=4165036&project=5514400&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+save_commit_measurements&referrer=issue-stream&statsPeriod=30d&stream_index=1&utc=true. I looked up in our logs that this error is shortly followed by "Archive enabled field found in storage after delay"., so we're erroring and quickly …
> 1164 adjust archive get fn error call

- .github/workflows/mypy.yml
- .pre-commit-config.yaml
- mypy.ini
add mypy checking in pre commit and CI
> build: add mypy (optional)

- database/models/reports.py
- helpers/number.py
- helpers/tests/unit/test_number.py
- services/report/__init__.py
- services/yaml/reader.py
This ensures that we use the user specified rounding strategy before saving to the database. 
This change does _not_ update the database to increase precision; that is too much effort, and this is mean to fix the common default case (of rounding down to 2 decimal places).
There might be a future PR to actually migrate the database for more precision, in which case this code will still be useful for setting that more precise number into the database.
Quick fix for the common default case in https://github.com/codecov/engineering-team/issues/1614
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize …
> Round the coverage numbers before saving to database

- helpers/telemetry.py
https://github.com/codecov/internal-issues/issues/461
> make telemetry helper resilient to exceptions

- requirements.in
- requirements.txt
- services/stripe.py
Upgrades stripe to latest API version
Related Ticket: https://github.com/codecov/engineering-team/issues/1754
Main changes found here: https://github.com/codecov/codecov-api/pull/569
> dev: Upgrade stripe to latest

- conftest.py
- helpers/tests/unit/test_environment.py
These tests are consistently failing on my local but they passing when they run in CI.
This fix allows them to pass on my local
> get all tests passing on local

- services/notification/notifiers/mixins/message/__init__.py
- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/tests/integration/cassetes/test_comment/TestCommentNotifierIntegration/test_notify_new_layout.yaml
- services/notification/notifiers/tests/integration/cassetes/test_comment/TestCommentNotifierIntegration/test_notify_with_components.yaml
- services/notification/notifiers/tests/integration/test_comment.py
- services/notification/notifiers/tests/unit/test_checks.py
- services/notification/notifiers/tests/unit/test_comment.py
- tasks/tests/integration/test_notify_task.py
https://github.com/codecov/engineering-team/issues/1573
the link was to the pull, should be to the commit
> update HeaderSectionWriter to link to head_report

- database/models/reports.py
- requirements.in
- requirements.txt
After the migration to increase the number of decimal places for these tables, we should be able to use them to 5 decimal places. We just need to also update the models used in worker for consistency.
Migration happens in `shared`: https://github.com/codecov/shared/pull/224
ref: https://github.com/codecov/engineering-team/issues/1614
Diff for the `shared` update: https://github.com/codecov/shared/compare/codecov:f6c2c3852530192ab0c6b9fd0c0a800c2cbdb16f%5E%5E%5E%5E%5E...codecov:ae6e12f3cf43188a6d6fa0156ccb78252d3405a8
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. …
> Increase the number of decimal places for the AbstractLevelTotals

- tasks/bundle_analysis_processor.py
Trying this because I suspect we might be leaving a dangling connection to the SQLite db in this part of the code if for some reason we don't reach the call to bundle_report.cleanup, so I'm moving it to a finally so that code will always execute even if there's an error somewhere before it.
Fixes: https://github.com/codecov/internal-issues/issues/439
> fix: cleanup bundle report in finally

- services/notification/__init__.py
- services/notification/notifiers/__init__.py
- services/notification/tests/unit/test_notification_service.py
Customers with team plan only get patch status/checks, regardless of their yaml settings. This PR is to add this logic as it was never done when first creating the team plan. Ticket here https://github.com/codecov/engineering-team/issues/1660.
I introduced 2 new variables that indicate whether we need a status and a check. We are reusing `_should_use_checks_notifier` to check for status I just added a small piece to make it work with this logic. We are adding `_should_use_status_notifier` which returns true unless it's a team plan without a `patch` status/check - we've always returned status otherwise. Let me know if there's any confusion with this approach
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. …
> Logic to remove checks from team plan customer

- services/bots/github_apps.py
- services/bots/tests/test_bots.py
it aims to revert the important bits on https://github.com/codecov/worker/pull/445/commits/f58a5a07f14749e947ef02d66338f19c4043da28
That commit was released and we saw an immediate increase in errors of `RepoWithoutValidBot`.
We suspect that it was not correct to remove the deprecated path just yet.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's …
> fix: bring back Owner.integration_id check

- celery_config.py
- tasks/__init__.py
- tasks/backfill_existing_gh_app_installations.py
- tasks/backfill_owners_without_gh_app_installations.py
- tasks/tests/unit/test_backfill_existing_gh_app_installations.py
- tasks/tests/unit/test_backfill_owners_without_gh_app_installations.py
This just reworks the existing GH app backfill task to distribute the backfill to subtasks. Previous implementation seemed to run out of memory, hence making several subtasks.
> Rework backfill task to create sub-tasks

- requirements.in
- requirements.txt
- services/bundle_analysis.py
- services/tests/test_bundle_analysis.py
- tasks/bundle_analysis_notify.py
We're adjusting the BA PR comment to accommodate customers that don’t want a PR message when there are no changes, posting here for visibility. To summarize:
- We’re adding require_bundle_changes, a setting you can add to your codecov yaml
- If there are no changes
- If require_bundle_changes = false we show “Bundle size has no change” - we default to this
- If require_bundle_changes = true, we don’t show the comment at all
- When there are changes, we always display them, regardless of this setting ^
Moved around some logic to make it work but generally this is it
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me …
> 1459 ba pr message tweak

- services/comparison/__init__.py
- services/comparison/tests/unit/test_reports_uploaded_count_diff.py
- services/comparison/types.py
ticket: https://github.com/codecov/engineering-team/issues/1622
These changes introduce a new capabiliy to `ComparisonProxy`. Namely, to get the
difference in the number of uploads reported per flag between HEAD and BASE.
The idea is to be able to give more actionable message in the PR comment on the following scenario:
1. I have uploaded 5 reports to my base commit
2. I upload 1 report to head commit
3. I have NOT covered all lines of my patch
4. I'm seeing project coverage go WAY down
Because typically coverage is uploaded via CI, and CI doesn't change often, a different
number of reports present could indicate issues in the coverage results.
We have to ignore carryforward sessions because different commits might upload different
sets of reports.
Look, I get it. The entity doing …
> feat: count difference of uploaded sessions

- services/github.py
- services/tests/test_github.py
Adds `set_github_app_for_commit` and `get_github_app_for_commit` functions. These let us set and later get a GithubAppInstallation.id that's related to a Commit.id
ticket: https://github.com/codecov/engineering-team/issues/1737
👀 This commit is part 1/4 of a bigger change that is actually done, but I decided to break it up into multiple PRs so it's easier to review. See how it plays with the rest here: https://github.com/codecov/worker/compare/main...gio/pin-commit-to-ghapp
(I'll try to leave the original branch up to date best as I can)
> feat: Add functions to get/set apps to commits

- .github/workflows/cache_cleanup.yml
- .github/workflows/ci.yml
- .github/workflows/mypy.yml
- .github/workflows/self-hosted-release-pr.yml
- .github/workflows/self-hosted-release.yml
Bumps the GHA Action workflows to 1.2.20
> chore(ci): bump gha workflows to 1.2.20

- tasks/base.py
rather than searching for a commit sha in GCP logs to get celery task IDs and then checking if those celery task IDs exist in sentry, let's make it possible to just search the commit sha in sentry
> add commit sha to sentry trace tags

- services/report/__init__.py
i think the new report endpoint that the CLI's `create-report` command hits will create a `CommitReport` without creating a `ReportDetails` ([link](https://github.com/codecov/codecov-api/blob/f1a4eee037253eb39da3291b6a2ccca7702ff518/upload/views/reports.py#L40)) so this log is not actually unexpected and fires way too much
> delete outdated/noisy log

- database/models/timeseries.py
- requirements.in
- requirements.txt
Adds some timeseries measurement types to be used for various bundle analysis trend analytics.
closes: https://github.com/codecov/engineering-team/issues/1765
> Bundle Analysis: Add to timeseries MeasurementName enum

- services/report/raw_upload_processor.py
instead of logging the full set of path fixes, log the "first" 10, and skip logging a full table of contents ("toc")
the `fixes` and `toc` keys in this log can potentially have an item for every file in the repository. GCP collapses big logs into a smaller row that you can click to expand, but apparently a log can be so big that it will actually be split across several rows, and in at least one case the log was so big that it took up screenful after screenful and made investigating the issue i was working on much harder
> denoise an obnoxious log

- requirements.txt
This is to fix to a security vulnerability: https://github.com/advisories/GHSA-h75v-3vvj-5mfj
ref: https://github.com/codecov/internal-issues/issues/476
> Update jinja2 to 3.14

- helpers/backfills.py
- rollouts/__init__.py
- tasks/sync_repos.py
- tasks/tests/unit/test_backfill_existing_gh_app_installations.py
- tasks/tests/unit/test_backfill_owners_without_gh_app_installations.py
- tasks/tests/unit/test_sync_repos_task.py
This PR aims to remove the "control" code related to the list repos generator experiment. 
Related notion doc: https://www.notion.so/sentry/LIST_REPOS_GENERATOR-435d23a072034036b5b29e0ff79aab3e
Code has been running at 100% exp since May 13 2024.
[Metabase link](https://metabase.codecov.dev/question/170-experiment-dashboard-by-owner-id?variant_name=list_repos_generator&metric=worker.task.app.tasks.sync_repos.SyncRepos.core_runtime&start_date=2024-05-24)
**TESTING**
- Ran on Gazebo manually syncing repos, confirmed no error thrown, all repos look to still be shown on the screen
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some …
> chore: Remove List Repos Generator Exp Control Path

- services/github.py
- services/repository.py
- services/tests/test_github.py
- services/tests/test_repository_service.py
Change the repository service so we have a function that
checks whether a commit has been pinned to a specific app
and returns the TorngitAdapter with said app.
Note on `services.repository._is_repo_using_integration`: this function has become effectively obsolete since the introduction of `get_adapter_auth_information` because we can tell if we are using the installation by the presence of "installation_info" or not.
👀 This is PR 3/4 in the pinning commits to apps endeavour
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, …
> feat: get repo service for specific commit

- services/notification/notifiers/mixins/status.py
ticket: https://github.com/codecov/internal-issues/issues/204
Let me preface this by saying that the latest comment in the ticket doesn't seem an accurate complain
cause looking in the logs the adjusted base coverage is 91.30752 and the head covereage is 91.24169.
That being said, it's still possible that for a decent sized code base the change is less than what we
display as a "change" (that is, the change is smaller than 0.01), but it's still a change (might be 0.0001)
Realistically no one would care.
So this change protects us by having a little wiggle room. The check would only fail if the difference is
more than 0.01 (so the numbers in the comment would look different).
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as …
> fix: improve adjusted base comparison

- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/mixins/message/writers.py
- services/notification/notifiers/tests/unit/test_checks.py
- services/notification/notifiers/tests/unit/test_comment.py
Removes the "are" when missing lines of coverage.
Also adds a conditional where if there's only 1 line uncovered we say "line" instead of "lines"
Old: `Attention: Patch coverage is 97.53086% with 2 lines in your changes are missing coverage. Please review.`
New: `Attention: Patch coverage is 97.53086% with 2 lines in your changes missing coverage. Please review.`
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can …
> fix: Grammar for codecov comment when missing coverage

- conftest.py
- services/github.py
- services/notification/__init__.py
- services/notification/commit_notifications.py
- services/notification/notifiers/base.py
- services/notification/notifiers/checks/base.py
- services/notification/notifiers/status/base.py
- services/notification/notifiers/tests/unit/test_status.py
- services/notification/tests/unit/test_commit_notifications.py
- services/notification/tests/unit/test_notification_service.py
- services/tests/test_github.py
- services/tests/test_repository_service.py
- tasks/notify.py
- tasks/tests/integration/test_notify_task.py
- tasks/tests/unit/test_notify_task.py
extends NotificationResult to record the app that was used. After notifications go through we save them to `CommitNotification`, including the app. This is the "permanent pindown"
Previously this would only happen for pull requests, but not it _also_ saves a `CommitNotification` everytime we have a record of an app_id being used (for a successful notification)
The `Notify` task after selecting an app will possibly pindown the commit to that selected app, or refresh the permanent pindown in Redis (faster to access). Notice then, that if a notifier is to use a specific app this will certainly be in redis. Put there by the `NotifyTask`.
I've found some errors in the redis get/set though (through manual testing). It turns out that the return value is a binary string, not a "regular" string. …
> feat: pin down commits to apps

- tasks/sync_repos.py
- tasks/tests/unit/test_sync_repos_task.py
https://github.com/codecov/engineering-team/issues/1757
in most tasks, all db writes occur in a transaction and if an uncaught error occurs we roll the transaction back. for sync_repos, if a user syncs 999/1000 repos and then encounters an error, we actually don't want to roll everything back.
[`sync_repos` already commits after each repo insert](https://github.com/codecov/worker/blob/1beef847cdd951cd084adf4632893c39f4c442e9/tasks/sync_repos.py#L436) so the repo data won't be thrown away. however, what we _don't_ do is update the list of private repos that the syncing user can see. so if they sync 999 new private repos and then get a 502, the 999 repos will be in our database but we won't let the user view any of them. this PR changes that
the old behavior, when catching a worker task …
> sync_repos: allow private repo permissions to be set on error

- .pre-commit-config.yaml
- services/bots/types.py
Fixes the mypy config in the pre-commit hook so it actually runs.
Apparently it doesn't like the "type" keyworkd, so removing that
ps.: fixing in CI depends on https://github.com/codecov/gha-workflows/pull/26
> fix mypy config for pre-commit

- rollouts/__init__.py
- tasks/sync_pull.py
This experiment aims at reducing the time we wait for a lock before giving up
in the snyc_pulls task.
For more info please see https://l.codecov.dev/DeIgE5
> feat: experiment on sync_pulls

- requirements.in
- requirements.txt
- services/bots/helpers.py
- services/bots/public_bots.py
- services/bots/tests/test_bots.py
- services/bots/tests/test_helpers.py
- services/tests/test_bots.py
ticket: https://l.codecov.dev/QLcMzU
1st part of the move to having more dedicated-tokens for certain functionality in the app.
It also now allows dedicated-tokens to come from apps (for GitHub)
> chore: re-work public tokens (part I)

- services/comparison/__init__.py
- services/comparison/tests/unit/test_reports_uploaded_count_diff.py
- services/notification/notifiers/mixins/message/__init__.py
- services/notification/notifiers/mixins/message/helpers.py
- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/mixins/message/tests/test_helpers.py
- services/notification/notifiers/tests/unit/test_comment.py
- tasks/tests/integration/test_notify_task.py
These changes include 2 related things:
* refactor: create MessagesToUserSectionWriter
Moving the "install github app" message to a dedicated section writer.
I'm doing this because I want to use this new section writer to add the
"number of uploads in your commit differs from base" message afterwards
* feat: add warning if number of uploads differ
Introduces a message when the number of uploads differ and there is a significant coverage drop.
The idea is that we can inform users that possibly some upload is missing, and that is the cause of the coverage drop.
I had to re-work part of the logic that counts the upload diff because the sessions in a report is a `dict` object, not a `list`. Thankfully we have many tests :E
> Add message when upload count differs

- tasks/sync_pull.py
This changes the `sync_pull_task_time_to_get_lock_seconds` from "distribution" to "gauge".
Turns out distributions only let you aggregate by average, min and max. I want quantiles.
Also adds a new metric `sync_pull_task_rejected_count` to count how many tasks DONT run
per wait period. After all the goal if this experiment is to see if the reduced wait time
is effective in reducing the number of tasks that run
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this …
> chore: update sync_pull experiment

- helpers/checkpoint_logger/flows.py
- services/notification/notifiers/mixins/message/__init__.py
- services/notification/notifiers/mixins/message/helpers.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
I also had to fix some random linting errors so pre commit would pass
> fix: test results flow success event

- requirements.in
- requirements.txt
previous deploys were rolling back because they didn't have access to a settings variable - added it to shared so worker can access it that way
> bump shared (fix issue with migrations)

- .github/workflows/mypy.yml
This is to pull the latest version of the mypy changes because it keeps giving me an error:
```
Invalid workflow file: .github/workflows/mypy.yml#L16
The workflow is not valid. .github/workflows/mypy.yml (Line: 16, Col: 21): Invalid input, extra_config is not defined...
```
This should fix the issue.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under …
> Use the hash version of gha-workflows

- requirements.in
This is to fix vulnerability: https://github.com/advisories/GHSA-9wx4-h78v-vm56. Currently, we're already using requests>=2.32, so this is just to enforce it when we recompile.
Link to issue: https://github.com/codecov/internal-issues/issues/494
> Enforce requests>=2.32

- services/report/__init__.py
The re-write on readable format is currently not working for expired or empty reports.
This is because we don't returned the raw report (that despite the name does have a little
but of processing to it) in the case that the report is empty or expired.
By passing the raw_parsed_report we should start rewriting them in the readable format.
This didn't fall in the "rewrite in error" cathegory because these scenarios are not
treated as errors.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my …
> fix: rewrite raw uploads empty and expired

- helpers/exceptions.py
- services/report/__init__.py
- services/report/raw_upload_processor.py
- services/report/tests/unit/test_process.py
Fixes: https://github.com/codecov/engineering-team/issues/1755
> fix: add report file name to logs

- requirements.in
- requirements.txt
- services/notification/notifiers/comment/__init__.py
- services/notification/notifiers/comment/conditions.py
- services/notification/notifiers/mixins/message/__init__.py
- services/notification/notifiers/tests/unit/test_comment.py
- services/notification/notifiers/tests/unit/test_comment_conditions.py
- services/yaml/tests/test_yaml.py
- services/yaml/tests/test_yaml_parsing.py
- tasks/tests/integration/test_notify_task.py
As you can see, this is a big change.
It implements the changes from https://github.com/codecov/shared/pull/259 into the worker.
It does make the require changes condition way more complex. I also took the time to audit the unit tests, but I think they are valid now. Perhaps I should add more integration tests just in case...
> [!IMPORTANT]
> This depends on https://github.com/codecov/shared/pull/259, but it would be a bad idea to merge that and take a long time to merge this (being a breaking change and all)
> So I will hold off merging that one until this one is approved.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some …
> feat: implement new require_changes for coverage comment

- services/repository.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
set up the webhook_secret in passing if it is empty - starts the fix for https://github.com/codecov/internal-issues/issues/366
> add needs_webhook_secret_backfill to upload task

- tasks/notify.py
The way it is written, if `wait_for_ci` is not supplied, it evaluates as `False-y`
per [our docs](https://docs.codecov.com/docs/codecovyml-reference#codecovnotifywait_for_ci), `wait_for_ci` default is `True`
This changes the evaluation, so if `wait_for_ci` is not supplied, it evaluates to `True` which follows our intended behavior.
> add True as default for wait_for_ci

- database/models/reports.py
- requirements.in
- requirements.txt
- services/test_results.py
- services/tests/test_test_results.py
- tasks/test_results_finisher.py
- tasks/tests/unit/test_test_results_finisher.py
- tasks/tests/unit/test_test_results_processor_task.py
This commit makes the changes possible before the risky migrations in the supporting shared PR are done.
- update shared version
- update test results parser version
- add time-machine as a dependency
- add Flake and ReducedError sqlalchemy models
- modify TestResultsNotificationPayload to contain a set of flaky test ids instead of a dict[str, TestResultsNotificationFlake]
- change flaky test results comment format
- change flake detection in test results finisher to gather the Flake objects for a given repo and compare their test ids to the test ids of the failures relevant to the test results comment
> feat: pre risky migration flaky test changes

- helpers/sentry.py
- helpers/tests/unit/test_sentry.py
we already have sample rates set for sentry overall + for traces. this PR also sets one for profiling
note: the way the traces/profiles sample rate env vars are named follows how `shared.config` will read configs from env vars, but neither of them is actually part of the installation yaml schema in `shared.validation` …
> enable sentry profiling

- database/models/core.py
This column is part of the model since https://github.com/codecov/shared/pull/237
but was not reflected in the worker yet.
related: https://github.com/codecov/internal-issues/issues/519
> feat: track suspended apps

- database/models/reports.py
- tasks/process_flakes.py
- tasks/sync_pull.py
- tasks/test_results_finisher.py
- tasks/test_results_processor.py
- tasks/tests/unit/test_process_flakes.py
- tasks/tests/unit/test_sync_pull.py
- tasks/tests/unit/test_test_results_finisher.py
These changes should be committed after the risky migrations in the
flake detection shared change are run.
- Add reduced_error foreign key to test instance sqlalchemy models
- add the process flakes task which takes in a repoid and list of commit
ids as input and upserts Flake objects in the DB based on the test
instances on those commits. This task is what implements the
flakiness heuristic.
- call the process flakes task in sync pulls on merged commits
- call the process flakes task in the test results finisher when we
receive test results from the main branch
> feat: flake detection post risky migration changes 

- services/notification/notifiers/comment/conditions.py
- services/notification/notifiers/tests/unit/test_comment_conditions.py
The `coverage_drop` comment condition looks for the project status threshold,
but the config might be a simple bool. This causes the notifier to fail with
and exception.
These changes fix that and add some more testing to cover this case (that should
have been added earlier, I know. My bad)
related to: https://github.com/codecov/engineering-team/issues/1966
closes: https://github.com/codecov/engineering-team/issues/2003
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by …
> fix: coverage_drop condition

- requirements.in
- requirements.txt
- services/bundle_analysis.py
- services/tests/test_bundle_analysis.py
- services/yaml/tests/test_yaml.py
Updates the comment requirements for bundle_analysis.
Respects the `comment.bundle_change_threshold` defined in the YAML
and only notifies if changes are bigger than the threshold.
(threshold is expected to be an int. So technically [this PR](https://github.com/codecov/shared/pull/271) is a dependency of the present changes, because it does the
coercion into an integer, as expected)
Also adds the `"bundle_increase"` as a possible requirements. In this case
on top of the threshold the change also needs to cause the bundle to _increase_
in size for a comment to be sent.
closes: https://github.com/codecov/engineering-team/issues/2021
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity …
> feat: update bundle_analysis comment requirement

- database/models/core.py
- helpers/exceptions.py
- services/bots/github_apps.py
- services/bots/tests/test_github_apps.py
- tasks/notify.py
- tasks/tests/unit/test_notify_task.py
Currently we ignore if an app is suspended or not.
An app is suspended by the user.
If we select a suspended app we will fail to get an access_token for it
and eventually fail with `InstallationError`
These changes filter out suspended apps from being selected.
In case all apps for the user are suspended we skip notifications.
Other tasks would fail with `NoConfiguredAppsAvailable`.
closes https://github.com/codecov/internal-issues/issues/519
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my …
> feat: don't select suspended apps

- tasks/process_flakes.py
- tasks/test_results_finisher.py
- tasks/tests/unit/test_process_flakes.py
- Fix bug where we weren't queuing up the process flakes task when we were supposed to
- Refine test instances query in process flakes
> Fix process flakes

- tasks/__init__.py
- tasks/process_flakes.py
- tasks/tests/unit/test_process_flakes.py
partially fixes: https://github.com/codecov/engineering-team/issues/2032
> fix: take reduced error into account in process flakes

- tasks/sync_pull.py
- tasks/tests/unit/test_sync_pull.py
instead of processing all the commits on a pull that was merged, it's more correct to process only the testinstances that occurred on the head of the pull, since we can only guarantee that the test instances on the head  of the pull are reflective of the state of the code on main.
> fix: only process flakes for head of pull

- services/notification/notifiers/comment/conditions.py
- services/notification/notifiers/tests/unit/test_comment.py
Currently the `require_changes` will deelte an existing comment if the requirements are not met but a commit exists. The commit vanishes without trace, which is not great UX.
To improve UX we are changing this behavior to bypass required changes if a comment already exists for that PR. We will update that comment.
We did verify that this does not trigger a new email being sent to users, so it should be fine.
closes: https://github.com/codecov/engineering-team/issues/2023
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title …
> chore: don't delete comments.

- ruff.toml
- services/flake_detection.py
- services/notification/__init__.py
- services/notification/notifiers/mixins/message/__init__.py
- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/slack.py
- services/notification/notifiers/status/base.py
- services/report/__init__.py
- services/report/languages/jetbrainsxml.py
- tasks/compute_comparison.py
- tasks/tests/unit/test_preprocess_upload.py
- tasks/tests/unit/test_sync_repos_task.py
Part of the [lint enhancement epic,](https://github.com/codecov/engineering-team/issues/1716) this PR aims to add the Perflint PERF rules, with the fixes majorly being around creating list comprehensions or using .keys() or .values() instead of .items() for dictionaries
These can be found here:
- https://docs.astral.sh/ruff/rules/#perflint-perf
Closes https://github.com/codecov/engineering-team/issues/2050
This PR adds the rules listed above and fixes any errors that stemmed from them.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain …
> dev: Add Ruff Perf rules to worker

- rollouts/__init__.py
- tasks/sync_pull.py
read more on the experiment: https://l.codecov.dev/KvKfel (codecov internal)
Ending the pull_sync experiment.
The conclusion is to reduce blocking timeout to 0.5s (10x smaller). This apparently can reduce up to 10% of the tasks run.
The vast majority of tasks wait less than 100ms for the lock, so there's still plenty room for delays.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and …
> chore: end sync_pull experiment

- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
fixes an issue from https://github.com/codecov/worker/pull/521
> repository secret was being saved to repo when the update failed

- tasks/github_app_webhooks_check.py
saw this spewing in my local instance
the correct param name is `installation_id` https://github.com/codecov/worker/blob/562a878f8b61f2ca05b06b078b44d8eca84bf5fb/services/github.py#L19
> fix incorrect param name in github webhook check task

- services/bundle_analysis/comparison.py
- services/bundle_analysis/exceptions.py
- services/bundle_analysis/notify.py
- services/bundle_analysis/report.py
- services/bundle_analysis/tests/test_bundle_analysis.py
- tasks/bundle_analysis_notify.py
- tasks/bundle_analysis_processor.py
- tasks/bundle_analysis_save_measurements.py
- tasks/tests/unit/test_bundle_analysis_notify_task.py
- tasks/tests/unit/test_bundle_analysis_processor_task.py
- tasks/tests/unit/test_bundle_analysis_save_measurements_task.py
- tasks/upload.py
These changes add nothing. It's a simple refactor breaking up
different services related to bundle analysis into different files.
The "bundle_analysis" service is already a grouping of different things
(processing, comparison, notify, etc) and it's getting big as is.
> refactor: break up bundle analysis services

- requirements.in
- requirements.txt
- tasks/__init__.py
- tasks/activate_account_user.py
- tasks/notify.py
- tasks/tests/unit/test_activate_account_user.py
- tasks/tests/unit/test_notify_task.py
This adds a task that links a user to an account. In particular, we want this to be called in the NotifyTask if the organization has `should_attempt_author_auto_activation` enabled.
Why is this a different task? This is mainly to isolate the models to avoid using SQLAlchemy. In the _ideal_ scenario, we would add this association directly in [the `activate_user` method](https://github.com/codecov/worker/blob/a9332e29cdd53636a6293439b751ad42f92f7238/services/activation.py#L88). The second best place would be in the [New User Activation Task](https://github.com/codecov/worker/blob/main/tasks/new_user_activated.py). However, this would mean porting the code to Django, and it is a big lift for now. So, adding this new task to _just_ do the account-user association. In the future, this task …
> Add activate user task

- tasks/activate_account_user.py
- tasks/tests/unit/test_activate_account_user.py
This field is needed to `run_impl` properly. See Sentry error: https://codecov.sentry.io/share/issue/62a996975a424922b6ceb9d0d1b91e47/
> Add db_session to ActivateAccountUserTask

- rollouts/__init__.py
- services/test_results.py
- tasks/sync_pull.py
- tasks/test_results_finisher.py
- tasks/tests/unit/test_sync_pull.py
- tasks/tests/unit/test_test_results_finisher.py
we want to run the write part of the flake detection process without doing the read part of the flake detection process
> feat: add flaky shadow mode

- services/report/__init__.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/upload_processor.py
Apparently I forgot a little detail in the previous "fix"
(that the ProcessingResult is broken apart if it fails)
This time I tested locally 😅
> fix: empty reports not being saved in readable format

- services/report/report_processor.py
It might be nice to have a histogram with the raw size in bytes for various report formats
> Add a metric for the raw report size

- services/notification/notifiers/mixins/message/__init__.py
- services/notification/notifiers/tests/unit/test_checks.py
- services/notification/notifiers/tests/unit/test_comment.py
If a user specifies the files formatting in their comment layout config, we want it to show the newfiles formatting as well.
> feat: make newfiles part of files behaviour

- services/report/languages/cobertura.py
Fixes invalid escape sequence...
Related logs: https://console.cloud.google.com/logs/query;query=severity%3DERROR%0A%22worker%2Fservices%2Freport%2Flanguages%2Fcobertura.py%22;pinnedLogId=2024-04-08T19:18:39.852000850Z%2Fgt0cscxqclw9v94d;summaryFields=jsonPayload%252Fusername:false:32:beginning;cursorTimestamp=2024-07-29T22:46:07.456996759Z;duration=P1D?project=genuine-polymer-165712&authuser=1&rapt=AEjHL4M3xuoV-WET7swbpc94gTPEq8p_N0PpuZcCeMOHTb153SKBFmDHhEwYcsqLEueQ06MpwogKmAbmC2EUok6nmXE0zZAHzZQ1RAngRlWdyp8_FqIvqZI
Roughly ~6k instances a day since who knows when
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me …
> fix: Invalid Escape Sequence on Cobertura parser

- celery_config.py
- helpers/checkpoint_logger/flows.py
- helpers/notifier.py
- services/test_results.py
- services/tests/test_test_results.py
- tasks/__init__.py
- tasks/notify_error.py
- tasks/test_results_finisher.py
- tasks/tests/unit/test_notify_error_task.py
- tasks/tests/unit/test_test_results_finisher.py
- tasks/tests/unit/test_upload_finisher_task.py
- tasks/upload_finisher.py
fixes: https://github.com/codecov/internal-issues/issues/517
> Notify user of errors with uploading in comment

- services/bundle_analysis/new_notify/helpers.py
- services/bundle_analysis/new_notify/tests/test_helpers.py
- services/bundle_analysis/new_notify/types.py
- services/notification/notifiers/base.py
Part 1 of the bundle analysis notify refactor.
This PR simply introduces `NotificationType` and helper functions to determine
what notifications are configured based on the current_yaml.
Some other helper functions are from the existing notify service slightly adjusted
to not depend on the class they are declared in
> refactor: introduce helpers and types

- .gitignore
- services/report/__init__.py
- services/report/prometheus_metrics.py
arpad added one for the individual coverage files inside of an upload in https://github.com/codecov/worker/pull/574. this PR does the same for the overall upload
an upload contains one or more coverage files, but also path fixes and the output of `git ls-files`. so it can be much larger than just the sum of its coverage files. also those coverage files can be b64-encoded which affects the size too
(the .gitignore changes help me use Sapling with this repo and aren't important)
> add metric for overall report size

- requirements.in
- requirements.txt
This primarily pulls in https://github.com/codecov/shared/pull/309, which fixes an error related to `BundleAnalysisReport` keeping a SQLite connection open without properly closing it.
> Update `shared`, fixing `BundleAnalysisReport` connection leak

- helpers/metrics.py
- services/report/prometheus_metrics.py
- services/report/report_processor.py
- tasks/upload_finisher.py
like https://github.com/codecov/worker/pull/583 and https://github.com/codecov/worker/pull/574
arpad's metrics are already flowing. when this and #583 are deployed, i'll create a dashboard or a few showing p50/p75/p95 for:
- raw upload size + the number of coverage files contained in a single upload
- size of each individual coverage file inside an upload
- the above, grouped by format (cobertura, lcov, jacoco...)
- report_json size and chunks file size
> add metrics for report_json and chunks file sizes

- services/report/languages/jacoco.py
- services/report/languages/tests/unit/test_jacoco.py
JaCoCo currently sometimes output line 0 for coverage report, which is a confusing behaviour. This occurs primarily when the Kotlin compiler cannot properly resolve synthetic functions. Although this should ultimately be fixed in the Kotlin-JaCoCo report generation, we're just going to skip the line to allow for the rest of the report processing to work.
ref: https://github.com/codecov/internal-issues/issues/504
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping …
> Gracefully handle nr=0 in JaCoCo report

- docker/Dockerfile.requirements
Build was failing locally and it seems the base image we were using an out of date base image (`python:3.12.2-slim-bookworm`). Not sure in exactly what way this was breaking things, but using `python:3.12.4-slim-bookworm` fixes the issue.
> Update base image to python:3.12.4-slim-bookworm

- services/report/__init__.py
looking at the nearby counter metrics in Grafana, the median upload supposedly has no raw report files inside of it. we can search this log in GCS to see specific cases of this to see what's up.
> log when raw upload contains no uploaded files

- helpers/exceptions.py
- tasks/tests/unit/test_preprocess_upload.py
worker copy/pastes the definitions of exception types that live in shared now. worker code tries to catch the worker redefinitions, but shared is throwing the original shared definitions. even though they're named/defined identically, they're totally unrelated types. so the exceptions aren't caught
i added a unit test for the specific case i saw where an exception was not getting caught. there may be others
> re-export shared bot exceptions instead of redefining them

- helpers/telemetry.py
- services/archive.py
- tasks/base.py
This adds a bunch of instrumentation to `Archive` as well as add some Sentry tags to each Celery Task.
> Slightly improve tracing

- services/repository.py
- services/tests/test_repository_service.py
- tasks/preprocess_upload.py
- tasks/tests/unit/test_preprocess_upload.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
This function was copy-pasted across two different classes although it was not depending on any `self` class members.
The function is deduplicated and moved to a different place, along with its tests.
---
This PR was extracted from https://github.com/codecov/worker/pull/592, as its a simple standalone change.
> Move `fetch_commit_yaml_and_possibly_store` to `services.repository`

- services/bundle_analysis/new_notify/__init__.py
- services/bundle_analysis/new_notify/tests/test_notify_service.py
- services/bundle_analysis/new_notify/types.py
- tasks/bundle_analysis_notify.py
- tasks/tests/unit/test_bundle_analysis_notify_task.py
Activates the new notification service for bundle analysis
> feat: swap the notification services

- helpers/parallel_upload_processing.py
- helpers/sentry.py
- helpers/tests/unit/test_sentry.py
- services/report/__init__.py
- tasks/base.py
- tasks/upload.py
- tasks/upload_processor.py
This adds a bit more tracing to Upload related tasks, and task calls, as well as disable spammy signal spans in the automatically enabled Sentry Django integration.
> Add more tracing

- tasks/tests/unit/test_upload_finisher_task.py
- tasks/upload_finisher.py
Fixes a typo, adds a few types and simplifies code slightly
---
Extracted from https://github.com/codecov/worker/pull/592
> Clean up `UploadFinisher` task a bit

- requirements.in
- services/bundle_analysis/new_notify/contexts/__init__.py
- services/bundle_analysis/new_notify/contexts/comment.py
- services/bundle_analysis/new_notify/contexts/tests/test_contexts.py
- services/bundle_analysis/new_notify/helpers.py
- services/bundle_analysis/new_notify/messages/tests/test_comment.py
- services/bundle_analysis/new_notify/tests/test_helpers.py
- services/bundle_analysis/new_notify/tests/test_notify_service.py
- services/bundle_analysis/new_notify/types.py
These changes hide away the current_yaml from the Contexts.
The original idea was to not expose it, but I didn't do that detail correctly the 1st time.
Now it's hidden behind the `user_config` field. Builders still have full access.
The `user_config` field parses the config that will be used for commit statuses,
and also the config already used for the PR comment required changes.
Notice that we have 2 seemingly redundant options with `changes_threshold` and
`required_changes_threshold`. Still waiting on design to clean that up,
but they are technically different things at this time:
* `required_changes_threshold` is the threshold to send the comment;
* `changes_threshold` is the threshold to fail status checks
If they remain separate one of them will be renamed :E
> chore: user config in notifications

- tasks/upload.py
This moves the logic to debounce multiple `Upload` tasks based `upload_processing_delay` to its own function. It also fixes the debouncing logic so that it properly takes into account the previous task time.
Previously, assuming a 10-second delay, a previous upload 9 seconds in the past would delay the next upload by 10 seconds, for a total delta of 19. This now schedules the task in 1 second, so the total delay is at 10 seconds.
---
Extracted from https://github.com/codecov/worker/pull/592
> Simplify and fix debouncing of `Upload` task

- tasks/tests/integration/test_upload_e2e.py
- tasks/tests/utils.py
Instead of relying on overly mocked unit tests, this rather adds a mostly end-to-end test. It Pushes uploads to Storage/Redis, and then invokes the `Upload` task, running it to completion. After completion of the whole upload flow, it runs assertions on the final report after all processing is complete.
> Add an e2e-ish test for the Upload flow

- tasks/parallel_verification.py
- tasks/tests/integration/test_upload_e2e.py
- tasks/tests/unit/test_upload_task.py
- tasks/tests/utils.py
- tasks/upload.py
This replaces the manual chunking of upload processing tasks with a chunks generator. In addition, it also makes the `is_final` logic explicit. Previously, there was a bug related to this logic that would not mark the final chunk correctly as `is_final` in case it aligned on a chunk boundary.
---
Extracted from https://github.com/codecov/worker/pull/592
The `is_final` logic is important for the `ParallelVerification` task. This trace here exhibits a problem where the serial processing result is supposed to be uploaded, but is not due to that issue. The linked trace consists of 9 uploads/sessions, which are split into 3 equally sized chunks.
https://codecov.sentry.io/performance/trace/eaf0381cca8d4ad48cd22b1446c0122b/
> Refactor and fix task spawning in `Upload`

- services/bundle_analysis/new_notify/types.py
- tasks/bundle_analysis_notify.py
- tasks/tests/unit/test_bundle_analysis_notify_task.py
Refactor the bundle_analysis_notify task so `result` is always set,
and we early-return if there's nothing to notify on.
Adding a new `NotificationSuccess` value for the early return.
> fix: UnboundLocalError

- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
Celery `chain` automatically passes a first (non-kw) argument. However only for all the *successive* tasks, not the first one in the chain. So we have to pass that arg manually to the *first* task in that case.
Fixes WORKER-NFC
> Fix `BundleAnalysisProcessor` task receiving wrong arguments

- services/report/__init__.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/upload_processor.py
This removes and inlines the `schedule_for_later_try` call, and adjusts the tests accordingly
> Simplify retries of `build_report_from_raw_content`

- services/bundle_analysis/new_notify/__init__.py
- services/bundle_analysis/new_notify/tests/test_notify_service.py
When we fail to create the notification context we can't send that
notification, but that is not an error. So warning should suffice to aid in
debugging.
Typically this happens when some information is missing.
For example, a commit that is not part of a PR will fail to build the PR_COMMENT
notification context, simply because there is no PR associated with the commit.
> chore: reduce log level for step failed

- services/bundle_analysis/new_notify/__init__.py
- services/bundle_analysis/new_notify/tests/test_notify_service.py
Activates the bundle analysis commit statuses.
> feat: actuvate bundle analysis commit status

- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
According to traces, it happens quite frequently that an `Upload` task early-returns right after acquiring its upload lock because it does not have any pending tasks.
This moves this check outside of the lock to optimize one case. However it can still happen that concurrent `Upload` tasks "steal" each others pending uploads, so another check is still required within the lock.
> Check for pending uploads outside of lock

- services/bundle_analysis/new_notify/__init__.py
- services/bundle_analysis/new_notify/tests/test_notify_service.py
- tasks/tests/unit/test_bundle_analysis_notify_task.py
There's no actual checking if the notification was successful.
So the notification service will report FULL_SUCCESS even if notifications
attempted actually failed.
> fix: BA notify success

- services/report/__init__.py
- services/report/parser/__init__.py
- services/report/parser/tests/unit/test_parsers.py
We are capturing a couple internal errors where the `VersionOneReportParser` tries to json-parse something that is not JSON.
In particular, this event shows that the reportfile contents look rather like a `Legacy` format: https://codecov.sentry.io/issues/5258384165/events/1c65937e66614ec5b5f56743c3d42132/
To make this more bulletproof, this will now check that the format "looks like" JSON when choosing the parser, before it actually tries to fully json-parse the contents.
Fixes WORKER-MMH
> Consider contents when choosing between v1/legacy ReportParser

- main.py
- tests/unit/test_main.py
part of https://github.com/codecov/engineering-team/issues/2000
> add startup license logging to worker

- main.py
- tests/unit/test_main.py
This is causing issues with GCS rate limits on calling bucket create. We know the bucket exists already.
> Don't auto create bucket when not needed.

- helpers/pathmap.py
- helpers/tests/pathmap/test_pathmap.py
- helpers/tests/pathmap/test_tree.py
- services/path_fixer/__init__.py
This mostly rewrites the `Tree`, making the following changes and optimizations:
- Uses a real `Node` struct with children and terminals, instead of abusing special keys for it.
- Avoids constructing needless non-terminal strings for all intermediate nodes.
- Constructs the tree directly iteratively, instead of creating a parallel tree and merging recursively.
- Switches from recursion to iteration for `_drill`. It should be possible to also avoid recursion in lookup, but with a bit more effort.
This should primarily improve construction performance and improve memory usage, which was the primary pain points with the previous implementation.
> Rewrite the `pathmap.Tree`

- tasks/parallel_verification.py
fixes https://github.com/codecov/engineering-team/issues/2449
> Add Sentry Events/Metrics for ParallelVerification

- services/bundle_analysis/new_notify/helpers.py
- services/bundle_analysis/new_notify/tests/test_helpers.py
I was expecting that returning a certain type from yaml validation would keep the type.
Maybe there's some to-from dict transformation happening but the type is being lost,
and then re-casting it is not giving the expected results.
So I'm improving the function to make sure that `["percentage",["absolute",1000.0]]` won't be returned anymore.
Fixes Sentry issue 5767825563
> fix: type casting

- services/activation.py
- services/bundle_analysis/new_notify/contexts/comment.py
- services/bundle_analysis/new_notify/contexts/tests/test_comment_context.py
- services/bundle_analysis/new_notify/messages/comment.py
- services/bundle_analysis/new_notify/messages/templates/bundle_analysis_notify/upgrade_comment.md
- services/bundle_analysis/new_notify/messages/tests/test_comment.py
closes: https://github.com/codecov/engineering-team/issues/2254
Aligning with coverage and test analytics, PR comment for BA will
take up seats now.
> feat: count seats for BA notify

- database/engine.py
We have @events running in worker for whenever a repository is changed - these sync the data bw postgres db and shelter. While those are defined, those are never ran/acknowledged unless you import them, hence, this pr
> add database events to be executed

- database/base.py
- database/models/reports.py
the Flake model defined in shared uses the `BaseModel` which does not include the `external_id` field.
The `Flake` model defined in worker used the `MixinBaseClass` that included that field, I made a new `MixinBaseClassWithNoExternalID` so that there's an equivalent base class mixin for the `BaseModel` in shared, and changed the `Flake` to use that
> fix flake model

- services/bundle_analysis/report.py
- services/notification/notifiers/tests/conftest.py
- services/report/__init__.py
- services/test_results.py
- services/tests/test_report.py
- tasks/preprocess_upload.py
- tasks/upload.py
It looks like historically there is a mix of sync/async code.
The consensus(?) seems to favor sync code as celery is fundamentally sync.
Async code also does not play as well with profiling, which will not show the async code directly in a flamegraph, instead just inserting a `wait` for the async code running in a different thread.
> Make `ReportService` sync

- tasks/tests/integration/test_upload_e2e.py
- tasks/tests/utils.py
Extends the upload e2e test to also take into account the Comparison
that is generated when the commit is part of a PR.
> tests: extend upload e2e test

- tasks/upload_finisher.py
The `save_parallel_report_to_archive` function was recently refactored to not be `async` anymore. However the `async_to_sync` wrapper was still doing its job, running the function in an async context on a background thread.
This has lead to an error inside that function which was also calling `async_to_sync` internally.
Fixes WORKER-P4B
> Remove double-`async_to_sync`

- services/bundle_analysis/notify/__init__.py
- services/bundle_analysis/notify/helpers.py
- services/bundle_analysis/notify/tests/test_helpers.py
- services/bundle_analysis/notify/tests/test_notify_service.py
- services/bundle_analysis/tests/test_bundle_analysis.py
The objective here is to re-use the Pull and BundleAnalysisComparison that are loaded
as part of building contexts. Currently both the commit status and the PR comment notifications have to load these things independently.
Plus these just so happen to be the most slow parts of being a notification context.
Why flip the order in which we process the notifications?
Because the PR comment one is more restrictive, in the sense that the PULL cannot be `None`.
For the commit status it's possible that the Pull is `None`.
So by flipping them we can re-use the PR notification context "safely",
whereas the other way around we might run intro issues.
> perf: reuse pull and comparison

- services/report/report_builder.py
- services/report/report_processor.py
- services/report/tests/unit/test_report_processor.py
https://github.com/codecov/worker/pull/666 introduced a regression where an empty JSON object would end up being processed by the `NodeProcessor` and raise an exception in there.
fixes WORKER-P4T
> Properly skip parsing empty JSON

- database/tests/factories/reports.py
- services/test_results.py
- tasks/sync_pull.py
- tasks/tests/unit/test_sync_pull.py
- tasks/tests/unit/test_test_results_finisher.py
This PR does 2 things:
- makes it so the flaky shadow mode feature flag also enables the read path for flake detection, meaning when that feature flag resolves to true users will also get notified of any flaky tests that they fail on in their PRs
- change the behaviour of sync pulls to avoid calling the process flakes task when a repo isn't uploading test results
> Update flaky shadow mode

- database/events.py
- database/models/core.py
- database/tests/unit/test_events.py
> Revert "170 2 adjust event only to fire when due"

- .github/workflows/ci.yml
should automatically post/update a comment on PRs that change the hash of our `shared` dependency for reviewers to take a quick glance at
example comment (which was updated automatically as its PR switched to different hashes for `shared`):
> add shared-change-checker CI step

- services/bundle_analysis/notify/messages/comment.py
- services/bundle_analysis/notify/messages/templates/bundle_analysis_notify/bundle_comment.md
- services/bundle_analysis/notify/messages/templates/bundle_analysis_notify/bundle_table.md
- services/bundle_analysis/tests/test_bundle_analysis.py
add mention in the PR comment when bundle is cached
closes https://github.com/codecov/engineering-team/issues/2045
> feat: note when bundle is cached

- helpers/comparison.py
- services/comparison/__init__.py
- services/notification/notifiers/mixins/status.py
- services/repository.py
- tasks/compute_comparison.py
- tasks/notify.py
- tasks/tests/integration/cassetes/test_notify_task/TestNotifyTask/test_simple_call_only_status_notifiers.yaml
- tasks/tests/integration/test_notify_task.py
- tasks/tests/unit/test_notify_task.py
related: https://github.com/codecov/internal-issues/issues/721
related: https://github.com/codecov/engineering-team/issues/2387
We have a problem that the UI and the statuses are reporting different numbers for patch.
Part of this issue is that the `NotifyTask` (calculates patch for status) has access to the `Pull` while the `ComputeComparison` (calculates for the UI) doesn't.
This is a problem because the base for patch coverage might be different, so numbers would be different (see [here](https://github.com/codecov/worker/blob/9078de24b4dbed1bb64250b2b3864336954f310c/tasks/compute_comparison.py#L334) that we assume no action is needed cause there's nothing we can do).
So the 1st change here is to have the `NotifyTask` calculate and save patch coverage.
The second change is to cache the …
> fix: UI and status report diff patch numbers

- .github/workflows/ci.yml
- .github/workflows/pr_detect_shared_changes.yml
- requirements.in
- requirements.txt
https://github.com/codecov/gha-workflows/pull/32 will change this to use `main` before merging
- [run that skips posting a comment because shared was not changed](https://github.com/codecov/worker/actions/runs/10726314483/job/29746076253?pr=690)
- [run that posts a comment to this PR](https://github.com/codecov/worker/actions/runs/10726340835/job/29746157639?pr=690)
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can …
> move shared change check to separate workflow with correct permissions

- .github/workflows/pr_detect_shared_changes.yml
apparently i added https://github.com/codecov/worker/pull/690 to the merge queue. i meant to change the version of the workflow it used back to `main` before merging.
> use main instead of pr32 for shared dep change check

- services/report/__init__.py
- services/report/parser/legacy.py
- services/report/raw_upload_processor.py
- services/report/tests/unit/test_process.py
- services/tests/test_report.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/upload_processor.py
This moved some code around and improves type annotations. I tried to make the code related to error handling and "rewrite readable" a bit more readable, but wasn’t fully successful.
This should also slightly improve perf, as it should avoid re-SELECT-ing the `upload` after it has been modified. All in all, I still don’t understand why the upload model is fetched twice, but I guess its just some magic accessor that does this implicitly.
> Refactor Upload processing and file rewriting a bit

- services/bundle_analysis/notify/contexts/__init__.py
- services/bundle_analysis/notify/contexts/comment.py
- services/bundle_analysis/notify/contexts/commit_status.py
- services/bundle_analysis/notify/contexts/tests/test_comment_context.py
- services/bundle_analysis/notify/messages/comment.py
- services/bundle_analysis/notify/messages/templates/bundle_analysis_notify/bundle_comment.md
- services/bundle_analysis/notify/messages/templates/bundle_analysis_notify/bundle_table.md
- services/bundle_analysis/notify/messages/tests/test_comment.py
- services/bundle_analysis/tests/test_bundle_analysis.py
Customizes the bundle analysis PR comment based on the commit status outcome. matches designs in https://github.com/codecov/engineering-team/issues/1491 except for the table warnings (we can't get a per-bundle percentage yet)
Removing some unit tests in favor of larger scoped ones in `test_bundle_analysis.py`
> feat: customize comment based on status

- services/tests/test_timeseries.py
- services/timeseries.py
we were getting measurements with duplicate "index_elements" values in the measurements list which was causing errors because that's not allowed, so we have to deduplicate them. I added logs for when we get duplicates.
Fixes: https://github.com/codecov/internal-issues/issues/717
> fix: deduplicate component measurements

- services/bundle_analysis/notify/contexts/commit_status.py
- services/bundle_analysis/notify/contexts/tests/test_commit_status_context.py
For the `commit_status` context it's possible that the `pull` is `None` (which is not the case for `comment`). I forgot to include that check.
This really shows that:
(1) the builders pattern is not very good, because of code duplication, and
(2) we need better tests
But for now this only fixes issue worker-p8r
> fix: WORKER-P8R

- services/report/languages/cobertura.py
- services/report/languages/helpers.py
- services/report/languages/jacoco.py
- services/report/languages/lcov.py
- services/report/languages/lua.py
- services/report/languages/mono.py
- services/report/languages/pycoverage.py
- services/report/languages/scoverage.py
- services/report/languages/tests/unit/test_cobertura.py
- services/report/languages/tests/unit/test_dlst.py
- services/report/languages/tests/unit/test_pycoverage_encoded_labels.py
- services/report/languages/tests/unit/test_scoverage.py
- services/report/languages/tests/unit/test_vb2.py
- services/report/languages/vb.py
- services/report/languages/vb2.py
- services/report/languages/xcode.py
- services/report/languages/xcodeplist.py
- services/report/report_builder.py
This only fixes the type errors in one part of the language processors. Others still fail mypy, and I will fix those in followup PRs.
> Fix some type errors in `LanguageProcessor`s

- helpers/reports.py
- services/report/__init__.py
- services/yaml/reader.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
- tasks/upload_processor.py
Instead of creating a copy of a raw upload for consumption in the parallel verification task, this will only schedule parallel verification in case the uploads are not being deleted after processing.
That way, the uploads are guaranteed to still be there for verification, so no copy is needed.
> Avoid copying raw upload for parallel verification

- requirements.in
- requirements.txt
- services/comparison/__init__.py
- tasks/notify.py
- tasks/tests/unit/test_notify_task.py
depends on https://github.com/codecov/shared/pull/354
These changes collect extra SHAs that we need to (potentially) notify for GitLab users
that use "merge request result" pipelines and the "merge train" feature.
These changes only _collect_ the extra SHAs. The actual notification will happen later.
> feat: collect extra shas for gitlab notif

- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
we don't need to fetch the report upload because all we're doing is setting the upload_pk to upload_id in the normalized args dict
we also can batch our redis lpops into groups of 50 so we don't have to make as many calls to redis
> perf: use lpop with count and don't fetch upload in Upload task

- services/repository.py
- services/tests/test_repository_service.py
We were not actually performing the branch filter on the git parents. This fixes it and also refactors the code a bit to avoid duplication.
> Fix commit parent selection when there are multiple parents

- services/redis.py
- services/report/__init__.py
- tasks/flush_repo.py
- tasks/upload.py
It looks like this code was incomplete, as it was *writing* to redis, but never *reading* from it.
> Remove parallel session_id allocations in Redis

- helpers/parallel_upload_processing.py
- services/report/__init__.py
- services/report/raw_upload_processor.py
- services/report/tests/unit/test_process.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
- tasks/upload_finisher.py
- tasks/upload_processor.py
This reverts commit b110b7f8a37968786b30be6356217ef4e92096ec.
This has caused https://codecov.sentry.io/issues/5867617053/ which is reported as **integer out of range**.
Possibly the `order_number` is not wide enough to take the same values as the session_id. :-(
> Revert "Make `session.id == upload.id` (#713)"

- services/notification/notifiers/status/base.py
- services/notification/notifiers/tests/unit/test_status.py
related to https://github.com/codecov/engineering-team/issues/2076
Now that we are collecting different SHAs that we potentially need to notify for Gitlab,
the only missing piece was actually doing the notification in multiple SHAs.
Some notes:
* The `checks` notifier is exclusive for GitHub, so no need to change that
* "notifying to multiple shas" is done in the most transparent way possible
* I created `_send_notification_with_metrics` just to wrap the timer, but it would probably be better to
add it in the Torngit adapter directly
* We don't need to do this for the PR comment, just the status
> feat: notify status to multiple shas (gitlab)

- services/bundle_analysis/notify/contexts/comment.py
- services/bundle_analysis/notify/contexts/commit_status.py
- services/bundle_analysis/notify/helpers.py
- services/bundle_analysis/notify/messages/comment.py
- services/bundle_analysis/notify/messages/templates/bundle_analysis_notify/bundle_table.md
- services/bundle_analysis/notify/messages/tests/test_comment.py
- services/bundle_analysis/notify/tests/test_helpers.py
- services/bundle_analysis/tests/test_bundle_analysis.py
The designs for the bundle comment include percentage change and potentially warnings
in the rows of the bundles (PR comment).
These changes add those.
This fully matches the designs for now.
> feat: add percentage change and warnings in bundle rows

- services/report/languages/go.py
- services/report/languages/helpers.py
- services/report/languages/tests/unit/test_go.py
It appears that Go coverage reports are very susceptible to mangled lines. This makes sure we encapsulate all of the parsing for a coverage line within a try/except block, or skip over other invalid lines, instead of raising unexpected errors.
fixes [WORKER-MB9](https://codecov.sentry.io/issues/5165160706/), fixes [WORKER-P4S](https://codecov.sentry.io/issues/5787850847/), fixes [WORKER-P8D](https://codecov.sentry.io/issues/5826394496/), fixes [WORKER-P7Z](https://codecov.sentry.io/issues/5821076186/), fixes [WORKER-PAJ](https://codecov.sentry.io/issues/5860678163/), fixes [WORKER-PAH](https://codecov.sentry.io/issues/5860453353/), fixes [WORKER-P56](https://codecov.sentry.io/issues/5792037589/), fixes [WORKER-P7W](https://codecov.sentry.io/issues/5820563536/), fixes …
> Better detect corrupted Go report lines

- services/report/languages/lcov.py
- services/report/languages/tests/unit/test_lcov.py
fixes [WORKER-JGW](https://codecov.sentry.io/issues/5065170594/), fixes [WORKER-JN4](https://codecov.sentry.io/issues/5067222163/), fixes [WORKER-JMY](https://codecov.sentry.io/issues/5067151603/), fixes [WORKER-JNY](https://codecov.sentry.io/issues/5068075518/), fixes [WORKER-PA7](https://codecov.sentry.io/issues/5859337983/)
> Make lcov parser more accepting of corrupt coverage lines

- services/report/languages/coveralls.py
- services/report/languages/tests/unit/test_coveralls.py
It looks like for some reason, the `coverage` can also be a string with a json-encoded list. This change handles that case.
Fixes [WORKER-PA5](https://codecov.sentry.io/issues/5859233085/), fixes https://github.com/codecov/internal-issues/issues/797
> Coveralls parser now accepts json-encoded `coverage`

- database/models/reports.py
This primarily changes the types from `Integer` (i32) to `BigInteger` (i64), to align foreign keys with the column types they are pointing to.
At least for `reports_uploadleveltotals.upload_id`, the column in production is already an i64, and the column values exceed the value range of an i32.
> Fix various foreign key column definitions

- services/bundle_analysis/report.py
- services/report/__init__.py
- services/report/report_processor.py
- services/test_results.py
- tasks/upload.py
The `Upload` task schedules multiple `UploadProcessor` tasks and another `UploadFinisher`.
This batching is rather accidental because of locking rather than intentional. It might be good to know how uploads are being grouped into a single processor/finisher chain.
Also includes a bunch of cleanups and driveby typing fixes.
> Add metric for uploads per scheduled tasks

- services/test_results.py
This fixes a regression from https://github.com/codecov/worker/pull/718:
Seems like `flags` is a comma-separated string in all upload types except `TestResults`, where it is already a list.
Fixes [ECDN-WORKER-D7C](https://codecov.sentry.io/issues/5879541242/), fixes [WORKER-PBY](https://codecov.sentry.io/issues/5879476288/)
> Fix `flags` being a `list` in TestResults arguments

- services/bundle_analysis/report.py
- services/bundle_analysis/tests/test_bundle_analysis.py
- tasks/bundle_analysis_save_measurements.py
- tasks/tests/unit/test_bundle_analysis_save_measurements_task.py
closes https://github.com/codecov/engineering-team/issues/1875
No need to save every bundle of a commit, just save the processed bundle instead, otherwise it is inserting duplicate measurements to timeseries
> bundle analysis: remove unnecessary save measurements

- helpers/labels.py
- services/path_fixer/__init__.py
- services/path_fixer/tests/unit/test_path_fixer.py
- services/report/__init__.py
- services/report/raw_upload_processor.py
- services/report/tests/unit/test_sessions.py
- services/report/tests/unit/test_sessions_encoded_labels.py
- services/repository.py
- services/tests/test_report.py
- tasks/tests/integration/test_upload_e2e.py
- tasks/upload_finisher.py
This just moves some code around, removes excessive logging and metrics, and aims to make things a bit more readable.
---
Feel free to review this with "ignore whitespace", as it does some re-indenting.
> Clean up some carry-forward related code

- services/report/languages/lcov.py
- services/report/languages/tests/unit/test_lcov.py
The `append/merge` operation on lines does not work properly when merging a covered line with a partial branch.
Therefore, prefer the branch coverage by overwriting any existing line records.
---
This was a regression from https://github.com/codecov/worker/pull/684 and fixes https://github.com/codecov/feedback/issues/513
> lcov Branches should override Lines

- tasks/test_results_finisher.py
- tasks/tests/unit/test_test_results_finisher.py
we want to ignore flakes that are obvisouly tests that were broken for a bit but are now fixed
> feat: fix heuristic when reading flakes

- tasks/tests/integration/test_upload_e2e.py
This adds another E2E-style test which runs the "full" upload process from Redis through the various Upload Tasks, using two consecutive commits that will carry-forward a couple of sessions from the first to the second commit.
> Create an E2E test for Carryforwarding

- services/notification/notifiers/mixins/status.py
- services/notification/notifiers/tests/unit/test_status.py
The math was not math-ing (i.e. it would only work if the difference between BASE and HEAD
was within 0.01, in absolute value)
Now the math allows the HEAD to be infinitely greater than the base when suceeding.
Added better tests as well. Reduced wiggle room to 0.005.
closes https://github.com/codecov/feedback/issues/463 …
> fix: adjust_base behavior

- services/report/parser/legacy.py
- services/report/parser/types.py
- tasks/tests/samples/sample_uploaded_report_1.txt
- tasks/tests/unit/test_upload_processing_task.py
- tasks/upload_processor.py
These reports are already "readable", so there is no need to rewrite them.
Should save a GCS write call in that case for a small speedup.
> Do not `rewrite_readable` legacy Reports

- helpers/github_installation.py
- helpers/tests/unit/test_github_installation.py
- services/repository.py
- services/tests/test_repository_service.py
- tasks/bundle_analysis_notify.py
- tasks/commit_update.py
- tasks/compute_comparison.py
- tasks/notify.py
- tasks/preprocess_upload.py
- tasks/save_report_results.py
- tasks/sync_pull.py
- tasks/sync_repo_languages.py
- tasks/upload.py
- tasks/upload_processor.py
This concept is only relevant for github, so move an appropriate check inside.
Also removes the superfluous `dbsession` parameter, and removes the caching which is quite the overkill for this very simple query:
> Simplifies `get_installation_name` a bit

- services/bundle_analysis/notify/contexts/__init__.py
- services/bundle_analysis/notify/contexts/tests/test_contexts.py
Fixes WORKER-PA8
The "comment" is allowed to be `bool` type, and that breaks the user_config loading.
> fix: comment config can be bool

- helpers/github_installation.py
- helpers/tests/unit/test_github_installation.py
- services/repository.py
- services/tests/test_repository_service.py
- tasks/bundle_analysis_notify.py
- tasks/commit_update.py
- tasks/compute_comparison.py
- tasks/notify.py
- tasks/preprocess_upload.py
- tasks/save_report_results.py
- tasks/sync_pull.py
- tasks/sync_repo_languages.py
- tasks/upload.py
- tasks/upload_processor.py
This is the same as #749 which I reverted immediately as the added caching for `get_repo_provider_service` did not work properly due to the types not being `pickle`-able.
> Simplify `get_installation_name` a bit

- services/report/__init__.py
- services/report/raw_upload_processor.py
- services/tests/test_report.py
- tasks/tests/integration/test_upload_e2e.py
The `Upload`s in the database should mirror the `Session`s within a stored `Report`.
However, so far this was not the case for carryforwarded sessions/uploads. The `Session`s were removed from the `Report` as they were being overridden by new uploads, but that was not the case for the `Upload` rows in the database which were created from the carry-forwarded `Session`s on initial `Report` carry-forwarding.
This change will now make sure that the `Upload`s in the database match the `Session`s in the `Report`.
> Clear CFF `Upload`s as they are overwritten

- tasks/sync_pull.py
- tasks/tests/unit/test_sync_pull.py
These changes handle `NoConfiguredAppsAvailable`. There is no way of recovering
from that - similar to `RepositoryWithoutValidBotError` - but we can fail in a clean way
instead of just dying with an exception.
closes [WORKER-P24](https://codecov.sentry.io/issues/5763549073/)
> chore: handle NoConfirugedAppsAvailable error

- services/bundle_analysis/report.py
Add a logging for printing errors for parsing. 
> bundle analysis: add logging for fail to parse

- helpers/parallel.py
- services/report/__init__.py
- tasks/tests/integration/test_upload_e2e.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/upload.py
- tasks/upload_finisher.py
- tasks/upload_processor.py
This adds another variant to the `PARALLEL_PROCESSING` feature/rollout flag which prefers the parallel upload processing pipeline in favor of running it as an experiment.
Upload Processing can run in essentially 4 modes:
- Completely serial processing
- Serial processing, but running "experiment" code (`EXPERIMENT_SERIAL`):
- In this mode, the final (`is_final`) `UploadProcessor` task saves a copy
of the final report for later verification.
- Parallel processing, but running "experiment" code (`EXPERIMENT_PARALLEL`):
- In this mode, another parallel set of `UploadProcessor` tasks runs *after*
the main set up tasks.
- These tasks are not persisting any of their results in the database,
instead the final `UploadFinisher` task will launch the `ParallelVerification` task.
- Fully parallel …
> Implement fully parallel upload processing

- helpers/parallel.py
- tasks/upload.py
- tasks/upload_finisher.py
- tasks/upload_processor.py
The parallel upload processing feature flag had an edge-case where toggling the feature flag would effect all *already running* tasks, moving them from experiment mode to fully parallel mode.
Now this decision is being made at the very beginning in `Upload`, and the scheduled tasks adhere to that decision.
> Gracefully upgrade existing tasks to parallel processing

- tasks/upload_finisher.py
This was an oversight in the original parallel processing PR.
The final merge step is now performed while holding the "master Report" lock to guard against concurrent mutation.
> Perform parallel report merging within the Report lock

- helpers/parallel_upload_processing.py
- tasks/upload.py
- tasks/upload_finisher.py
- tasks/upload_processor.py
I replaced this by just using the upload_id a while back, so this PR here will just finish that cleanup by just removing the `parallel_idx` completely.
> Clean up usage of `parallel_idx`

- services/archive.py
- tasks/parallel_verification.py
- tasks/tests/integration/test_upload_e2e.py
- tasks/upload_finisher.py
This makes sure the following intermediate files are being cleaned up / deleted after parallel processing:
- The "partial Report" files, after merging
- The copy of the *initial* and the *final* "master Report" used in parallel verification
- The parallel version of the "master Report" used for verification
> Delete intermediate report files used in parallel Processing

- helpers/sentry.py
According to https://docs.sentry.io/platforms/python/integrations/redis/#options, adding an appropriate `cache_prefix` should make sure that things get automatically populated in the Sentry "Caches" insights page.
It might still be worth manually instrumenting the underlying cache code in `shared` though.
> Enable cache monitoring in Sentry Redis integration

- helpers/telemetry.py
This will now add some common task tags to the Sentry transaction as well. Not sure why, but this used to just work using the global tags, but stopped working at some point (possibly because of an SDK update?)
> Add tracing tags explicitly

- helpers/notifier.py
- services/comparison/changes.py
- services/notification/__init__.py
- services/notification/notifiers/base.py
- services/notification/notifiers/checks/base.py
- services/notification/notifiers/checks/changes.py
- services/notification/notifiers/checks/checks_with_fallback.py
- services/notification/notifiers/checks/patch.py
- services/notification/notifiers/checks/project.py
- services/notification/notifiers/codecov_slack_app.py
- services/notification/notifiers/comment/__init__.py
- services/notification/notifiers/generics.py
- services/notification/notifiers/gitter.py
- services/notification/notifiers/hipchat.py
- services/notification/notifiers/irc.py
- services/notification/notifiers/mixins/message/__init__.py
- services/notification/notifiers/mixins/status.py
- services/notification/notifiers/slack.py
- services/notification/notifiers/status/base.py
- services/notification/notifiers/status/changes.py
- services/notification/notifiers/status/patch.py
- services/notification/notifiers/status/project.py
- services/notification/notifiers/webhook.py
Adds tracing to the various `notify` implementations, and improves their typing. In particular, it fixes mismatches between the base and derived classes, and fixes up type annotations to match their usage.
> Add tracing and improve typing of `NotificationService`

- services/activation.py
- services/bundle_analysis/notify/__init__.py
- services/bundle_analysis/notify/contexts/__init__.py
- services/bundle_analysis/notify/contexts/comment.py
- services/bundle_analysis/notify/contexts/commit_status.py
- services/bundle_analysis/notify/contexts/tests/test_comment_context.py
- services/bundle_analysis/notify/contexts/tests/test_commit_status_context.py
- services/bundle_analysis/notify/helpers.py
- services/bundle_analysis/notify/messages/tests/test_comment.py
- services/bundle_analysis/notify/messages/tests/test_commit_status.py
- services/bundle_analysis/notify/tests/test_notify_service.py
- services/bundle_analysis/tests/test_bundle_analysis.py
This was not the main goal I had, but these errors were really distracting,
so fixing some type errors in BA notifiers.
One side-effect is that when loading the user_config we are now expecting the comment
config to be `bool | dict` (not `None`). This is in fact the case because we have default
config in place, but the tests didn't know that. Now they do.
I might have also caught a bug in the user activation in terms of the func args.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my …
> chore: fix (some) type errors in BA notify

- conftest.py
- services/processing/state.py
- services/tests/test_processing_state.py
- services/tests/test_redis.py
- tasks/tests/unit/test_send_email_task.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/upload.py
- tasks/upload_finisher.py
- tasks/upload_processor.py
This introduces a new component that is responsible for keeping track of the processing status of individual uploads.
The goal here is that this state tracking can make batched Report merging and debounced notifications a lot more intentional.
The state tracking is achieved by keeping sets of `upload_id`s in Redis, one for in-progress (currently being parsed) Uploads, another for processed (and waiting to be merged) Uploads.
---
This is part of https://github.com/codecov/engineering-team/issues/2618
> Keep track of in-progress Uploads

- services/processing/loading.py
- services/processing/merging.py
- services/processing/state.py
- services/tests/test_processing_state.py
- tasks/upload_finisher.py
This should make the high level steps of parallel processing a bit more obvious and easier to grasp.
> Move loading and merging intermediate Reports to its own file

- services/processing/merging.py
- services/report/__init__.py
- services/tests/test_report.py
The previous code was doing a SELECT/UPDATE cycle for each of the `Upload` records needing updates. This will now avoid doing the SELECTs, and only emit `UPDATE` statements.
As a driveby change, this should also fix an edge-case where a deleted `session_id` is immediately being reused.
> Optimize `update_uploads`

- services/processing/merging.py
fixes [WORKER-MM5](https://codecov.sentry.io/issues/5256339866/)
> Account for empty reports when merging

- tasks/tests/unit/test_upload_finisher_task.py
- tasks/upload_finisher.py
Instead of failing with a `LockError`, this copy-pasted the same retry logic as the `UploadProcessor` has.
---
Fixes [WORKER-PJE](https://codecov.sentry.io/issues/5974196957/)
> Retry `UploadFinisher` when Report is locked

- services/repository.py
This re-does part of https://github.com/codecov/worker/pull/776 (that was reverted)
It aims to reduce 1 DB operation by not refreshing immediately after changing a Session object.
And to make the code style more similar to what we use elsewhere (not accessing the tables directly unless necessary)
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's …
> perf: remove extra refresh

- tasks/tests/unit/test_upload_finisher_task.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/upload_finisher.py
- tasks/upload_processor.py
Moves the `load_commit_diff` portion out of `save_report_results`.
This way, the whole commit diff loading can be moved outside of the Report merge lock. Additionally, the function was decorated with a cache, as the diff for a commit will never change.
> Cache and move `load_commit_diff` out of Report lock

- helpers/checkpoint_logger/__init__.py
- helpers/checkpoint_logger/prometheus.py
We want to separate prometheus responsibilities from the checkpoint responsibilities to later extend its functionality. This PR just rearranges logic and doesn't include new one, to separate reviews into more manageable chunks. 
This PR mainly creates the PrometheusCheckpointLoggerHandler class, which has log_X methods for logging X things. This class is then used in the checkpoint_logger.__init__.py file
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this …
> Created prometheus handler class

- services/tests/test_repository_service.py
This helps reduce database key conflicts by reusing existing objects for tests
This refactor was pulled out of https://github.com/codecov/worker/pull/729 to make changes more manageable. It solved a problem where recreating the objects had conflicts when I switched to Django models (duplicate key errors).
This is also significantly easier to review if you set "hide whitespace" to view the diff because I removed test classes.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and …
> Refactored repository services tests to use fixtures

- database/models/core.py
This is getting this more similar to how the models are defined in Django
Another small fix pulled out from https://github.com/codecov/worker/pull/729 . 
> Add defaults to models with DB defaults set

- services/bundle_analysis/report.py
re-organize the code to make tracing more evident.
Sadly the part that usually takes the longest needs to be updated in shared.
I include a small optimization making the CacheConfig query return the data in the format we want it
instead of having to go over the list again.
> chore: further breakdown tracing in BA processor

- helpers/telemetry.py
- tasks/base.py
- tasks/tests/unit/test_base.py
This explicitly declares and forwards all the arguments to the `on_success/retry/failure` task hooks, as they are documented on https://docs.celeryq.dev/en/main/_modules/celery/app/task.html#Task.on_success
The reason being that the Sentry tags set via the `MetricContext` constructor are not making their way to Sentry, possibly because the `kwargs` were misused in the previous hooks, and were overwriting those tag values with `None`.
So this should ideally solve that mystery.
As a driveby change, I also took the liberty of removing all the deprecated statsd `metrics` calls. All of the relevant metrics also have prometheus equivalents.
> Use correct signatures for Celery Task Hooks

- database/tests/factories/core.py
- tasks/tests/unit/test_brolly_stats_rollup.py
- tasks/tests/unit/test_commit_update.py
- tasks/tests/unit/test_sync_pull.py
- tasks/tests/unit/test_upload_task.py
This is because the tests were failing on duplicate keys. Fixtures reuses existing objects, which avoids creating objects with duplicate keys.
This was also extracted from https://github.com/codecov/worker/pull/729 . 
Also, since I also got rid of the Test Class, there's also a lot of white space changes. I would suggest selecting `Hide whitespace` when reviewing this.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry …
> Refactor tests to use fixtures

- services/bundle_analysis/report.py
> bundle analysis: move to prometheus

- database/models/reports.py
In particular, this table doesn't actually have an external id.
This was pulled out from #729 
> Fix ReducedError to make it more similar to Django Model

- helpers/log_context.py
- helpers/logging_config.py
- helpers/tests/unit/test_log_context.py
- helpers/tests/unit/test_logging_config.py
- tasks/base.py
new functions for managing log context:
- `get_log_context()`
- `set_log_context(LogContext())`
- `update_log_context({"repo_id": 5})`
`tasks/base.py` / `helpers/logging_config.py` use this new `ContextVar` log context instead of globals to put the task name and id on each log message. in separate PRs, we can continue on to:
- automatically add `repo_id`/`owner_id`/`commit_sha` to log messages when available
- get rid of `MetricContext`, making SQL metrics much less cumbersome to work with
- store `CheckpointLogger` data in the `ContextVar` to clean up usage a bit
the globals were put in because previously we got the task details from `get_current_task()` and its `request` member. the request is definitely a thread-local variable and `get_current_task()` may also rely on thread-local …
> create LogContext ContextVar and populate in tasks/base.py

- services/notification/notifiers/codecov_slack_app.py
- services/notification/notifiers/mixins/status.py
- tasks/notify.py
- tasks/tests/integration/test_notify_task.py
There were a couple of errors spread around the notification code assuming that a `head.report` always exists, which is not necessarily the case.
In particular that would be the case when using `empty-upload` or `manual_trigger`.
---
Fixes [WORKER-P6A](https://codecov.sentry.io/issues/5801299347/)
> Fix notifications with an empty HEAD report

- helpers/log_context.py
- helpers/logging_config.py
- helpers/tests/unit/test_log_context.py
- helpers/tests/unit/test_logging_config.py
currently worker logs have celery task information that you can query in GCP Logs Explorer with something like
```
jsonPayload.task_name="app.tasks.compute_comparison.ComputeComparison"
jsonPayload.task_id="c70bf145-dbcc-43ff-970d-dcf9251e289f"
```
those fields are still there, but this PR adds a lot more:
- task info (new location) `jsonPayload.context.task_name` and `jsonPayload.context.task_id`
- repo info `jsonPayload.context.repo_name` and `jsonPayload.context.repo_id`
- owner info `jsonPayload.context.owner_name`, `jsonPayload.context.owner_service`, `jsonPayload.context.owner_id`
- commit info `jsonPayload.context.commit_sha` and `jsonPayload.context.commit_id`
- note: in many places we call the SHA the `commitid` but here the SHA is `commit_sha` and the database ID is `commit_id` …
> add commit/owner/repo/sentry context to all log messages

- tasks/test_results_processor.py
- tasks/tests/unit/test_test_results_processor_task.py
we want to handle the case where there is no actual class name when computing the name for a Pytest test.
this commit also adds unit tests for the compute_name function in test_test_results_processor_task.py
> fix: update compute_name and add tests

- tasks/tests/integration/test_upload_e2e.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
- tasks/upload_processor.py
With parallel upload processing fully rolled out, its time to start cleaning up the feature flag.
This first step is changing the initial `Upload` task to only schedule the parallel version of `UploadProcessor/Finisher`.
As there will probably be a bunch of already scheduled tasks at time of deploy, this does not yet change those tasks to assume they run in fully parallel mode.
> Only schedule parallel Upload Tasks

- helpers/parallel_upload_processing.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/upload_processor.py
So far, this removes the lock handling, and the code to store the "experiment" reports, along with other codepaths only relevant for serial processing mode.
A bunch of tests are also being removed which would have asserted that `UploadProcessor` is updating the final `report_json`, which is not the case anymore, as that logic now happens in `UploadFinisher` only.
> Hardcode parallel-only mode in `UploadProcessor`

- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
- tasks/upload_finisher.py
this is a low-hanging fruit for reducing database locking. instead of doing this write in the repos table for _every_ `UploadTask`, let's do it for `UploadFinisher` which should run less
that said, the `UploadFinisher` task will hold the lock longer
> move repo.updatestamp update from Upload to UploadFinisher

- django_scaffold/settings.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
Fix DB perf issues. We also gained intended insight from this metric in terms of understanding a user signup- > completed upload ratio.
> Stop tracking onboarding metrics

- tasks/tests/unit/test_process_flakes.py
- tasks/tests/unit/test_test_results_processor_task.py
This was leaking into other tests (other tests were using the wrong times).
Pulled this out from https://github.com/codecov/worker/pull/729
> Fix leaky usage of time machine

- tasks/send_email.py
- tasks/tests/integration/test_send_email_task.py
- tasks/tests/unit/test_send_email_task.py
Updates the send email task to 
1. take a to-address instead of an owner and
2. make from-address optional, pulling from config if not set explicitly in the call.
> ref: Tweaks to send email task

- services/processing/processing.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/upload_processor.py
The code has been moved out of the `UploadProcessor` task into its own file, and adapted in such a way that it will only deal with a single upload per task invocation.
> Rewrite the core `UploadProcessor` logic

- conftest.py
These logs were getting really noisy when testing locally (especially when running with verbose mode `-vv`). Removing unnecessary logs should make it more manageable to debug, especially since the VCR logs aren't super useful. If someone wants the full log, they can remove this or override manually.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's …
> Only show VCR logs on errors

- helpers/log_context.py
- helpers/tests/unit/test_log_context.py
- tasks/base.py
Previously, this would unset the `LogContext` back to an empty version at the end of the task `run` hook. However this would also unset all the previously set Sentry tags. As the Sentry Celery integration automatically wraps the `run` function, the Sentry tags have to persist past the end of said function.
This will now only set an initialized `LogContext` when entering `run`, and keep that around until the next task overwrites it. That way, we should also get an initialized context for any async code that runs outside of the `run` scope.
> Do not clear the `LogContext` on task finish

- services/report/languages/cobertura.py
- services/report/languages/gap.py
- services/report/languages/jetbrainsxml.py
- services/report/languages/lcov.py
- services/report/languages/mono.py
- services/report/languages/tests/unit/test_cobertura.py
- services/report/languages/tests/unit/test_jetbrainsxml.py
- services/report/tests/unit/test_process.py
An empty `ReportFile` is boolean-coerced to `False`, so we always need to explicitly compare it to `None`.
This primarily fixes the `JetBrainsXML` parser always emitting empty `Report`s. Also fixes cobertura failing on empty filenames, and other smaller fixes.
---
Fixes https://github.com/codecov/feedback/issues/532
Fixes [WORKER-P9A](https://codecov.sentry.io/issues/5845175379/)
> Properly check for created coverage files

- services/processing/intermediate.py
- services/processing/merging.py
- services/processing/processing.py
- services/processing/types.py
- tasks/tests/unit/test_upload_finisher_task.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
- tasks/upload_finisher.py
This also returns more information in the `ProcessingResult`, in order to clean it up in a forwards compatible way, as well as laying the groundwork for eventually updating the `Upload` state and error only once in the finisher instead of touching that DB object twice in the processor and finisher.
> Start properly typing `processing_results` and `arguments_list`

- services/timeseries.py
There was a bunch of duplication and large methods. This refactoring reduces the duplication and standardized measurement creation. Also, makes the giant method easier to follow, hopefully.
No functionality had been changed.
> Refactor timeseries service to dedupe code

- Makefile
- tasks/sync_repos.py
Only update the timestamp IF other fields change. This will help immensely with DB lock contention.
> Less repo timestamp updates

- tasks/test_results_processor.py
the rewrite_readable and writing of the storage file should've been outside the loop, having them inside the loop was:
1. doing extra useless work by calling rewrite_readable a bunch of times
2. causing rate limit errors in GCS due to trying to write to the same object so often, resulting in the task failing
> fix: rewriting of test result reports

- requirements.in
- requirements.txt
- services/report/__init__.py
- services/tests/test_report.py
- tasks/tests/integration/test_upload_e2e.py
- tasks/tests/unit/test_preprocess_upload.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/tests/unit/test_upload_task.py
This model was previously used for the ill-fated `report_builder` feature which was since removed.
Avoiding the table and in particular the `files_array` saves us from one GCS write per report, so should speed up the `UploadFinisher` ever so slightly.
> Stop writing `ReportDetails`/`files_array`

- requirements.in
- requirements.txt
Updating django as there are vuln tickets
https://github.com/codecov/internal-issues/issues/904
https://github.com/codecov/internal-issues/issues/905
> 904 update django dependency

- services/processing/processing.py
- services/processing/types.py
- tasks/tests/unit/test_upload_finisher_task.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
The `UploadFinisher` was made forward compatible to accept a new shape of arguments, which itself is the return value of the `UploadProcessor`.
Both tasks are also cleaned up of some old obsolete task arguments which are not being used anymore.
> Clean up `Upload{Processor,Finisher}` task args and return values

- tasks/tests/integration/test_upload_e2e.py
- tasks/tests/unit/test_manual_trigger.py
- tasks/tests/unit/test_test_results_processor_task.py
- tasks/tests/unit/test_upload_finisher_task.py
Extracted this from https://github.com/codecov/worker/pull/729
A few of the tests become flaky when migrating to the Django models because of some unique references that's defined in Django, but not SQLAlchemy. 
In particular, the way that FactoryBoy creates references can be flakey (i.e. Commits referencing Pulls. If the original `pull` is not flushed, there is a chance that the `commit` gets created first, which inadvertently creates a separate pull with the `id` of the one that you specified to create). So, doing an explicit flush will of `pull` before creating the `commit` will fix this. 
Also fixed a test where DB returned results are not necessarily ordered.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional …
> Fix some flakey tests

- tasks/test_results_processor.py
- tasks/tests/unit/test_test_results_processor_task.py
we deadlock when inserting (on conflict do update is the part i think
causes this) tests possibly because each worker task is inserting tests
in a different order, this fixes that by making sure if tasks are inserting
the same tests they will insert them in the same order
does the same for the rollups batch insert on conflict do update
> fix: deadlock when inserting tests and rollups

- rollouts/__init__.py
- services/processing/intermediate.py
- services/processing/processing.py
- tasks/tests/integration/test_upload_e2e.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
- tasks/upload_finisher.py
- tasks/upload_processor.py
This adds a new feature flag to store intermediate reports in Redis rather than in GCS.
Doing so will remove very slow GCS write/delete operations from the processing/merging flow respectively. It also switches from `gzip` to `zstd` compression for those reports, which should also be slightly faster.
> Store intermediate Reports in Redis

- services/test_results.py
- services/tests/test_test_results.py
- tasks/tests/unit/test_test_results_finisher.py
Updating the PR comment as described in [#2711](https://github.com/codecov/engineering-team/issues/2711) 
> fix: Update the PR comment footer copy

- tasks/github_marketplace.py
- tasks/tests/unit/test_ghm_sync_plans.py
This PR aims to update the stripe call from a .delete() to a .cancel() when the user purchases Codecov via the Github Marketplace and already has an existing stripe subscription.
Delete doesn't actually cancel the stripe subscription, and shouldn't be called at all [looking at the Stripe documentation](https://docs.stripe.com/api#cancel_subscription)
Closes https://github.com/codecov/internal-issues/issues/1033
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this …
> fix: Cancel Stripe sub when user purchases via GHM

- services/repository.py
- tasks/commit_update.py
- tasks/preprocess_upload.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
This makes the `possibly_` variant of this function sync, to avoid an unnecessary `async_to_sync` call.
The main function is changed in such a way that:
- It early-returns when no commit was found, de-indenting the rest of the block
- Most importantly, it moves some of the field writes around, and adds an explicit `flush` at the end. That way, it avoids splitting the `UPDATE` into two different queries, and rather does one update at the end.
- A query indirection doing a `COUNT` before the actual query is removed by just doing the filtering on the Python side
- It might avoid a second provider request for a bitbucket edgecase.
---
Part of https://github.com/codecov/engineering-team/issues/2824
> Optimize `update_commit_from_provider_info`

- services/processing/processing.py
- services/report/__init__.py
- services/report/raw_upload_processor.py
- services/report/tests/unit/test_process.py
- services/tests/test_report.py
- tasks/tests/unit/test_upload_processing_task.py
The `process_raw_upload` function would previously get a partial `report` as one of its arguments, to merge the processed upload into.
As this has changed fundamentally with parallel upload processing, we can just return the processed `Report` directly.
> Make `process_raw_upload` return the `Report` directly

- tasks/notify.py
- tasks/tests/unit/test_notify_task.py
- tasks/tests/unit/test_upload_finisher_task.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/tests/utils.py
- tasks/upload_finisher.py
- tasks/upload_processor.py
This field is constantly being updated/touched in both `UploadFinisher` and `Notify`.
But I couldn’t find any piece of code that actually reads this field across the whole codebase.
---
Moves and debounces the update to `Repository.updatestamp`, fixes https://github.com/codecov/internal-issues/issues/1043
---
Stops setting `Commit.pullid` in `UploadFinisher`.
This already happens as part of `{PreProcess,}Upload`, so it is not needed to set this field once again.
This also cleans up the code quite a bit.
---
Part of https://github.com/codecov/engineering-team/issues/2824
> Do not update `Commit.notified`

- services/processing/merging.py
- services/processing/processing.py
- services/processing/types.py
- services/report/__init__.py
- services/tests/test_report.py
- tasks/tests/unit/test_upload_finisher_task.py
- tasks/tests/unit/test_upload_processing_task.py
- tasks/upload_finisher.py
This avoids updating the `Upload` state in the first `UploadProcessor` job, deferring that work to the final `UploadFinisher`, which was doing the same anyway.
This way, it is also possible to run the `UPDATE`, as well as all the `INSERT`s for either `UploadError` or `UploadLevelTotals` (which we should start removing) in bulk.
> Only update the `Upload` once in `UploadFinisher`

- tasks/upload_finisher.py
Fixes [WORKER-Q11](https://codecov.sentry.io/issues/6051507644/) which is a recent regression.
> Account for `Repository.updatestamp` being nullable

- .github/workflows/ci.yml
This will add another comment to be emitted on our PRs to dogfood `basic-test-results`.
> Update workflow to use basic-test-results

- tasks/cache_test_rollups.py
- tasks/cache_test_rollups_redis.py
this fixes an error where the cache tasks only expect one arg instead of all the actual args
> fix: cache tasks args

- services/processing/merging.py
- services/report/raw_upload_processor.py
- tasks/compute_comparison.py
- tasks/tests/integration/test_upload_e2e.py
- tasks/upload_finisher.py
This change tries to optimize the slow `Report.merge` operation.
When merging report `B` into an existing report `A`, we can just use `B` in case `A` is empty. Also, the speed of merging depends on the size of the right hand size Report (`B` in this example). By swapping the reports, we can make sure to always merge the smaller Report into the larger one.
> Optimize Report merging

- rollouts/__init__.py
- services/processing/intermediate.py
- services/processing/processing.py
- tasks/tests/integration/test_upload_e2e.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
- tasks/upload_finisher.py
- tasks/upload_processor.py
The feature has been fully rolled out by now, so it is time to clean up the transitional code.
> Hardcode and cleanup `intermediate_reports_in_redis` feature

- tasks/cache_test_rollups.py
there's an error where the cursor of the serialized table BytesIO is not at the start which causes it to fail writing to GCP, this fixes that
> fix: cache rollup task serialization

- tasks/cache_test_rollups.py
polars is having trouble inferring the schema for flags, i'm guessing that it's because at the start of the data that we're reading from, there's a bunch of null values for the flags, so i'm manually making it so the schema expects a list of strings
> fix: polars schema inference issue

- django_scaffold/settings.py
- tasks/cache_test_rollups.py
- tasks/cache_test_rollups_redis.py
This PR updates the Test Result bucket for stage env to use the env variable, which should be codecov by default and codecov-staging on stage
> fix: Update bucket name for TA Stage result storage

- services/processing/merging.py
- services/report/__init__.py
- services/report/raw_upload_processor.py
- services/report/tests/unit/test_process.py
- tasks/tests/unit/test_upload_finisher_task.py
- tasks/tests/unit/test_upload_processing_task.py
This functionality was temporarily broken due to parallel processing, and this restores that functionality.
Additionally, this also logs any time this flag is triggered to Sentry to assist in figuring out who is actually using this.
> Fix `joined=False` functionality

- services/path_fixer/__init__.py
- services/path_fixer/tests/unit/test_path_fixer.py
- services/report/languages/cobertura.py
- services/report/languages/helpers.py
- services/report/report_builder.py
Calls to the PathFixer are very hot in report processing. I have the suspicion that some formats might call the path fixer multiple times for the same file. So it might be beneficial to go through a small cache in that case.
Previously, each call to `create_coverage_line` would call `supports_labels` which goes through all of the flags in the yaml config. As this result never changes, this will now cache the result for the whole processor.
> Optimize repeated path-fixing and calls to `supports_labels`

- conftest.py
This also fixes an issue with the `test_postgres_sqlalchemy` teardown if we don't want to keep the DB.
> Allow for "reuse_db" test functionality

- services/test_results.py
- services/tests/test_test_results.py
- tasks/tests/unit/test_test_results_finisher.py
we want to add python codee formatting to the code blocks in the TA PR comment so that the code blocks have some highlighting even though it's not completely accurate to the content of the code block
> feat: add formatting to code blocks in PR comment

- helpers/email.py
- tasks/send_email.py
- tasks/tests/integration/test_send_email_task.py
Our emails were adding an extra `text/` to the `text/html` MIME type on our emails, causing only the text content to display in gmail web client (though mailhog handled this fine interestingly).
Also adds "Codecov" as the display name for our emails.
> fix: MIME type for HTML emails

- services/report/languages/bullseye.py
- services/report/languages/clover.py
- services/report/languages/cobertura.py
- services/report/languages/csharp.py
- services/report/languages/helpers.py
- services/report/languages/jacoco.py
- services/report/languages/jetbrainsxml.py
- services/report/languages/mono.py
- services/report/languages/scoverage.py
- services/report/languages/vb.py
- services/report/languages/vb2.py
- services/report/report_processor.py
fixes https://github.com/codecov/internal-issues/issues/965
we import `xml.etree.ElementTree.Element` but what we're actually using is `lxml.etree.Element`. we use lxml for xml parsing, not the standard library module:
https://github.com/codecov/worker/blob/8056e7b5978bac6d826c666fa81b001c18d97397/services/report/report_processor.py#L129
this caused a security alert to misfire
> fix type annotation mistake that caused a security detector to misfire

- services/report/raw_upload_processor.py
- tasks/upload.py
This adds Sentry `capture_message` to some rarely-used features, in order to help decide what to do about these.
> Log usage of niche features

- rollouts/__init__.py
- services/test_results.py
- services/tests/test_test_results.py
- tasks/sync_pull.py
- tasks/test_results_finisher.py
- tasks/tests/unit/test_sync_pull.py
- tasks/tests/unit/test_test_results_finisher.py
- remove flaky_shadow_mode feature flag
- simplify should_{write,read}_flaky_detection functions to
general should_do_flake_detection that checks whether to do either
- add check to make sure repo is not private and on a free plan or
team plan
- the new logic is:
- if a user has explicitly set flake_detection to false in their
yaml we don't do flake detection
- else:
- if a user is part of the feature flag we do flake detection
- else if the repo is private then we require them to be on a
pro plan
- else we do flake detection
> feat: don't do flake detection on private repos not on the pro plan

- services/comparison/types.py
- tasks/notify.py
- tasks/tests/integration/test_notify_task.py
A recent change to default to an empty `Report` for the `Notify` `Comparison` unfortunately broke a different case which now errors because of a non-existant `FullCommit.commit`.
---
This reverts half of https://github.com/codecov/worker/pull/881, as it was causing [WORKER-Q27](https://codecov.sentry.io/issues/6064335366/)
> Revert defaulting to an existing `Report` in Notify

- tasks/test_results_processor.py
i want to find out if the reason the json decode errors are occuring is because we are re-processing uploads that have already been processed before. I also don't want to hard crash if we run into a json decode error
> fix: add some sentry emits to debug json error

- Makefile
All the `Skipping timeseries migration` logs are due to the fact that a timeseries database is configured (by default) but it's not enabled, which doesn't trigger the migration and hence the warning. We _could_ probably also remove the warning, as it's kind of noisy. But this is quicker, because the warning is in [`shared`.](https://github.com/codecov/shared/blob/511b553fd19113f1716326b0363b9d9a4afca1d7/shared/django_apps/db_routers/__init__.py#L36)
I could also be convinced to just set line 207 to hardcode `TIMESERIES_ENABLED=true` (this will affect the tests in CI, but this doesn't really affect test runs). 
BTW, running the tests on the `umbrella-hat` version of worker doesn't have this issue because the configuration in `umbrella-hat` sets `timeseries` to be enabled.
Look, I get it. …
> Enable timeseries for local testing environment

- services/report/languages/simplecov.py
- services/report/report_processor.py
related to https://github.com/codecov/engineering-team/issues/1520
i reviewed all of the uncaught exceptions during report processing. this PR addresses two of the highest-firing ones. others should be addressed but are more work and don't fire as frequently so i am punting on them
the `services/report/report_processor.py` change addresses a somewhat common uncaught exception: `ValueError: invalid literal for int() with base 10: 'ignored'`. JSON-ified simplecov reports have "ignored" as a coverage value for skipped lines. we should convert those to -1 which is [how the pyreport format represents skipped lines](https://github.com/codecov/shared/blob/511b553fd19113f1716326b0363b9d9a4afca1d7/shared/utils/merge.py#L300-L301)
the `services/report/languages/simplecov.py` change addresses the …
> fix: a couple uncaught exceptions during coverage processing

- services/notification/notifiers/mixins/message/__init__.py
- services/notification/notifiers/tests/unit/test_comment.py
- tasks/profiling_normalizer.py
this change also includes a change to the profiling normalizer because
it was breaking the linter
> fix: remove new feature comment section

- tasks/commit_update.py
- tasks/tests/unit/test_commit_update.py
when we update a commit, we want to ensure the commit's corresponding pull and branch are also upserted to reflect whatever changes were made to the commit
this is duplicating the logic in the `commits_insert_pr_branch` and `commits_update_heads` db triggers
> fix: upsert branch and pull when updating commit

- tasks/cache_test_rollups.py
This splits apart the individual subqueries into their own variables, and formats each of the queries.
(If you are curious, I just pasted the subqueries into https://sqlformat.org/)
> Split and format the test rollups query

- tasks/test_results_processor.py
it doesn't really help much and it causes errors if you try to decode a file that isn't utf-8 so just don't do it
> fix: don't show file_content in test results error

- helpers/log_context.py
- helpers/tests/unit/test_log_context.py
Instead of selecting ORM objects and have the ORM do related queries, this now explicitly lists only the needed fields using a single JOIN query.
Additionally, this also adds the `owner_plan` to the `LogContext`. This could potentially be used in the custom celery router.
> Add `owner_plan` to more focussed `LogContext` queries

- tasks/commit_update.py
- tasks/tests/unit/test_commit_update.py
we want to eventually replace the db triggers that exist to update the pull head and branch head when a commit is either inserted or updated
as a first step we want to duplicate the logic that those db triggers run in this commit update task which should run whenever a commit is inserted
the second step will be to run this task when a commit object is updated which is usually when we receive a webhook from github with some new information about a commit
the last step will be to remove the newly redundant db triggers
Fixes: https://github.com/codecov/internal-issues/issues/1027
> feat: update pull and branch head in commit update

- tasks/test_results_processor.py
the query with the join is the most expensive query in the db right now, this should improve it
> fix(ta processing): filter by flag_id instead of join

- tasks/test_results_processor.py
This eagerly inserts all the test / flags combinations, and uses a `on_conflict_do_nothing` to avoid duplicates.
Previously, this would resolve/fetch *all* the tests that have *any* repo flag, and deduplicate those on the python side.
That code was very slow, as the underlying query was extremely slow for unknown reasons. I also believe the code was potentially buggy, as it queried for *all* the tests with repo flags, not filtering for the specific flags we were interested in. Though it was probably fine, as the flags are part of the deterministic `test_id`.
In addition, this queries for the `flag_id` directly, turning it into a `set`, instead of using a `map` and a lookup for each test.
---
Fun fact, this function accounts for ~40% of all time in profiling:
> Handle Test/Flag inserts in the DB

- services/path_fixer/fixpaths.py
- services/path_fixer/tests/unit/test_fixpaths.py
- services/processing/processing.py
- services/report/__init__.py
- services/report/parser/legacy.py
- services/report/parser/tests/unit/test_version_one_parser.py
- services/report/parser/types.py
- services/report/parser/version_one.py
- services/report/raw_upload_processor.py
- services/report/tests/unit/test_parser.py
- services/report/tests/unit/test_process.py
- tasks/tests/unit/test_upload_processing_task.py
Removes a bunch of has/get methods in favor of accessing fields directly. Removes the `env` field completely.
Avoids a `BytesIO` indirection in the renamed `as_readable` method.
> Slight `ParsedRawReport` cleanup

- tasks/test_results_processor.py
the previous fix for this was not enough. what's currently happening is that we're processing the files, marking the upload as processed then we crash with none of the parsed testruns being persisted to the database
we need to make sure that we persist the processed tests to the database before marking an upload as processed and then we are safe to rewrite it as readable.
so the order for a successful parsing is:
process it -> write testruns to database -> upload.state = process -> db commit -> safe to rewrite
a failed parsing would be:
process it -> upload.state = failed -> db commit -> safe to rewrite
we never want the rewrite or the upload state to be updated before we persist whatever processed testruns we need to persist to the database
> fix(ta): handle random task retry better

- services/report/__init__.py
emitting sentry errors allows us to see when, for instance, processing timeouts spike, and we can click through to specific traces to see what's regressed in sentry
> log sentry errors for upload processing errors

- requirements.in
- requirements.txt
- services/yaml/__init__.py
- services/yaml/tests/test_yaml_saving.py
This will help us get rid of one of the repo triggers to update the bot/branch field ([here](https://github.com/codecov/codecov-api/blob/168d5f2b8f4f3081c9c4dd1e459ff0511ad33ab5/legacy_migrations/migrations/legacy_sql/main/triggers/repos.py#L13)). Branch is already updated, so we only need to update the bot field.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, …
> Update bot if we see that the bot field has changed in the YAML

- services/path_fixer/fixpaths.py
- services/path_fixer/tests/unit/test_fixpaths.py
- services/processing/processing.py
- services/report/__init__.py
- services/report/parser/legacy.py
- services/report/parser/tests/unit/test_version_one_parser.py
- services/report/parser/types.py
- services/report/parser/version_one.py
- services/report/raw_upload_processor.py
- services/report/tests/unit/test_parser.py
- services/report/tests/unit/test_process.py
- tasks/tests/unit/test_upload_processing_task.py
> Revert "Slight `ParsedRawReport` cleanup"

- services/yaml/__init__.py
https://github.com/codecov/worker/pull/926 has caused [WORKER-Q99](https://codecov.sentry.io/issues/6108679584/).
We have to use the `owner.service` (which is a DB enum containing `"github"`, etc) here instead of the `service_id`, which I believe represents an opaque ID of the repo *on a particular service*.
> Use the correct `owner.service` for `get_ownerid_if_member`

- services/repository.py
- tasks/tests/integration/test_notify_task.py
probably some side effects where we are persisting some changes as part of a failed task but for now this should alleviate some issues with lock contention in the db
> fix: commit transaction after updating pull

- templates/success-after-failed-payment.html
- templates/success-after-failed-payment.txt
Adds an email template for a successful payment after a failed payment. Trigger to come from API.
> feat: Add email template for success after failed payment

- services/test_results.py
- tasks/test_results_finisher.py
- tasks/tests/unit/test_test_results_finisher.py
This cleans up the code a bit, and removes usage of statsd metrics.
Some performance improvements here include avoiding querying the related `Upload` of failed tests multiple times, as well as fetching redundant pull request information in the `Notifier`.
Another optimization was related to querying per-outcome aggregations first, before querying for failures specifically. This avoids a N+1 query fetching all the related `Test`s.
---
> Cleanup and optimize `TestResultsFinisher`

- helpers/notifier.py
- services/test_results.py
- tasks/test_results_finisher.py
A recent change to load the `repo_provider` and `pull` ahead of time regressed the happy path of test results when no test failures are present. In that case, no notification has to be performed, so no `repo_provider` or `pull` is needed.
Additionally to fixing this regression, this also fixes the case when the `pull` is legitimately `None`, but the on-demand loading was trying to fetch it once again.
---
fixes a slight regression from https://github.com/codecov/worker/pull/924
> Resolve notifier `pull` on demand

- tasks/process_flakes.py
- tasks/sync_pull.py
- tasks/tests/unit/test_sync_pull.py
this was previously always running the reports test query but we don't need to query it if flake detection is not enabled
> fix: only query tests if flake detection enabled

- services/notification/notifiers/comment/__init__.py
- services/notification/notifiers/comment/conditions.py
- services/notification/notifiers/tests/unit/test_comment_conditions.py
"I think, for now, we just shouldn't send this PR comment (but still send statuses!) in the event that auto activate is disabled on the org repo settings."
> feat: don't send autoactivate pr comment if owner autoactivate is off

- .github/workflows/ci.yml
This will allow us to download the junit xml files that gets generated during CI run. Having the raw file will be useful for debugging test analytics stuff.
> Update CI to expose JUnit artifacts

- tasks/process_flakes.py
- tasks/sync_pull.py
- tasks/test_results_finisher.py
- tasks/tests/unit/test_process_flakes.py
- tasks/tests/unit/test_sync_pull.py
- tasks/tests/unit/test_test_results_finisher.py
we want to process test instances related to an upload only once. If an upload has already been taken into account we don't want to take them into account again.
we are still only processing test instances that are related to code that is on the main branch since this task is only being run when:
- we receive a sync pulls task for the PR associated with this commit (merge existing test instances)
- we process test results for this commit that come from the main branch (we receive new relevant test instances)
This PR then refactors the process flakes task to use bulk create and update for general efficiency and also commits the transaction after processing a single upload since that should be smallest unit of work that must get done
> fix(flakes): process uploads only once

- rollouts/__init__.py
- services/notification/notifiers/mixins/message/__init__.py
- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/mixins/message/writers.py
- services/notification/notifiers/tests/unit/test_comment.py
This is going to only be restricted to certain repos (specified in Feature Flag). And this is temporary, so there's a note to remove this code after a particular date.
Ref: https://github.com/codecov/engineering-team/issues/2987
> Add Impact Analysis Deprecation Message to end of comments

- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/tests/unit/test_comment.py
This was duplicated because it's also added at the end of the message. So, removing this from the footer to ensure that the message is on more comments. It is being hidden by a feature flag that checks for eligible repos, so the impact of this change should be fairly low.
See this PR for an example of the duplicate message: https://github.com/codecov/worker/pull/964#issuecomment-2549084965
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I …
> Remove the Impact Analysis Deprecation from footer

- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
we don't want to call the ta processors using a chord because we want to temporarily reduce the amount of lock contention in the database
this is a short term fix, we eventually want to move the test results writes to the finisher step, which will achieve the same effect as this fix
> fix: call ta processors using chain

- tasks/test_results_finisher.py
- tasks/test_results_processor.py
- tasks/tests/unit/test_test_results_finisher.py
- tasks/tests/unit/test_test_results_processor_task.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
i previously forgot that chains pass through a single previous result through all the tasks so this commit fixes that
we pass a boolean that at first is false, if at any point there is a single parsing success then it becomes true and means there was at least one success in parsing a test results file
the finisher then replaces the call to check_if_no_success with checking if the previous result is false
> fix: test analytics chain prev result handling

- helpers/log_context.py
- helpers/tests/unit/test_log_context.py
Make log context disableable in the case we want to test perf with it off.
> Making log context able to be disabled.

- requirements.in
- requirements.txt
Celery billiard has a bug where billiard.util.get_logger() is broken for Python 3.13.
> Use billiard>=4.2.1

- tasks/sync_pull.py
- tasks/tests/unit/test_sync_pull.py
this query is really expensive on the database so let's just remove it
> fix: remove test count query from sync pull

- database/engine.py
- database/tests/unit/test_engine.py
- helpers/timeseries.py
- services/tests/test_timeseries.py
- services/timeseries.py
- tasks/base.py
- tasks/tests/integration/test_timeseries_backfill.py
- tasks/tests/unit/test_timeseries_backfill_commits.py
- tasks/tests/unit/test_timeseries_backfill_dataset.py
- tasks/tests/unit/test_timeseries_delete.py
- tasks/timeseries_backfill.py
- tasks/timeseries_delete.py
We are using a different function in worker than in API to determine if timeseries should be enabled. This already exists in shared, so my change is just making use of that and adjusting tests as necessary.
> adjust fn used by worker to determine timeseries enabled

- helpers/log_context.py
- helpers/tests/unit/test_log_context.py
apparently populating the log context was slamming the commit table. so this PR stops using the commit table when populating log context
previously:
- if `commit_id` or `commit_sha`+`repo_id` were available, query the commits table to populate every field
- everything is populated this way, including `commit_id` (the DB PK for the commit)
now:
- `commit_id` and `commit_sha` will be set if available but not used to query anything else
- if `repo_id` is available, that will take care of populating the repo + owner
it's possible this will just move the problem to the repos table. if that is the case, it's solvable but will take a little elbow grease:
- transform `populate_from_sqlalchemy()` in `helpers/log_context.py` into `populate_log_context(kwargs) -> (Commit, Repository, Owner)` in …
> disable populating log_context based on commit_sha/commit_id

- tasks/compute_comparison.py
Attempting to help locks https://github.com/codecov/engineering-team/issues/3148
These 3 commits split the query into 3 different logs - verified by locally logging DB logs and seeing the query separate into these individual ones. 
> Split big commit's into 3

- services/path_fixer/__init__.py
- services/path_fixer/tests/unit/test_path_fixer.py
there are a couple issues in the base-path-aware path fixer:
- the regular path fixer early-exits if the passed-in path is `""`
- if the regular path fixer doesn't succeed, the base-aware path fixer retries with some prefixes (one of them being `./` for windows paths due to the other bug fixed in this PR)
- the regular path fixer is retried with the passed-in path of `""`, so it does not early-exit
- however, the next line strips `./` so the path is _turned into_ `""`
- `os.path.relpath()` gets mad
the base-path-aware path fixer uses the parent directory of the coverage file as its base. we use `PurePath` to figure out that parent directory, as it does not perform any actual disk operations, it's just path manipulations.
the issue is, `PurePath` on our Linux prod servers will instantiate …
> fix: handle empty/windows paths correctly in base-path-aware path fixer

- services/report/__init__.py
sibling PRs:
- https://github.com/codecov/gazebo/pull/3522
- https://github.com/codecov/shared/pull/431
- https://github.com/codecov/codecov-api/pull/1036
merge after the API PR has been deployed
when we receive a `SoftTimeLimitExceeded` exception we will now attempt to stop and save an upload error, but it's possible that we will get a hard timeout before we can actually commit. so there may still be timeouts that aren't properly coded. but hopefully for a lot of them we can display something more descriptive
> use new UploadErrorCode value for processing timeouts

- services/report/__init__.py
We're seeing this in Sentry, https://codecov.sentry.io/issues/5707951012/?project=4165036&statsPeriod=24h, likely because we're waiting till here https://github.com/codecov/worker/blob/57e5f92720532ce1099731be23e7908db718b89d/tasks/upload.py#L508-L509 to commit everything. This is an attempt to commit preemptively to help with DB lock contention
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, …
> Hopefully help DB lock contention

- celery_config.py
- conftest.py
- database/models/core.py
- requirements.in
- requirements.txt
- tasks/flare_cleanup.py
- tasks/tests/unit/test_flare_cleanup.py
New strategy for managing `flare` storage
depends on https://github.com/codecov/shared/pull/450
When a `pull` is no longer `OPEN`, leave the `flare` in order to reduce locks and wait time.
During low traffic hours (4am UTC?), run this task to clear it out of our database and Archive storage.
So we won't pay for maintaining the `flare` field but also won't slow down other `pull` actions by checking or clearing the field 🎉
> add FlareCleanupTask

- requirements.in
- requirements.txt
- services/report/__init__.py
- tasks/tests/integration/test_upload_e2e.py
- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
More lock contentions help! We have this query, https://codecov.sentry.io/issues/5707951012/?project=4165036&statsPeriod=24h, causing a bunch of N+1 queries. One of them is this one, so this is an effort to extract measurements inserts into one batched insert
> Add bulk_create fn to upload processes to help w/ lock contention

- services/notification/notifiers/mixins/status.py
I'm working on [this ticket](https://github.com/codecov/engineering-team/issues/1605) and [this ticket](https://github.com/codecov/engineering-team/issues/1626), which are changing the messaging coming out of this flow around `target` and `threshold`.
`StatusPatchMixin` and `StatusProjectMixin` are similar, but doing things differently, ie
`head_coverage + threshold >= target_coverage` vs `head_coverage >= (target_coverage - threshold)` 
No behavior/logic changes, just cleanup to make them more uniform and easier to understand.
> clean up status mixins

- database/models/profiling.py
- database/models/staticanalysis.py
- database/tests/factories/profiling.py
- database/tests/factories/staticanalysis.py
- django_scaffold/settings.py
- requirements.in
- requirements.txt
This pulls in the following newly moved to `shared.django_apps`: `compare`, `labelanalysis`, `profiling` and `staticanalysis`
---
Depends on https://github.com/codecov/shared/pull/469
> Install more shared `django_apps`

- database/events.py
- database/tests/unit/test_events.py
In self-hosted / enterprise, our customers may not always have shelter deployed. Add a check for those signals that call shelter to confirm first that shelter is enabled.
This PR is paired with a similar fix done in api [here](https://github.com/codecov/codecov-api/pull/1093) to fix `regenerateOrgUploadToken` when shelter disabled.
Closes https://github.com/codecov/engineering-team/issues/3212
> fix: Handle disabled shelter signals

- database/models/core.py
- database/tests/factories/core.py
- database/tests/unit/test_models.py
- requirements.in
- requirements.txt
- services/bundle_analysis/notify/contexts/tests/test_comment_context.py
- services/bundle_analysis/notify/contexts/tests/test_commit_status_context.py
- services/decoration.py
- services/seats.py
- services/tests/test_billing.py
- services/tests/test_decoration.py
- services/tests/test_urls.py
- services/urls.py
- tasks/new_user_activated.py
- tasks/tests/unit/test_ta_finisher_task.py
Decoration service was causing confusion for GitLab users. Cleaned it up and added some comments to clarify the current GL org strategy which is: 
- the root org owns the plan, so when dealing with a GL org's plan, look at the plan from the root org
- membership and activation through `plan_activated_user` also happens on the root org instead of a subgroup org
- if a notification has the `plan` or `member` url, give GL users the correct url (correct url is to root group, not subgroup)
more details on ticket https://github.com/codecov/engineering-team/issues/2710
> add root_organization property to worker, clean up decoration service, change notification urls for GL

- database/enums.py
- database/models/reports.py
- database/tests/factories/core.py
- database/tests/factories/reports.py
- services/comparison/__init__.py
- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/mixins/message/writers.py
- services/notification/notifiers/tests/integration/test_comment.py
- services/notification/notifiers/tests/unit/test_comment.py
- services/test_results.py
- services/tests/test_test_results.py
- tasks/notify.py
- tasks/ta_finisher.py
- tasks/ta_processor.py
- tasks/test_results_finisher.py
- tasks/tests/unit/test_notify_task.py
- we want to persist upload errors in the ta_processor
- we want to surface those errors when we notify either TA or coverage
> Handle TA upload error

- ta_storage/pg.py
- tasks/ta_finisher.py
- tasks/test_results_processor.py
- removes functions we don't use anymore
- fixes the insert on conflict condition to be test_id instead of the previous set of fields when inserting tests in the new TA processor
- adds a log to help debug when we're rewriting readable reports in TA
> fix test analytics

- database/enums.py
- services/notification/__init__.py
- services/notification/notifiers/checks/patch.py
- services/notification/notifiers/mixins/status.py
- services/notification/notifiers/status/patch.py
- services/notification/notifiers/tests/unit/test_checks.py
- services/notification/notifiers/tests/unit/test_status.py
- tasks/tests/integration/test_notify_task.py
The goal of this epic is to communicate details about check or status failures in the other notifiers, like pr comment.
This is part 1, which is mostly new data structures and variables, and handling of notifications.
Right now we collect all notifications and execute them in any order, they are all independent and they don't know about each other. In this pr, I split notifications into 2 categories (checks/status notifications, or other notifications). Now the check/status notifications go first, because their outcome will impact the messaging in the other types of notifications.
The specific condition I will tackle next: add custom helper text for users that have specified a `target` in their `yaml`. If their check/status fails, we will add a message to the pr comment telling them that …
> Failed check and status messaging in comment, part I

- database/enums.py
- services/notification/__init__.py
- services/notification/notifiers/checks/patch.py
- services/notification/notifiers/mixins/status.py
- services/notification/notifiers/status/patch.py
- services/notification/notifiers/tests/unit/test_checks.py
- services/notification/notifiers/tests/unit/test_status.py
- tasks/tests/integration/test_notify_task.py
> Revert "Failed check and status messaging in comment, part I"

- services/cleanup/models.py
- services/cleanup/owner.py
- services/cleanup/repository.py
- tasks/delete_owner.py
- tasks/flush_repo.py
- Deleting non-existing files can raise, so catch and ignore such errors
- Switch "Shadow Owner" to a `raw_delete` to avoid expensive django `SET NULL` / `CASCADE` queries
- Use a `SELECT FOR UPDATE NOWAIT` when starting deletions to make this more resilient to conflicting tasks:
- This also catches "not found" when the repo does not exist, and "integrity" errors on duplicate shadow owner inserts.
- Last but not least, this makes the task explicitly retry on timeouts.
> Fix problems discovered in Repository Deletion

- codecov.yml
- database/enums.py
- services/notification/__init__.py
- services/notification/notifiers/checks/patch.py
- services/notification/notifiers/mixins/status.py
- services/notification/notifiers/status/patch.py
- services/notification/notifiers/tests/unit/test_checks.py
- services/notification/notifiers/tests/unit/test_status.py
- services/notification/tests/unit/test_notification_service.py
- tasks/tests/integration/test_notify_task.py
this PR was missing a check and caused an error.
the check has been added and a unit test to cover the condition that broke when it was deployed.
perviously deployed and reverted version: https://github.com/codecov/worker/pull/1014
> redo: Failed check and status messaging in comment, part I

- codecov.yml
- services/notification/__init__.py
- services/notification/notifiers/base.py
- services/notification/notifiers/checks/base.py
- services/notification/notifiers/checks/checks_with_fallback.py
- services/notification/notifiers/codecov_slack_app.py
- services/notification/notifiers/comment/__init__.py
- services/notification/notifiers/generics.py
- services/notification/notifiers/mixins/message/__init__.py
- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/mixins/status.py
- services/notification/notifiers/status/base.py
- services/notification/notifiers/tests/unit/test_checks.py
- services/notification/notifiers/tests/unit/test_status.py
- services/notification/tests/unit/test_notification_service.py
when user has:
patch checks notifier OR patch status notifier
AND
AND
has defined a `target` in their codecov yml
AND 
the patch check/status fails
THEN
add some helper text to the comment notifier to point out that the check/status failed and that they can change their `target`.
https://github.com/codecov/engineering-team/issues/1626
> Failed check and status messaging in comment, part II

- services/cleanup/relations.py
- services/cleanup/tests/snapshots/relations__builds_delete_queries__owner.txt
- services/cleanup/tests/snapshots/relations__builds_delete_queries__repository.txt
- services/cleanup/tests/test_relations.py
The current implementation would still create subqueries of the form `foreign_pk IN (SELECT pk FROM table WHERE pk=123)`.
We can now detect these trivial lookups, and simplify those to `foreign_pk IN (123)`.
> Simplify dependent subqueries when possible.

- conftest.py
- main.py
- ruff.toml
- services/comparison/tests/unit/overlay/test_critical_path.py
- services/comparison/tests/unit/test_changes.py
- services/notification/notifiers/tests/unit/test_slack.py
- services/path_fixer/tests/unit/test_user_path_includes.py
- services/report/tests/unit/test_sessions.py
- services/tests/test_test_results.py
- tasks/tests/unit/test_brolly_stats_rollup.py
- tasks/tests/unit/test_notify_error_task.py
- tasks/tests/unit/test_profiling_collection.py
- tasks/tests/unit/test_profiling_normalizer.py
- tasks/tests/unit/test_sync_teams_task.py
- tasks/tests/unit/test_test_results_processor_task.py
- tasks/upload.py
This PR aims to add the ruff print rules to worker, and either removes or ignores each print statement (I just used my best judgement)
Ruff rules can be found here: https://docs.astral.sh/ruff/rules/#flake8-print-t20
Closes https://github.com/codecov/engineering-team/issues/3278
> dev: Add Ruff Print Rules to Worker (T20)

- database/models/reports.py
- generated_proto/testrun/ta_testrun_pb2.py
- protobuf/ta_testrun.proto
- requirements.in
- requirements.txt
- services/bigquery.py
- services/tests/test_bigquery.py
- ta_storage/base.py
- ta_storage/bq.py
- ta_storage/pg.py
- ta_storage/tests/test_bq.py
- ta_storage/utils.py
- tasks/tests/unit/snapshots/ta_processor_task__TestUploadTestProcessorTask__ta_processor_task_call__2.json
- generalize the way bigquery accepts query parameters
- change type of params arg in bigquery_service to sequence
- feat: add upload_id field to ta_testrun protobuf
- add flags_hash field to ta_testrun protobuf
- create new testid generation function
- add test_id to ta_testrun proto
- add flaky_failure to testrun protobuf
- handle flaky failures in ta_storage.bq
- create sql queries for reading from bq
- write tests for ta_storage.bq aggregate queries
> feat: improve ta_storage.bigquery

- services/cleanup/cleanup.py
- services/cleanup/models.py
- services/cleanup/relations.py
- services/cleanup/tests/snapshots/relations__builds_delete_queries__owner.txt
- services/cleanup/tests/snapshots/relations__builds_delete_queries__repository.txt
- services/cleanup/tests/test_relations.py
In todays episode of "the DB is slow for unexplainable reasons", we found out that querying `compare_commitcomparison` by **both** `base_commit_id` **OR** `compare_commit_id` is horribly slow. It is using a `Seq Scan` in that case for reasons unknown.
Splitting that `OR` filter up into two separate queries makes the DB use the appropriate indices, and the queries become instant. We can do this as the `OR` filter pretty much takes the union of both queries, which is equivalent of running both queries separately.
God only knows why, but here we are.
> Generate separate queries instead of `OR` filters

- services/notification/notifiers/checks/base.py
- services/notification/notifiers/checks/patch.py
- services/notification/notifiers/checks/project.py
- services/notification/notifiers/mixins/message/sections.py
- services/notification/notifiers/mixins/status.py
- services/notification/notifiers/status/base.py
- services/notification/notifiers/status/project.py
- services/notification/notifiers/tests/unit/test_checks.py
- services/notification/notifiers/tests/unit/test_status.py
- services/notification/tests/unit/test_notification_service.py
This is the same as the last one (https://github.com/codecov/worker/pull/1023) but for *project* rather than *patch* status and checks.
when user has:
project checks notifier OR project status notifier
AND
AND
has defined a target in their codecov yml
AND
the project check/status fails
THEN
add some helper text to the comment notifier to point out that the check/status failed and that they can change their target.
https://github.com/codecov/engineering-team/issues/1605
> Failed check and status messaging in comment, part III

- requirements.in
- requirements.txt
- services/bundle_analysis/notify/helpers.py
- services/bundle_analysis/notify/messages/comment.py
- services/bundle_analysis/notify/messages/commit_status.py
- services/bundle_analysis/notify/messages/tests/test_comment.py
- services/bundle_analysis/tests/test_bundle_analysis.py
should show negative numbers here as the size went down
> fix: Bundle Analysis - display negative number when size change goes down

- services/notification/notifiers/mixins/message/__init__.py
- services/notification/notifiers/tests/unit/test_comment.py
`layout` should be optional - docs [here](https://docs.codecov.com/docs/pull-request-comments#layout)
it's not optional in code and popped up [in sentry](https://codecov.sentry.io/issues/6254154285/events/8c287528c07f464c83068f7fa24a41ef/)
Added a test to show what the comment looks like with no `layout`, using the defaults we have set in code.
> layout should not be required

- tasks/test_results_processor.py
Turns out this was logging the complete "readable" contents of the uploaded test results. We shouldn’t do this.
> Do not log the complete upload contents

- rollouts/__init__.py
- services/comparison_utils.py
- tasks/compute_comparison.py
- tasks/compute_component_comparison.py
- tasks/tests/unit/test_compute_comparison.py
We're doing this for perf reasons. It's put behind a feature flag for now. We're gonna be queuing up one task per component which will "rebuild the world up to that point" by recreating the comparison and ComparisonProxy. There's no risk there because every transaction before that point will have committed. At that point it will find the component that it was tasked with computing the comparison for, and then compute the comparison for it and save that to the db.
> Parallelize compute component comparisons

- services/notification/notifiers/mixins/status.py
- services/notification/notifiers/tests/unit/test_checks.py
- services/notification/notifiers/tests/unit/test_status.py
- services/notification/tests/unit/test_notification_service.py
when user has:
project checks notifier OR project status notifier
AND
AND
has defined `removed_code_behavior` as `adjust_base` in their codecov.yml
AND
the project check/status fails
AND
the `adjusted_base` coverage does NOT allow the check/status to pass
THEN
add some helper text to the comment notifier to point out that the check/status failed, with links to `rcb` and `adjust_base` docs, and tell them the coverage on the head vs the adjusted base.
https://github.com/codecov/engineering-team/issues/1607
> Failed check and status messaging in comment, part IV

- services/notification/notifiers/checks/patch.py
- services/notification/notifiers/tests/unit/test_checks.py
two problems, one pr:
[sentry issue related to handling of this field](https://codecov.sentry.io/issues/6241627375/events/76de6cdb9fc64cb9872a858482d5b7f5/)
flips default on `annotations` from True to False https://github.com/codecov/engineering-team/issues/3295
> fix github checks annotations

- services/tests/test_timeseries.py
- services/timeseries.py
- services/yaml/__init__.py
- tasks/__init__.py
- tasks/save_commit_measurements.py
- tasks/tests/integration/test_timeseries_backfill.py
- tasks/tests/unit/test_save_commit_measurements.py
- tasks/tests/unit/test_upload_finisher_task.py
- tasks/upload_finisher.py
- tasks/upsert_component.py
similar to what i just did with the compute component task
when it comes time to upserting measurements in the save_commit_measurements
task, i added a feature flag and behind that feature flag i altered the
behaviour so that instead of upserting the measurements for each component
sequentially it will queue up a task for each component so that they can upsert
in parallel
I had to reorganize the code to avoid some circular imports hence save_commit_measurements
the function, being moved to tasks/save_commit_measurements.py
> feat: add parallel component computation to timeseries

- tasks/save_commit_measurements.py
- tasks/upsert_component.py
- while old versions of the code are still running the task save_commit_measurements may still receive none as the value for the dataset_names arg, so we must handle
- give upsertComponent task a task name
> fix: save_commit_measurements

- services/repository.py
- services/tests/test_repository_service.py
fixes https://github.com/codecov/engineering-team/issues/3289
i rearranged the function a little bit but the only change is that, if the owner already exists, we will make sure `owner.username`, `owner.name`, and `owner.email` are updated and then commit if anything changed.
> fix: change get_or_create_author() to upsert_author(). track username/name/email changes

- services/notification/__init__.py
- services/notification/notifiers/mixins/message/__init__.py
This PR aims to fix an N+1 query that was introduced when swapping to the plan model as the source of truth from the consts in shared for the same.
Previously we were calling the plan query n number of times depending on how many values get returned in line 179 here:
https://github.com/codecov/worker/blob/2508bbccd03eee0eca3624b6ea73fba1b8aa049c/services/notification/__init__.py#L179-L185
This cascaded down to https://github.com/codecov/worker/blob/2508bbccd03eee0eca3624b6ea73fba1b8aa049c/services/notification/__init__.py#L93-L94 and 
https://github.com/codecov/worker/blob/2508bbccd03eee0eca3624b6ea73fba1b8aa049c/services/notification/__init__.py#L73-L74 where since plan wasn't persisted on the NotificationService we were calling the query every single time.
My fix is to persist the plan …
> fix: N+1 query for plans / tiers

- services/notification/notifiers/mixins/status.py
- services/notification/notifiers/tests/unit/test_status.py
I noticed that the coverage comparison we do when we apply adjusted_base behavior does not take `threshold` into account. Talked with @aj-codecov, we think that if a user defines `threshold`, they would expect it to be applied to all coverage comparisons, not just some.
Therefore, I updated the comparison to include `threshold` if the user has set it.
Right now threshold doesn't change the `message` - this follows the pattern with the other `project` checks/status messages, where `threshold` is used in the comparison but not explicitly stated in the `message`.
> have adjusted base comparison use threshold

- services/notification/notifiers/checks/changes.py
- services/notification/notifiers/mixins/status.py
- services/notification/notifiers/status/changes.py
- services/notification/notifiers/tests/unit/test_checks.py
- services/notification/notifiers/tests/unit/test_status.py
- tasks/tests/integration/test_notify_task.py
when user has:
changes checks notifier OR changes status notifier
AND
AND
the change check/status fails
AND
there are unexpected/indirect changes
THEN
add some helper text to the comment notifier to point out that the check/status failed, with links to docs
https://github.com/codecov/engineering-team/issues/1627
> Failed check and status messaging in comment, part VI

- services/tests/test_timeseries.py
- services/timeseries.py
- tasks/save_commit_measurements.py
- tasks/upload_finisher.py
- tasks/upsert_component.py
This primarily moves the component filtering to a separate function, and removes a bunch of unnecessary code.
It now asserts preconditions instead of logging warnings, and removes the component deduplication code which I believe to not be relevant.
> Further simplify Component Measurements

- tasks/ta_finisher.py
- tasks/test_results_finisher.py
they were previously trying to call
self.schedule_new_user_activated_task, which didn't exist on either of those tasks
> fix: {ta, test results}_finisher tasks

- tasks/github_app_webhooks_check.py
- tasks/tests/unit/test_github_app_webhooks_check.py
- creates a counter for all webhooks (from github) that failed to be delivered, broken down by webhook event
- creates a counter for webhook redelivery requests (to github), broken down by whether the request succeeded or not
- reorganizes some logic to make the relationship between the filters and metrics clearer
ideally the redelivery counter would also have an event label, and both counters could have a label for the event. but i don't want to get too into this right now and it's not that important
right now we only do this webhook redelivery thing with github. not sure if other providers offer something similar, but if they do, the same counters have a "service" label and can be used
> add webhook failure/redelivery statistics

- services/test_results.py
- services/tests/test_test_results.py
- tasks/tests/unit/test_ta_finisher_task.py
- tasks/tests/unit/test_test_results_finisher.py
the current feedback issue is archived and we want to prompt users to take a survey about TA, but only if they're actively using TA, which is why it will only live on the TA comment.
fixes: https://github.com/codecov/engineering-team/issues/3326
> feat: change TA comment footer

- tasks/test_results_finisher.py
we want to easily find example TA comments
> chore: add log when making a TA comment

- services/test_results.py
- services/tests/test_test_results.py
- tasks/test_results_finisher.py
- tasks/tests/unit/test_test_results_finisher.py
we don't want to even try to notify if the pull is none, so i'm pushing that check out of the Notifier.notify() and overriding the base notify in the TestResultsNotifier, to expect a Pull
> refactor: improve test results finisher notify logic

- database/events.py
- database/tests/unit/test_events.py
We want to add these two fields to Shelter sync conditions
Ticket:
https://github.com/codecov/engineering-team/issues/3341
> Add private + owner to sync conditions for Shelter

- tasks/bundle_analysis_processor.py
- tasks/tests/unit/test_bundle_analysis_processor_task.py
Fix a retry issue where it doesn't trigger more than once and change the cooldown to be exponentially increasing
> Bundle Analysis: fix processor retry

- services/cleanup/cleanup.py
- services/cleanup/regular.py
Thi `regular_cleanup` cron task is a scheduled task that is used to clean up data that is not needed anymore.
In particular, it will delete all the storage associated with certain models, as opposed to just dropping the table.
As we have deprecated the "profiling"/"impact analysis" feature, and are about to drop the `ProfilingUpload` model completely, lets run it through this cleanup task to fully wipe all the uploaded data as well.
> Add `ProfilingUpload` to the `regular_cleanup` job

- requirements.in
- requirements.txt
- services/cleanup/models.py
- services/cleanup/owner.py
- services/cleanup/repository.py
- services/cleanup/tests/test_utils.py
- services/cleanup/utils.py
- tasks/delete_owner.py
- tasks/flush_repo.py
- tasks/regular_cleanup.py
This has various improvements to the cleanup tasks:
- First, it adds a `with_autocommit` contextmanager, which enables django autocommit for the various cleanup tasks. As the tasks are designed to be retried on timeouts, we still want to commit deletion progress as we go.
- It adds the `timeseries` cleanup to the `Repository` as well. Previously, when deleting all `Repository`s related to a parent `Owner`, this would have been skipped.
- Captures and ignores all the storage-related errors, and reduces the chunksize a bit. In particular the `regular_cleanup` is currently failing consistently because of some random storage-related errors. This shoul not stop progress on the deletion job.
> Enable autocommit for cleanup tasks, and other improvements

- rollouts/__init__.py
- services/notification/notifiers/mixins/message/__init__.py
- services/notification/notifiers/mixins/message/writers.py
- services/notification/notifiers/tests/unit/test_comment.py
This mainly removes the Impact Analysis Deprecation Notice from the code.
Also includes a change to remove a table reference from some clean up code.
> Remove Impact Analysis Deprecation Notice

- tasks/tests/unit/test_trial_expiration.py
- tasks/trial_expiration.py
`TrialExpirationTask` was doing outdated behavior, updating it to use PlanService's helper function instead
> update trial expiration task

- services/bundle_analysis/report.py
Starts fixing https://github.com/codecov/engineering-team/issues/3190 by first adding the error name to the logs and see what that gives back to us. From there we can start exploring the different exception types a bit easier
> dev: Add error type to log for better debugging

- helpers/sentry.py
- helpers/tests/unit/test_sentry.py
- tasks/base.py
Previously, Sentry was configured to drop such errors and not capture those.
I believe it is still valuable to capture these, even though they might be unactionable in lots of cases.
> Capture `SoftTimeLimitExceeded` errors

- Makefile
needed for https://github.com/codecov/umbrella/pull/4
we bindmount our local `worker` into the docker container. currently our local `worker` is the actual git repo, so the `git` invocation works. in umbrella, it's not the actual git repo, so the command fails
apparently this is all i need to change...?
> makefile changes for monorepo prep

- services/processing/merging.py
- services/report/raw_upload_processor.py
- tasks/upload_finisher.py
The `delete(_multiple)_sessions` function only exists on the `EditableReport`, so make sure to enforce that type, as well as optimizing the code so that it uses the batch-delete function.
> Correct the types needed to `delete_multiple_sessions`

- database/models/core.py
@calvin-codecov found that owners were still being created with users-basic, which is a value being derived from the DB
> fix: Update default plan value on owner model to DEFAULT_PLAN_VAL

- tasks/base.py
- tasks/tests/unit/test_base.py
`get_repo_provider_service()` can raise two exceptions which we do not consistently catch. from a quick scan of usages, it appears to make sense to handle them the same way across tasks, so this PR adds a wrapper method to `BaseCodecovTask` that behaves as follows:
- calls `get_repo_provider_service()`
- if `RepositoryWithoutValidBotError`, call `save_commit_error()` and return `None`. each task can decide whether it can proceed without a `repo_provider` or not
- if `NoConfiguredAppsAvailable`, there are two ways to handle it:
- if `exc.rate_limited_count > 0`, retry the task at the start of the next hour
- otherwise, return `None` and each task can decide whether it can proceed without a `repo_provider` or not
i created https://github.com/codecov/engineering-team/issues/3389 to keep …
> add get_repo_provider_service fn to base task

- tasks/tests/unit/test_upload_task.py
- tasks/tests/utils.py
- tasks/upload.py
depends on: https://github.com/codecov/worker/pull/1107
part of: https://github.com/codecov/engineering-team/issues/3389
> move upload task to get_repo_provider_service wrapper

- tasks/sync_repo_languages.py
- tasks/tests/unit/test_sync_repo_languages.py
depends on: https://github.com/codecov/worker/pull/1107
part of: https://github.com/codecov/engineering-team/issues/3389
> move sync_repos_languages task to get_repo_provider_service wrapper

- helpers/notifier.py
- tasks/ta_finisher.py
- tasks/test_results_finisher.py
prevously it wasn't checking these settings, but it lead to users getting the TA / upgrade comment only, so we should check it
> fix: TA should read comment config value

- tasks/process_flakes.py
- tasks/ta_finisher.py
- tasks/tests/unit/test_process_flakes.py
Previously, I made the decision to use a redis lock to exclude multiple process_flakes tasks from running for the same repo at the same time, so that we would minimize database concurrency issues. 
The idea was that I would set this redis key that represents "more flakes need to be processed for this repo" and that tasks that failed to acquire the lock could rely on the currently running task to handle their work so they wouldn't have to block. I never actually implemented the part where the currently running task takes the work of tasks that ceded their work to it.
This commit implements that by replacing the value of the current redis key with a list of commits that need to be processed, this way the currently running task actually has access to the commits that need to be processed.
> fix: process flakes task redis lock and key

- conftest.py
- pyproject.toml
- services/cleanup/utils.py
- services/processing/merging.py
- services/report/report_builder.py
- services/report/tests/unit/test_process.py
- services/report/tests/unit/test_report_builder.py
- services/report/tests/unit/test_sessions.py
- tasks/tests/unit/test_delete_owner.py
- tasks/tests/unit/test_flush_repo.py
- tasks/tests/unit/test_label_analysis.py
- tasks/tests/unit/test_label_analysis_encoded_labels.py
- uv.lock
This function has been moved to `shared`, so can now be removed from `worker`.
> Update `shared` again, removing `change_sessionid`

- pyproject.toml
- uv.lock
The proposed PR to convert `api` to a `pyproject.toml` defines a different version for its `vcrpy` dependency. Lets unpin the dependency here, so a workspace pulling in both will work.
> Unpin `vcrpy`

- Makefile
- docker-compose.yml
- docker/test_codecov_config.yml
Rather than messing with ENV in docker, this uses the test-global `config.yml` to enable timeseries tests, and switches to a lighter-weight timescale docker image.
> Enable timeseries tests, differently

- .github/workflows/ci.yml
- .github/workflows/self-hosted-release.yml
Unblocks self-hosted release because we weren't passing in the uv.lock param to use that cached image, so it was referencing the requirements.txt image when that one is no longer being built
> fix: Pass in uv-lock for self-hosted cache image stuff

- pyproject.toml
- services/test_analytics/ta_timeseries.py
- services/test_analytics/tests/test_ta_timeseries.py
- services/test_analytics/utils.py
- uv.lock
this PR creates some utility functions for inserting and aggregating testrun data in timescale
`transaction=True` is required for the test_get_testrun_summary for the continuous aggregates to populate the data that is expected to be in the summary for the test to pass
depends on: https://github.com/codecov/shared/pull/508
> create utils for accessing testrun timescale models

- pyproject.toml
- uv.lock
Instead of reverting https://github.com/codecov/worker/pull/1133 and rolling the `shared` update back, this is rather fixing forward, and pulling in https://github.com/codecov/shared/pull/567 which reverts the bad config change.
> Update `shared` once again

- tasks/tests/unit/test_upload_task.py
- tasks/upload.py
impl_type is a literal that can be "old" | "new" | "both"
old: in the case of old it will keep running the it has been
both: it will run the timescale implementation of the TA proc
task but it won't be updating the upload state or deleting/rewriting
the raw upload
new: it will only run the new timescale implementation and it will
update the upload state and rewrite/delete the raw upload
> fix: pass impl_type arg to TA tasks instead of new_impl

- helpers/reports.py
I’m about to remove the additional arguments to `Report.get`, so lets first remove any remaining usage.
> Remove usage of additional `Report.get` arguments

- tasks/upload_finisher.py
It might be possible that `hard_time_limit` is `0`, in which case we would define a `0` TTL for the redis lock.
The problem here is that we have observed some data races related to this lock apparently not working as intended. The redis key / lock TTL-ing might be one cause of this.
> Fix `report_lock` TTL

- services/test_results.py
- services/tests/test_test_results.py
we don't want utils like this one that aren't talking to the database to require on objects related to the ORM
> types: don't use db model in test results notif

- tasks/notify.py
- tasks/tests/integration/test_notify_task.py
We have observed some slowness accessing the `CompareCommit`/`CommitComparison` table. This might be related to us not committing an insert/update right away. So lets do that, in the hopes that it will help with some DB lock contention issue.
> Explicitly commit after `save_patch_totals`

- services/test_analytics/ta_timeseries.py
- services/test_analytics/tests/test_ta_timeseries.py
our aggregation functions in the db assume the only states for the outcomes are: "pass" | "skip" | "failure" | "flaky_fail"
ideally we should change the aggregation functions to not care about the values of the outcome column (do something like the pivot operator from BQ)
> fix: replace error from parser lib with failure

- tasks/test_results_finisher.py
we previously were using the method of setting a key in redis to have a value to let the process flakes task know that there was more work to do, however this made it so the process flakes task would skip processing certain commits
this is a follow-up change to previous changes we made to the process flakes task: https://github.com/codecov/worker/pull/1101
this change makes it so the test results finisher is using the new method of queueing up commitids in redis before queueing up the process flakes task
there will be another change where we make it so process flakes no longer checks the old redis key and that will complete this change
> fix: ta finisher calls process flakes properly

- services/test_results.py
making this change because the test_ids used in timescale will be bytes instead of strs
> types: make TA notification payload generic

- services/cleanup/models.py
- services/cleanup/relations.py
- services/cleanup/tests/test_relations.py
- tasks/tests/unit/test_delete_owner.py
For some reason, our postgres is unable to properly optimize a delete query on certain tables, which are using a subquery in the where clause.
It turns out that unrolling that subquery within Python works just fine however. So lets do just that.
As we are building all of the delete queries dynamically based on django relations (or some manually defined ones as well), we have to use some queryset magic as well to reverse those automatically created subqueries.
So another method was added which can parse the `IN (...)` subquery out of a queryset, in order to execute that separately, and issue N+1 delete queries on the target table.
> Allow unrolling subqueries in cleanup task

- services/test_analytics/utils.py
- tasks/upload.py
we don't want to try to use timescale for TA if the config settings aren't enabling it
depends on: https://github.com/codecov/worker/pull/1150
> fix: impl_type detected in upload.py

- services/comparison/__init__.py
- services/notification/tests/unit/test_comparison.py
As the `rust_report` is hard-enabled because `get_impacted_files` depends on it, we are also unconditionally running both implementations of `get_changes`.
But those two implementations differ in some details, and we are spamming logs with a ton of differences that noone ever looks ate to eventually move the implementation one way or the other.
So lets just remove this comparison code for a tiny speedup.
> Remove `get_changes_using_rust` usage

- tasks/tests/unit/test_compute_comparison.py
The mocks are setting this to `True`, which is the default anyway.
> Remove `should_load_rust_version` mocks

- conftest.py
- docker-compose.yml
- docker/test_codecov_config.yml
- services/test_analytics/ta_processing.py
- services/test_analytics/ta_processor.py
- services/test_analytics/tests/conftest.py
- services/test_analytics/tests/samples/sample_test.json
- services/test_analytics/tests/snapshots/ta_processing__insert_testruns_timeseries__0.json
- services/test_analytics/tests/test_ta_processing.py
- services/test_analytics/tests/test_ta_processor.py
- tasks/test_results_processor.py
deps on: #1078
we make use of the TA timeseries functions to process testruns
persisting them to Timescale instead of postgres
in test_results_processor we toggle which implementation to use
based on should_use_timeseries
> feat: new TA processor implementation

- Makefile
- pyproject.toml
- uv.lock
see resulting test file paths here: https://app.codecov.io/gh/codecov/worker/tests/matt%2Fmonorepo-friendly-junit
sort by "Last run" to get the results of the most recent attempt
this is a bit of a hack, but better solutions are all way, way easier after cutover and involve more invasive changes to how things work.
the worker/shared/api PRs pass `--rootdir=${PYTEST_ROOTDIR} -c pytest.ini` to pytest invocations. `--rootdir=${PYTEST_ROOTDIR}` allows us to override the rootdir, and `-c pytest.ini` makes sure pytest can still find its config when we do.
by default, the rootdir is `.`, which is the directory `pytest.ini` lives in. it's as if neither argument were passed at all. the original worker/api/shared repos use the default, so they are unchanged.
[the gha-workflows …
> emit junit results in a monorepo-friendly way

- services/processing/flake_processing.py
we recently turned autocommit back on by default, but in the case of the process flakes task we explicitly want it on.
> fix: process flakes

- services/test_analytics/ta_cache_rollups.py
- services/test_analytics/tests/snapshots/ta_cache_rollups__cache_test_rollups__0.json
- services/test_analytics/tests/snapshots/ta_cache_rollups__cache_test_rollups_use_timeseries_branch__0.json
- services/test_analytics/tests/snapshots/ta_cache_rollups__cache_test_rollups_use_timeseries_main__0.json
- services/test_analytics/tests/test_ta_cache_rollups.py
- tasks/cache_test_rollups.py
- tasks/tests/unit/snapshots/cache_test_rollups__TestCacheTestRollupsTask__cache_test_rollups_use_timeseries__0.json
- tasks/tests/unit/snapshots/cache_test_rollups__TestCacheTestRollupsTask__cache_test_rollups_use_timeseries_branch__0.json
- tasks/tests/unit/snapshots/cache_test_rollups__TestCacheTestRollupsTask__cache_test_rollups_use_timeseries_main__0.json
- tasks/tests/unit/test_cache_test_rollups.py
we want to make it so the cache rollup task is capable of reading test analytics information from the timeseries db
this also changes the format of the dataframe being cached, so we'll also change the format of the path at which we will store the cached dataframe
the logic for reading from the timeseries db is:
- if no branch is specified -> read from the repo wide continuous aggs
- if a branch is specified
- if it's one of the more popular main branch names -> read from the branch scoped continuous aggregates
- else, directly aggregate from the individual testruns
> feat: implement cache rollup task using TA timeseries models

- services/processing/flake_processing.py
- services/test_analytics/ta_process_flakes.py
- services/test_analytics/tests/snapshots/ta_process_flakes__testrun_filters__0.json
- services/test_analytics/tests/test_ta_process_flakes.py
- tasks/process_flakes.py
- tasks/tests/unit/test_process_flakes.py
- remove code related to old upload states
- create implementation of flake processing that consumes data from timescale
- process flakes uses impl_type
idea is that we'll start with impl_type both for a while which will persist flakes to the current db table and the new one, then at some point we will detect flaky tests in the finisher by checking the new flakes table
> feat: implement flake processing using timeseries models

- services/report/tests/unit/test_process.py
- tests/test_debug.py
This now defines two skipped-by-default tests that are supposed to be manually invoked with some downloaded production artifacts to more easily be able to reproduce customer issues.
There is a test to run the raw upload processing, as well as a test that just loads a stored report into memory so it can be inspected further.
> Move debugging test

- conftest.py
there's a deadlock error that happens where the timescale background worker is running background jobs and we're altering the schema of the tables on which it's running the background job on, so we stop the background worker momentarily to allow the migrations to run.
> tests: fix sql_alchemy_db fixture for timescale

- conftest.py
- pyproject.toml
- uv.lock
deps on: https://github.com/codecov/worker/pull/1177
> build: update shared

- conftest.py
- services/test_results.py
- tasks/test_results_finisher.py
deps on: https://github.com/codecov/worker/pull/1177
> fix: update test results finisher to split out old impl

- conftest.py
- services/test_analytics/ta_timeseries.py
when we get bytes out of the DB using django it returns them as a
memoryview so if you want the actual values in bytes you must call
the bytes constructor on the memoryview
> fix: ta_timeseries flake set and dict

- services/bundle_analysis/report.py
- tasks/bundle_analysis_processor.py
- tasks/tests/unit/test_bundle_analysis_processor_task.py
Another attempt at ensuring we don't do BA processor task a bunch of times for each upload that comes in for a commit regardless of the report type. We only need to do cache the bundles one time, all subsequent calls are redundant. In the previous attempt it was directly querying the Upload model for all upload types which is slow, this rework ensures it doesn't directly query Upload and it only makes query if the repo has BA enabled.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my …
> Bundle Analysis: dedupe caching processing

- tasks/bundle_analysis_processor.py
> Bundle Analysis: Remove logging noise from retries

- services/processing/flake_processing.py
- services/test_analytics/ta_cache_rollups.py
- services/test_analytics/ta_metrics.py
- services/test_analytics/ta_process_flakes.py
- services/test_analytics/ta_processor.py
- tasks/cache_test_rollups.py
- tasks/test_results_finisher.py
- tasks/test_results_processor.py
we want to be able to measure the impact of the timescale changes so im adding relevant metrics
> chore: add TA metrics to grafana

- tasks/test_results_finisher.py
- tasks/tests/unit/test_test_results_finisher.py
we are currently not passing the impl_type to the rollups and flakes tasks in the finisher, even though the impl_type might be both, which means the tasks aren't running the logic they should be according to the feature flag
> fix(ta): pass impl_type in finisher

- tasks/process_flakes.py
this is the final step in moving the process flakes task to using the new method of fetching commit shas from redis. Since all TA finisher tasks are writing to redis using the new method, the process flakes task doesn't need to read the old method anymore, so we can remove that.
> fix: remove process flakes commit_sha arg

- services/test_analytics/tests/test_ta_cache_rollups.py
- tasks/cache_test_rollups.py
- tasks/tests/unit/test_cache_test_rollups.py
since all callers are using repo_id by this point we no longer have
to accept repoid as an arg
> fix: step 3 of changing cache task args

- services/test_analytics/ta_cache_rollups.py
- services/test_analytics/tests/snapshots/ta_cache_rollups__cache_test_rollups__0.json
- services/test_analytics/tests/snapshots/ta_cache_rollups__cache_test_rollups_use_timeseries_branch__0.json
- services/test_analytics/tests/snapshots/ta_cache_rollups__cache_test_rollups_use_timeseries_main__0.json
- services/test_analytics/tests/test_ta_cache_rollups.py
we want to be able to evolve the schema of the rollups and we can do that by including a version tag in the GCS object metadata.
However, even though in this case we're making the change in worker first, in the future, we should modify the reading code to handle the new schema before modifying the write code, since if we deploy both reader and writer at the same time, its possible a rollup written by a new version of the writer is read by an old version of the reader which doesn't understand the new format
deps on: https://github.com/codecov/shared/pull/590
> feat: add version metadata in ta_cache_rollups

- Makefile
needed for https://github.com/codecov/umbrella/pull/30
umbrella wants to shell out to worker/api's `Makefile`s, but it needs to override some make variables when it does. for example, umbrella has to build requirements images differently, so it needs to inject its own `REQUIREMENTS_TAG` variable
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's …
> allow Makefile vars including REQUIREMENTS_TAG to be overridden

- services/report/tests/unit/test_transplant.py
- services/report/transplant.py
- tasks/__init__.py
- tasks/compute_comparison.py
- tasks/transplant_report.py
This new task is responsible for copying over the coverage report from one commit to another commit.
---
The commits for this feature:
- https://github.com/codecov/worker/pull/1190
- https://github.com/codecov/codecov-api/pull/1276
- https://github.com/codecov/codecov-cli/pull/677
> Add new `transplant_report` task and logic

- services/bundle_analysis/notify/contexts/comment.py
- services/bundle_analysis/notify/contexts/commit_status.py
- services/bundle_analysis/notify/contexts/tests/test_comment_context.py
- services/bundle_analysis/notify/contexts/tests/test_commit_status_context.py
- services/bundle_analysis/notify/messages/tests/test_commit_status.py
- services/seats.py
- services/test_analytics/ta_finish_upload.py
- services/test_analytics/tests/snapshots/ta_finish_upload__ta_finish_upload__0.txt
- services/test_analytics/tests/snapshots/ta_finish_upload__ta_finish_upload__1.txt
- services/test_analytics/tests/snapshots/ta_finish_upload__ta_finish_upload__2.txt
- services/test_analytics/tests/snapshots/ta_finish_upload__ta_finish_upload__3.txt
- services/test_analytics/tests/snapshots/ta_finish_upload__ta_finish_upload__4.txt
- services/test_analytics/tests/test_ta_finish_upload.py
- tasks/test_results_finisher.py
- tasks/tests/unit/test_test_results_finisher.py
this module is responsible for the new implementation of the TA finisher and it gets its test run and flake information from timescale and the new postgres flake table
> feat: create ta_finish_upload

- tasks/process_flakes.py
- tasks/test_results_finisher.py
I forgot to make it so when the old impl of the finisher runs with impl_type "both" it sets the redis keys for the new impl process flake task
> fix: new ta task flake processing

- services/test_analytics/ta_processing.py
- services/test_analytics/ta_processor.py
since we've observed a bit of replication lag between the primary and the TA read replica i just want to ensure we make these important reads from the primary to avoid any read-after-write inconsistencies
> fix: handle TA db replication lag

- rollouts/__init__.py
- services/notification/notifiers/mixins/message/__init__.py
temporarily adding a feature flag so support can manually disable this for customers until we make it configurable
> fix: manual toggle for cross pollination message
