database/models/core.py
tasks/flush_repo.py
tasks/tests/unit/test_flush_repo.py
tasks/tests/unit/test_upload_finisher_task.py
tasks/upload_finisher.py

Removes occurences of the repo cache field in the worker for https://github.com/codecov/platform-team/issues/92

Remove occurences of the Repo cache field

---

tasks/tests/unit/test_trial_expiration_cron.py
tasks/trial_expiration_cron.py

Only run this cron job for customers that have users-trial plan

Add condition to only expire if users on trial plan

---

services/notification/notifiers/mixins/message/__init__.py
services/notification/notifiers/mixins/message/sections.py
services/notification/notifiers/tests/integration/test_comment.py
services/notification/notifiers/tests/unit/test_checks.py
services/notification/notifiers/tests/unit/test_comment.py
tasks/tests/integration/test_notify_task.py

https://github.com/codecov/engineering-team/issues/296

Move feedback link out of footer section and always include at the bottom of a comment

---

.github/workflows/ci.yml

Fix prod tag to watch

---

.github/workflows/ci.yml

Use release create for prod

---

.github/workflows/ci.yml
Makefile

Use ATS not with action for now

---

.github/workflows/ci.yml

Use push of tag

---

docker/Dockerfile.requirements

Use alpine 3.18

---

.github/workflows/ci.yml
.github/workflows/self-hosted-release-pr.yml
.github/workflows/self-hosted-release.yml

Use the same sentry version

---

README.md

update badge in readme to show `ci.yml` workflow status

Update badge to GHA in readme

---

helpers/telemetry.py

fixes issues we've been seeing today hopefully

fix: remove timeseries timer use from base codecov task

---

.github/workflows/ci.yml
Makefile

Uploads test results to codecov

build: upload test results

---

.github/workflows/ci.yml

removed ats

---

requirements.in
requirements.txt

chore: update jinja dep

---

helpers/string.py
helpers/tests/unit/test_string.py
services/test_results.py
tasks/tests/unit/test_test_results_finisher.py

this commit also change the test results notifier to normalize line endings before escaping failure messages

feat: modify string escaper to take in list of strings as input

---

services/notification/notifiers/comment/__init__.py
services/notification/notifiers/tests/unit/test_comment.py

Fixes: https://github.com/codecov/engineering-team/issues/882

fix: clarify first time PR comment copy

---

services/bundle_analysis.py
tasks/bundle_analysis_processor.py
tasks/tests/unit/test_bundle_analysis_processor_task.py

see: https://github.com/codecov/engineering-team/issues/1364

Bundle Analysis - update commit.state when finished processing report

---

tasks/preprocess_upload.py
tasks/tests/unit/test_preprocess_upload.py

These changes add a verification for `PreProcessUpload` task already running in another worker pod. This is to avoid a report being created twice for the same commit.
Imagine the following scenario:
* You make 2 concurrent uploads (calling `create-report` twice for the same commit).
* Task A will get the lock and create a new report;
* Task A releases the lock and task B immediately gets it;
* Task A is commiting the transaction (outside the lock), at the same time task B passed [this point](https://github.com/codecov/worker/blob/e41ba11d68e37ffc7892e93954f68a7b0175cf93/services/report/__init__.py#L278) and is creating a new report;
* Task B creates a new report and saves it again;
I'm not sure if the report will have more sessions than it should, but the database will show more …

fix: check if PreProcessUpload is running

---

requirements.in
requirements.txt

Bump django version, ticket here https://github.com/codecov/internal-issues/issues/233

Upgrade django version (via shared)

---

requirements.in
requirements.txt

update shared sha for hotfix

---

.github/workflows/ci.yml

Bump version of workflow for prodvana staging trial

Bump version of workflow

---

helpers/string.py
services/test_results.py
tasks/tests/unit/test_test_results_finisher.py

Depends on #311 
Fixes: https://github.com/codecov/engineering-team/issues/1296
- Vertically stack file description
- Take into account existing breaks in insert_breaks function

Fix test results PR comment

---

services/flake_detection.py
services/tests/test_flake_detector.py

This class is given a dbsession, repoid and an optional failure normalizer Returns a list of tuples of flaky test id and the type of flake for that id

feat: add FlakeDetector class

---

requirements.in
requirements.txt
tasks/sync_repos.py
tasks/tests/unit/cassetes/test_sync_repos_task/TestSyncReposTaskUnit/test_sync_repos_with_feature_flag_django_call.yaml
tasks/tests/unit/test_sync_repos_task.py

Updates the usage of `check_value()` in `async def sync_repos_using_integration()` and `async def sync_repos()` in `tasks/sync_repos.py` to be async instead of sync. 
Those two functions, although defined as `async`, are all called synchronously using `async_to_sync` [here](https://github.com/codecov/worker/pull/327/files#diff-d8d7bad46669d55554c3cb6889670f1e49d874a5717842ea824b29bea3e71c63R99) so presumably it should've been find to use a syncronous `check_value()` function? but alas it still errored, so we'll just make it async

fix/chore: add "integration" test + use async Feature method

---

requirements.txt
services/report/__init__.py
tasks/parallel_verification.py
tasks/upload.py
tasks/upload_finisher.py

The same changes here: https://github.com/codecov/worker/pull/363 before I forced pushed the base branch. Didn't want to resolve 20 merge conflicts, so I squashed the relevant commits and cherry-picked it here.

feat: add parallel upload processing verification task

---

requirements.in
requirements.txt

update shared commit

---

services/bots.py

update stamp used

---

services/notification/notifiers/mixins/status.py
services/notification/notifiers/tests/unit/test_status.py

https://github.com/codecov/internal-issues/issues/365
[The docs](https://docs.codecov.com/docs/commit-status) imply that you should use `number%` for the `threshold` field, which breaks the code. I added graceful handling so that users with an invalid `threshold` in their yaml will no longer be blocked. If they have the `number%` format for their `threshold`, the code attempts to handle it, but if all else fails it will fallback to the `0.0` default and allow the operation to continue.

add handling for threshold decimal conversion error

---

tasks/backfill_gh_app_installations.py

add try/except to ensure task doesn't die mid way through

---

tasks/sync_repo_languages_gql.py

fixes https://github.com/codecov/internal-issues/issues/404

switch to bulk update

---

services/notification/notifiers/mixins/message/sections.py
services/notification/notifiers/mixins/message/writers.py
services/notification/notifiers/tests/integration/test_comment.py
services/notification/notifiers/tests/unit/test_comment.py

Fixes: https://github.com/codecov/engineering-team/issues/1672

fix: remove relaxed emoji from PR comment

---

helpers/sentry.py
helpers/tests/unit/test_sentry.py

Tag cluster for sentry

---

conftest.py
requirements.in
requirements.txt
services/report/__init__.py
services/report/raw_upload_processor.py
tasks/sync_repos.py
tasks/test_results_finisher.py
tasks/upload.py
tasks/upload_finisher.py
tasks/upload_processor.py

Update feature interface as according to https://github.com/codecov/shared/pull/205. Need to update shared hash once <- PR is merged
TLDR here, the information about what field we're rolling out over is now kept in DB and edited via django admin instead of awkwardly passing in owner_id or repo_id kwarg.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under …

chore: update feature interface

---

celery_config.py

Add toggle for profilings job

---

services/stripe.py

Pins stripe version to 2023 version
[Related docs](https://docs.stripe.com/upgrades#2023-10-16)

dev: Pin Stripe Version to V8

---

.github/workflows/ci.yml
README.md

Adjust the readme to reflect deployment changes - kept old instructions here https://www.notion.so/sentry/Release-and-Testing-0ec99ef359394d2993ffcad46ae72919 for posterity

Adjust readme

---

django_scaffold/settings.py
django_scaffold/tests_settings.py
pytest.ini
services/bundle_analysis/new_notify/contexts/tests/test_contexts.py
services/bundle_analysis/new_notify/messages/__init__.py
services/bundle_analysis/new_notify/messages/comment.py
services/bundle_analysis/new_notify/messages/templates/bundle_analysis_notify/bundle_comment.md
services/bundle_analysis/new_notify/messages/templates/bundle_analysis_notify/bundle_table.md
services/bundle_analysis/new_notify/messages/tests/test_comment.py

Introduces the MessageStrategy and the PR_comment specialization.
Templates for Markdown are more annoying than expected because of the `\n` after the tags.
But it's nice to have them in any case.
The process of building and sending the message depends on the NotificationContext that
is created previously.

refactor: template-based messages

---

services/test_results.py
tasks/test_results_finisher.py

partially fixes: https://github.com/codecov/engineering-team/issues/1604

feat: notif latency with flake detection tag

---

services/bundle_analysis/new_notify/__init__.py
services/bundle_analysis/new_notify/contexts/__init__.py
services/bundle_analysis/new_notify/tests/test_notify_service.py

Ties the previous PRs together in a new service for bundle analysis notifications.

refactor: service

---

tasks/tests/unit/test_upload_processing_task.py
tasks/upload_processor.py

Adds some types and simplifies code slightly.
---
Extracted from https://github.com/codecov/worker/pull/592

Cleanup `UploadProcessor` task a bit

---

services/test_results.py
services/tests/test_test_results.py
services/urls.py
tasks/test_results_finisher.py
tasks/tests/unit/test_test_results_finisher.py

Fixes: https://github.com/codecov/engineering-team/issues/2179

feat: update test results comment

---

services/notification/notifiers/checks/checks_with_fallback.py
services/notification/notifiers/comment/__init__.py
services/notification/notifiers/tests/unit/test_comment.py

Fixes part of: https://github.com/codecov/internal-issues/issues/670

fix: try to notify comment even when PR is closed

---

.github/workflows/ci.yml

Update ci.yml (#615)

---

services/seats.py
services/tests/test_seats.py

This function will determine whether the PR author needs to have their seat activation given an EnrichedPull object.
This function is being added because we want to add seat activation checking for bundle analysis and test analytics.
Relevant: 
https://github.com/codecov/engineering-team/issues/2264
https://github.com/codecov/engineering-team/issues/2254

feat: add determine_seat_activation function

---

requirements.in
requirements.txt

Update shared version

---

.github/workflows/ci.yml

updating workflows

---

database/events.py
database/tests/unit/test_events.py
requirements.in
requirements.txt

Updating shared to latest + adding a minor change from last PR https://github.com/codecov/worker/pull/649 I forgot 🙃. 
Shared changes include:
- https://github.com/codecov/shared/commit/ed35419cfb77006e35425376f06eb64147b77ae1
- https://github.com/codecov/shared/commit/fb871f36bc6d62dc644a61aa6780ab1b7454ada3
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, …

Update shared + add signals related changes I forgot in previous PRs

---

services/report/__init__.py

This primarily restructures the function a bit, adding some explicit comments where archive operations happen.
It also avoids some duplicated queries by avoiding calling the implicit `commit.report` accessor multiple times.

Restructure and optimize `save_report`

---

services/test_results.py
services/tests/test_test_results.py
tasks/tests/unit/test_test_results_finisher.py

fix: truncate floats in test results comment

---

helpers/pathmap.py

Profiling still reveals that building the tree is the slowest operation of processing a coverage report.
The PathFixer is very hot code, as it scales with the size of the monorepo.
This optimization replaces `dataclasses` with a simple constructor,
and replaces the `setdefault` call with manual code.
This is in the hope of making `Node` construction quicker, and avoid creating them if not needed.
This should hopefully speed up this code a bit, and lower pressure on the GC.

Further optimize PathFixer/Tree

---

helpers/pathmap.py
services/path_fixer/__init__.py
services/path_fixer/fixpaths.py
services/path_fixer/match.py
services/path_fixer/user_path_fixes.py
services/path_fixer/user_path_includes.py
services/report/fixes.py

Also rewrites parts of the custom fixes and includes rules.

Add types to PathFixer and friends

---

tasks/test_results_finisher.py

this commit also removes the sentry metrics in the test results finisher and replaces them with the helper.metrics metrics

fix: add log for when we detect a flake the read side

---

database/models/reports.py
tasks/test_results_processor.py
tasks/tests/unit/test_test_results_processor_task.py

this wasn't matching what is defined in the Django models and broke processing

fix: fix the TestFlagBridge model

---

helpers/github_installation.py
helpers/tests/unit/test_github_installation.py
services/repository.py
services/tests/test_repository_service.py
tasks/bundle_analysis_notify.py
tasks/commit_update.py
tasks/compute_comparison.py
tasks/notify.py
tasks/preprocess_upload.py
tasks/save_report_results.py
tasks/sync_pull.py
tasks/sync_repo_languages.py
tasks/upload.py
tasks/upload_processor.py

This reverts commit 76070910efd11807e94cdd14ef9af743346ab4f7.

Revert "Simplifies `get_installation_name` a bit (#749)"

---

docker/Dockerfile.requirements

https://github.com/codecov/internal-issues/issues/820

update python image

---

services/comparison/changes.py

Don't try to access `diff_json` if it is `None`

fix WORKER-2RX

---

requirements.in
requirements.txt

new shared

---

services/bundle_analysis/report.py

bundle analysis: metrics ref

---

services/repository.py

[WORKER-PZP](https://codecov.sentry.io/issues/6048975811/)

Fix `None` being fed into `int()`

---

Makefile

fix: make flags do the thing

---

tasks/test_results_processor.py
tasks/tests/unit/test_test_results_processor_task.py

Fixes: https://github.com/codecov/internal-issues/issues/1019

fix: minimize deadlocks

---

services/notification/notifiers/mixins/status.py
services/notification/notifiers/tests/unit/test_status.py

Fixes a simple devide-by-zero error in the `StatusProjectMixin`.
fixes https://github.com/codecov/internal-issues/issues/1061

Fix Zero Coverage in Status Notifier

---

tasks/README.md

Some of these tasks are outdated. It is probably better for us to just look at the tasks directly to get a sense of what tasks are available. Also removed some documentation that will get outdated quite easily.

Clean up outdated task documentation

---

services/notification/__init__.py
services/notification/tests/unit/test_notification_service.py

Fixes: https://github.com/codecov/feedback/issues/528

feat: toggle slack app from install config

---

requirements.in
requirements.txt

This is to add the uv changes.

Update shared to latest

---

tasks/commit_update.py
tasks/tests/unit/test_commit_update.py

- it's possible for branch.authors to be null, so check for that
- it's possible for commit.timestamp to be a str, so check and convert it if it is
- it's possible for commit.pullid to be None, so handle that
- it's possible for commit.branch to be None, so handle that

fix: various commit update errors

---

tasks/cache_test_rollups.py

This reverts commit 2ac43ea19b20dcb6a3cd1edb49c31d570e840ebc.
---
Turns out that *not* joining the actual `RepositoryFlag`s makes the query even worse, a *lot* worse :-(
Reverts https://github.com/codecov/worker/pull/898

Revert "Resolve test flags in python (#898)"

---

tasks/test_results_processor.py

This includes the following changes:
- Remove some needless indirections for types that are not used or only used a single time
- Add some missing types and remove needless type annotations
- Reformat a bunch of log lines and other things
- Remove usage of `statsd` metrics as I don’t think anyone uses those
- Introduce some Sentry metrics where that makes sense

Clean up `TestResultsProcessor` a bit

---

requirements.in
requirements.txt

Update shared, delta is only a single BA commit
https://github.com/codecov/shared/commit/45252f75524c38172b991a960bac964ec7b6f7d1

update to shared commit that uses newest bundle analysis processing

---

tasks/test_results_processor.py

refactors the test results processing task into functions and add the explicit sentry tracing decorator to ensure they're measured in profiles

refactor(ta proc): into functions and add tracing

---

tasks/tests/unit/test_upload_task.py
tasks/upload.py

Fixes: https://codecov.sentry.io/issues/6158446805/?project=4165036&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=1h&stream_index=3

fix: call chain in upload correctly

---

services/report/__init__.py

Revert "Hopefully help DB lock contention"

---

services/processing/processing.py
tasks/tests/unit/test_upload_task.py

Commit prior to build report from raw content

---

services/cleanup/models.py

For the case where we were deleting models with files in chunk, the actual `DELETE` query would be chained to the existing input queryset. That way, the resulting query would have `WHERE original_filter AND id IN (original_filter...)`. Now only the `IN` part should remain.
Also adds a bunch of tracing annotations to better see each phase, in particular these file deletions.

Further simplify the DELETE queries

---

services/cleanup/models.py

Carryforwarded `Upload`s inherit/copy the `storage_path` from the `Upload` they were based on. We only need to delete the file once (using the parent `storage_path`), so no need to try to delete the same underlying file multiple times.

Bulk-delete carryforward `Upload`s

---

services/notification/notifiers/mixins/status.py
services/notification/notifiers/tests/unit/test_status.py

when user has:
project checks notifier OR project status notifier
AND
AND
the project check/status fails
AND
has defined `removed_code_behavior` as `fully_covered_patch` in their codecov.yml
AND
there are unexpected/indirect changes (therefore check/status is still failing after applying `fully_covered_patch` behavior)
THEN
add some helper text to the comment notifier to point out that the check/status failed, with links to docs
https://github.com/codecov/engineering-team/issues/1627

Failed check and status messaging in comment, part V

---

services/cleanup/models.py

Previously, I was SELECTing the first N records, deleting the associated files, and then running the DELETE query using a subquery selecting those first N records again.
The primary reason was to avoid having to pass those primary keys through python, which generates suboptimal and "unique" (for N records) queries.
This approach does not work well when running the same function concurrently multiple times, as the DELETE is not idempotent regarding the previous SELECT.
Now I did change this to actually do the pk roundtrip through python, which makes the DELETE idempotent and resilient against running this in parallel. We might end up in a situation where parallel jobs try to delete the same records, but that is now an idempotent operation and does not cause any problems.
---
This solves …

Delete chunked rows based on PK

---

tasks/__init__.py
tasks/compute_component_comparison.py

this is necessary or else celery won't be able to route the task

make sure to import new task in tasks/__init__.py

---

celery_config.py
services/cleanup/cleanup.py
services/cleanup/regular.py
services/cleanup/relations.py
services/cleanup/tests/snapshots/relations__leaf_table__leaf.txt
services/cleanup/tests/test_regular_cleanup.py
services/cleanup/tests/test_relations.py
services/cleanup/utils.py
tasks/__init__.py
tasks/regular_cleanup.py

So far this is only hooked up to delete *all* th `ReportDetails`, which are unused.

Add a cron task running regular cleanups

---

services/test_results.py
services/tests/test_test_results.py
tasks/tests/unit/test_ta_finisher_task.py
tasks/tests/unit/test_test_results_finisher.py

Change copy in case of only 1 failed test

Change copy on failed tests drop down

---

services/test_results.py
services/tests/test_test_results.py
tasks/ta_processor.py

Just aligning the name with other error code in the DB. 

fix: Snakify error code in upload errors

---

requirements.in
requirements.txt

Bump shared

---

services/cleanup/models.py

Fixes [WORKER-RED](https://codecov.sentry.io/issues/6308024355/)

Fix timeseries parts of Repository cleanup

---

rollouts/__init__.py
services/test_results.py
services/tests/test_test_results.py
tasks/tests/unit/test_sync_pull.py
tasks/tests/unit/test_test_results_finisher.py

this also fixes a test that was previously not working correctly

feat: remove flake detection feature flags

---

services/test_results.py

we want to dedup set of test instances we consider by test_id in get_test_summary_for_commit the same way we do in
latest_failures_for_commit
we do this because we only want to consider the latest run for each test

fix: TA re-run processing summary

---

.github/workflows/upload-overwatch.yml
ruff.toml

Integrate overwatch to CI

---

services/notification/notifiers/mixins/message/__init__.py
services/notification/notifiers/mixins/message/sections.py

This consolidates a bit of code, and makes the logic a bit clearer which configured layout sections end up where.
It also removes a bogus "Additional details" expander in case none of its children are configured.

Refactor PR message section logic

---

.github/workflows/upload-overwatch.yml

Don't install ssl, working towards not having this be required.

---

services/processing/intermediate.py
services/processing/merging.py
services/processing/types.py
services/report/__init__.py
services/report/raw_upload_processor.py
services/report/tests/unit/test_sessions.py
tasks/upload_finisher.py

I have merged these two classes a while back, so lets replace the usage of the obsolete one.

Replace usage of `EditableReport` with `Report`

---

services/notification/notifiers/mixins/message/__init__.py
services/notification/notifiers/tests/unit/test_comment.py

sometimes the internet doesn't like the emojis. This makes them safe

fix emoji references

---

tasks/test_results_finisher.py
tasks/tests/unit/test_test_results_finisher.py

we're changing the callers to use repo_id

fix: step 2 of changing cache task args

---

pyproject.toml
uv.lock

chore: Bump shared version

---

services/test_analytics/ta_processing.py

not sure what i was doing here, branch can always be None

fix(ta): branch can be none

---

README.md

add note to README about migrating to umbrella
